### ISSUE TITLE
Configurable bikjang rule

### ISSUE THREAD

**Issue by kimqwer2** [ianfab/Fairy-Stockfish#101]
Hello. I am Korean. 
I don't know English and use a translator.
There is a rule called bikjang in Korean janggi, but it seems to be wrong in this program.
The bikjang is a rule that allows the intestines to eat and make it a draw.
for example
![캡처](https://user-images.githubusercontent.com/63884391/79623167-a776b780-8155-11ea-8f43-dc4ae61116f9.PNG)
In this case, white is very disadvantageous.
But white has a rule called bikjang.
White can be used to make a draw using a bikjang.
If the white moves to the right, the black head has nowhere to move.
bikjang
![캡처](https://user-images.githubusercontent.com/63884391/79624038-1bb35a00-815a-11ea-9152-76e73a4e47b6.PNG)
or
Even if the black escapes, the white will bikjang and become a draw.
![캡처](https://user-images.githubusercontent.com/63884391/79624084-68973080-815a-11ea-9ba9-1633d5f69297.PNG)
So black is very advantageous, but there is a bikjang,
We have to eat the white palace with the black palace and make it a draw.
in other cases (When it is black turn, The photo above is bikjang because it is the turn of the white.)
![캡처](https://user-images.githubusercontent.com/63884391/79623383-e8230080-8156-11ea-8bf9-d2aef675fa07.PNG)
In this case, black should not bikjang.
Like the picture above, you have to block the path of the palace and block the bikjang.
But this program is black trying to bikjang.
![캡처](https://user-images.githubusercontent.com/63884391/79623871-6da7b000-8159-11ea-8b99-ef331f061999.PNG)
Black tries to bikjang despite its advantage, so the winning game becomes a draw.
Therefore, I think the ganggi rule of Fairy-Stockfish is a little strange in this part.
In addition, it is popular in Korea that there is no bikjang, and bikjang is often used in janggi competitions.
It would be nice if you could choose the bikjang rule.
thank you for your interest in Korean janggi.

**Comment by ianfab** [comment]
Fairy-Stockfish uses Janggi tournament rules where in this situation black wins in bikjang by material count, so this behavior seems correct to me.

If I understand correctly you would like to have the result of the bikjang rule as a configurable option. This is problematic for performance reasons, but in any case the first step would be to allow to configure a variant where bikjang always is a draw, which makes sense to implement.

**Comment by ianfab** [comment]
I now implemented it in the way that you use tournament rules if you select variant `janggi` and casual rules (bikjang is draw) as variant `janggicasual`.

**Comment by kimqwer2** [comment]
Thank you. The bikjang of Janggicasual works very well.
And If Janggi = no bikjang rule,
I think Now Janggi(no bikjang  rule)is applied with the rules of other countries. 
The program determines that the leader wins if he eats the leader.
These rules do not exist in Korean organs.
Leaders are only related to bikjang rule, and not related to no bikjang rule.
Janggi is not related to each other even when leaders are in a straight line.
Janggi doesn't have a draw like bikjang.
Janggi doesn't win or lose like the current program.
for example
![캡처](https://user-images.githubusercontent.com/63884391/80138126-4cbedf00-85df-11ea-9c3f-fb9e0d4153ec.PNG)
Pictured above Janggi is applied (no Janggicasual)
(Up and left) is the reaction of the program at the turn of white.
(bottom, left) is the reaction of the program when it turns black.
The program ended the game in two situations.
But in the Janggi rule, neither situation is over.
Even if there are leaders in a straight line, the game continues because there is no impact.
White can play the game like (up, right).
Black can play the game like (bottom, right).
Everything can be moved except for things that cannot be moved.
![제목 없음](https://user-images.githubusercontent.com/63884391/80140189-94933580-85e2-11ea-90aa-ba8a7824e19b.png)
Any movement is possible.
The same is true for the white turn.
Thanks for reading.

**Comment by ianfab** [comment]
Do I understand correctly that you would like to disable the bikjang rule, i.e., as if it the rule did not exist?

**Comment by kimqwer2** [comment]
No
I think the bikjang rule you implemented is good.
Variant = Janggi Casual
->good
The bikjang rule is used a lot in Korean organ competitions.

and variant = Janggi
-> It's a rule that people use a lot.
What is described above is about variant = Janggi

Variant = Janggicasual -> bikjang rule = very good
Variant = Janggi -> no bikjang rule = This is what I want to modify.

The bikjang rule exists.
It's a rule that makes a draw like Janggicasual implemented in the current program.
What I'm trying to say is,
The current rule in Variant = Janggi is to think it is strange.
![캡처](https://user-images.githubusercontent.com/63884391/80149421-9adcde00-85f1-11ea-9c4e-965c79bea006.PNG)
In Variant = Janggi, these two influences do not go out of that square.
In Variant = Janggicasual, these two influences were on each other.

Variant = Janggi
All the other rules are correct.
but I think we're affecting each other now.

**Comment by ianfab** [comment]
If I understand correctly now, you want to keep the bikjang rule for "janggicasual", but remove it for variant "janggi". However, the idea of those two variants is:
* Variant `janggi` uses official modern tournament rules that avoid draws.
  * Bikjang is enabled and the result is ruled based on material count.
  * Repetitions are prohibited.
* Variant `janggicasual` uses casual/traditional bikjang rules
  * Bikjang always is a draw.

Variant `janggi` should represent the official tournament rules, and we will not change that. What we could do is to add a third variant that completely disables bikjang, if this would help.

**Comment by kimqwer2** [comment]
That's what I thought. You got it perfectly.
But I don't know the word "Bikjang is enabled."
The rule in Janggi, Korea is Bikjang = draw.
And every rule has a three-point repeat limit.
https://www.pychess.org/5tSMIMK9 cannot be repeated like this.
![캡쳐](https://user-images.githubusercontent.com/63884391/80160897-bf44b480-8609-11ea-8dc9-1762619cd13e.jpg)
The meaning of "3수" in the picture means 3 moves.
A -> B -> A is possible.
A->B->A->B is not possible. (The moment you leave 3 moves, you will be defeated.)
This applies to all rules so as not to take meaningless time.

I think "Variant = Janggicasual" is the closest rule to the Korean Janggi competition.
1 Bikjang always is a draw and results are based on material score.
2 Repetitions are prohibited. (3 move prohibited)

And the other "Variant" rule is...
1 There is no Bikjang and results are based on material score.
2 Repetitions Are Prohibited. (3 move prohibited)

I don't know what the rules for "Bikjang is enabled."
If you make a rule out of this,
1 Bikjang is enabled and results are based on material score.
2 Repetitions Are Prohibited. (3 move prohibited)

but I know that "Bikjang is enabled" = "Bikjang always is a draw."

**Comment by ianfab** [comment]
Thanks. Then for the moment let us call the third variant `jangginobikjang`. Can you help me to understand under which circumstances these different rule sets are used in Korea? Currently, my understanding is that:
* `janggi` (no draws) are the modern rules and used in professional competitions
* `janggicasual` (bikjang draw) are the traditional rules and still used in amateur games
* `jangginobikjang` (no bikjang) are unofficial simplified rules that are sometimes used in casual games, especially if one player maybe does not know the bikjang rule.

If this description is correct, maybe `janggicasual` should be renamed to something like `janggitraditional` for clarity, since the third rule set better fits the term "casual" than the second one.

**Comment by kimqwer2** [comment]
As far as I know, it's a perfect explanation.
Ordinary people don't use bikjang often.
Bikjang is used in amateur games, official games

I think it's perfect to change it this way as you claim.
jangginobikjang -> janggicasual
janggicasual       -> janggitraditional

**Comment by ianfab** [comment]
Thanks, I will do that then.

**Comment by kimqwer2** [comment]
I'm sorry. There must have been a mistake with the translator.
I understood that "no draw" is preferred for the development of the program.
Currently, there is no "no draw" rule for "Variant=Janggi" in Korea. (=rules not found in Korea)

To redefine it by a modified name,
janggi (no draws) = Special rules for program development (does not exist in Korea).
I understand that "no draw" is used in programs because it has a good effect on program development.

janggitranditional (bikjang draw) =  traditional rules and modern rules[(traditional rules and modern rules) = I understand that they use similar rules.]
, professional competitions, amateur games, Most official games
janggicasual (no bikjang) are unofficial simplified rules that are sometimes used in casual games

It exists in Korea. = janggitranditional(official rule) , janggicasual(unofficial rule)
It doesn't exist in Korea. = Janggi

**Comment by ianfab** [comment]
The reason for the "no draw" rules has nothing to do with program development, it only reflects the rules that are to my knowledge used in Janggi tournaments of professional players, which I know from a reliable source, and this topic has already been thoroughly discussed on [our discord server](https://discord.gg/aPs8RKr).

**Comment by kimqwer2** [comment]
As far as I know, the bikjang in Korea...
In the case of facing each other on the same line between the king and the king in Janggi
In the case of a draw in which the king eats the king when this condition is not resolved.

The rule that becomes bikjang (draw) in the same line (with nothing between the king and the king) exists only in the Korean style of Janggi.

Chinese style Janggi = In Xiangqi, there is a rule that the person who made the first (if facing each other from the same line between the king and the king) loses.

Chinese and Korean rules are different.
If this is an issue that has been discussed, I have nothing more to say. Thank you.

**Comment by ianfab** [comment]
Ok, thanks for the clarification.
