### ISSUE TITLE
Wrong ButterflyHistory array size

### ISSUE THREAD

**Issue by boardgame1** [ianfab/Fairy-Stockfish#110]
In janggi LARGEBOARDS defined, in types.h 431 line, SQUARE_NB is defined as 120.
In types.h 710 line
`template<MoveType T>
inline Move make(Square from, Square to, PieceType pt = NO_PIECE_TYPE) {
  return Move((pt << (2 * SQUARE_BITS + MOVE_TYPE_BITS)) + T + (from << SQUARE_BITS) + to);
}`

In MovePick.h 89 line
`typedef Stats<int16_t, 10692, COLOR_NB, int(SQUARE_NB + 1) * int(SQUARE_NB)> ButterflyHistory;`

'array subscript out of range' error occured at ButterflyHistory

**Comment by ianfab** [comment]
Thanks for reporting, bug confirmed.
