### ISSUE TITLE
Janggi repetition evaluation fluctuation

### ISSUE THREAD

**Issue by kimqwer2** [ianfab/Fairy-Stockfish#117]
![ook](https://user-images.githubusercontent.com/63884391/80818256-ccffc880-8c0d-11ea-97e5-1927c0d31bf0.png)
It's white on the left and black on the right.
White turns are valued at high value.
Black turns are evaluated to be similar to each other
According to the black movement, white values are evaluated to be similar again.
I think this has something to do with repetition.
It appears the same in all rules.

**Comment by ianfab** [comment]
Can you please provide the FEN of the position ("copy position") so that I do not have to set it up manually?

**Comment by kimqwer2** [comment]
I don't know how to use github.
Please check the discode. Jaggi Channel
