### ISSUE TITLE
Pruning issues in Breakthrough - SF does not see mate in 2

### ISSUE THREAD

**Issue by ianfab** [ianfab/Fairy-Stockfish#12]
As example this game:

[Event "Breakthrough Chess Game"]
[Site "ATELCO-PC"]
[Date "2018.11.07"]
[Round "-"]
[White "Michael Taktikos"]
[Black "Fairy-Stockfish 071118 64 (UCI2WB)"]
[Result "1:0"]
[TimeControl "40/240"]
[Variant "breakthrough"]
[FEN "pppppppp/pppppppp/8/8/8/8/PPPPPPPP/PPPPPPPP w - - 0 1"]
[SetUp "1"]

{--------------
p p p p p p p p
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
P P P P P P P P
white to play
--------------}
1. a2b3 c7d6 {-0.51/17 34} 2. h2g3 f7e6 {-0.42/15 5} 3. b4 g7f6
{-0.62/18 24} 4. f2e3 a7b6 {-0.40/16 2.9} 5. e2d3 d5 {-0.36/19 17} 6. d2c3
h7g6 {-0.77/18 11} 7. c4 d6 {+0.50/18 10} 8. b5 c8d7 {+1.32/16 2.5} 9. g2f3
b7c6 {+2.57/16 8} 10. b5a6 b7 {+4.82/17 22}
*
The bug is reconstruable: In winboard, menu edit/"copy game from clipboard", then go to move #10 and play manually 10.b5a6    SF will answer with 10... b7? 
Has nothing to do with your new evaluation tweaking, the bug was there before, I assume somewhere to heavy pruning, or an unwanted try to promote the breakthrough-piece so that it never reaches the last rank

_Originally posted by @mtaktikos in https://github.com/ianfab/Fairy-Stockfish/commit/fd6e178a1dee24a804a7c0615ff0faa19129d5c2#commitcomment-31212386_

**Comment by ianfab** [comment]
@mtaktikos Thanks, bug confirmed. For some reason the selective depth stays at 1, so the mate is never resolved. It might be related to the extremely high evaluation terms, but I have not fully understood the issue yet.

```
setoption name UCI_Variant value breakthrough
position fen p2ppppp/1p1pp3/Ppppppp1/3p4/2P5/3PPPP1/1PP5/PPPPPPPP w - - 0 11
go depth 10
```
```
info string variant breakthrough startpos pppppppp/pppppppp/8/8/8/8/PPPPPPPP/PPPPPPPP w 0 1
info depth 1 seldepth 1 multipv 1 score cp 787 nodes 85 nps 42500 tbhits 0 time 2 pv a6a7
info depth 2 seldepth 1 multipv 1 score cp 787 nodes 132 nps 66000 tbhits 0 time 2 pv a6a7
info depth 3 seldepth 1 multipv 1 score cp 787 nodes 293 nps 146500 tbhits 0 time 2 pv a6a7
info depth 4 seldepth 1 multipv 1 score cp 787 nodes 350 nps 175000 tbhits 0 time 2 pv a6a7
info depth 5 seldepth 1 multipv 1 score cp 787 lowerbound nodes 470 nps 235000 tbhits 0 time 2 pv a6a7
info depth 6 seldepth 1 multipv 1 score cp 787 lowerbound nodes 1237 nps 412333 tbhits 0 time 3 pv a6a7
info depth 7 seldepth 1 multipv 1 score cp 787 lowerbound nodes 2042 nps 510500 tbhits 0 time 4 pv a6a7
info depth 8 seldepth 1 multipv 1 score cp 787 lowerbound nodes 2798 nps 559600 tbhits 0 time 5 pv a6a7
info depth 9 seldepth 1 multipv 1 score cp 787 lowerbound nodes 10835 nps 515952 tbhits 0 time 21 pv a6a7
info depth 10 seldepth 1 multipv 1 score cp 787 lowerbound nodes 34278 nps 489685 tbhits 0 time 70 pv a6a7
bestmove a6a7 
```

**Comment by ianfab** [comment]
@mtaktikos Thanks a lot again for your report. It revealed a very subtle bug that seriously affects playing strength for variants with pieces that move in a different way than they capture (which so far comprises only breakthrough and hoppelpoppel). This explains why the performance in breakthrough was quite bad.

I will commit the fix for this soon.

**Comment by ianfab** [comment]
Mate finding seems to have further improved with https://github.com/ianfab/Fairy-Stockfish/commit/8950b5020adb1b207a835e9597bb735d00881af0. This is the first version I have difficulties winning against (but apart from having played a handful of games against Stockfish, I do not have much experience with breakthrough).

**Comment by mtaktikos** [comment]
There seems that an aspect of the pruning issue remains open.  Here a new game:

[White "Michael Taktikos"]
[Black "Fairy-Stockfish 101118 64 (UCI2WB)"]
[Result "*"]
[TimeControl "40/240"]
[Variant "breakthrough"]
[FEN "pppppppp/pppppppp/8/8/8/8/PPPPPPPP/PPPPPPPP w - - 0 1"]
[SetUp "1"]

{--------------
p p p p p p p p
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
P P P P P P P P
white to play
--------------}
1. a2b3 g7f6 {+0.06/19 2.2} 2. h2g3 f7e6 {+0.06/18 1.5} 3. c3 h7g6
{+0.06/19 2.8} 4. f2e3 a7b6 {+0.07/16 0.9} 5. d3 c6 {+0.07/16 1.2} 6. e2f3
b5 {+0.07/15 0.9} 7. f3g4 c6d5 {+0.08/13 0.3} 8. g3f4 d7c6 {+0.07/9} 9. c4
b4 {+0.12/6} 10. c5 {+0.15/20 17} c7 {+0.24/8} 11. a2 b6 {+0.24/9} 12. cxb6
cxb6 {+0.15/9} 13. a3 c5 {+0.11/9} 14. b3c4 bxa3 {+0.23/9} 15. bxa3 d4
{+0.07/9} 16. exd4 cxd4 {+0.10/8} 17. a3b4 d7 {+0.05/7} 18. d3e4 g5
{+0.14/9} 19. g3 e7d6 {+0.11/9} 20. b5 d3 {+0.01/8} 21. b1c2 d6e5
{-0.38/10} 22. f5 exf5 {-0.20/10} 23. gxf5 dxc2 {-0.38/10} 24. dxc2 e5d4
{-0.30/9} 25. b5a6 e7 {-0.35/9} 26. e4d5 f6e5 {-0.54/9} 27. d5e6 dxe6
{-4.59/10} 28. fxe6 d3 {-9.17/11} 29. e6d7 h8g7 {-1000.01/56}

After move #27 SF, doesn't see the mate in 3 that starts with 28.fxe6.
Even the mate in 2 with 29.e6d7 is noot seen by SF

I tried this your way, with direct input of the position after move #27:

setoption name UCI_Variant value breakthrough
position fen pp3ppp/4p3/Pp2p3/4pPp1/2Pp4/6P1/2P5/2P1PPPP w - - 0 28
go depth 10

Evaluation is high for White, but SF doesn't see the mate in 2

**Comment by ianfab** [comment]
To me it looks fine with the current version (8950b50). It finds mate within around 10-20 ms on my machine, which should be perfectly sufficient for a 40/240 game. Are you sure you compiled the most recent version? If so, it could basically only be an issue with the hash, since otherwise SF seems to easily find mate in the given position.
```
setoption name UCI_Variant value breakthrough
position fen pp3ppp/4p3/Pp2p3/4pPp1/2Pp4/6P1/2P5/2P1PPPP w - - 0 28
go depth 15
```
```
info string variant breakthrough files 8 ranks 8 pocket 0 template fairy startpos pppppppp/pppppppp/8/8/8/8/PPPPPPPP/PPPPPPPP w 0 1
info depth 1 seldepth 1 multipv 1 score cp 50 nodes 32 nps 32000 tbhits 0 time 1 pv f5e6
info depth 2 seldepth 2 multipv 1 score cp 63 nodes 61 nps 61000 tbhits 0 time 1 pv f5e6 a8a7
info depth 3 seldepth 3 multipv 1 score cp 81 nodes 102 nps 102000 tbhits 0 time 1 pv f5e6 b8b7 e6d7 b7a6
info depth 4 seldepth 4 multipv 1 score cp 75 nodes 178 nps 89000 tbhits 0 time 2 pv f5e6 g5f4 e6d7 f4g3
info depth 5 seldepth 5 multipv 1 score cp 295 nodes 746 nps 373000 tbhits 0 time 2 pv f5e6 b8b7 e6d7 d4d3 a6b7
info depth 6 seldepth 6 multipv 1 score cp 355 nodes 1352 nps 450666 tbhits 0 time 3 pv f5e6 d4e3 e6d7 e3e2 f1e2 e5f4 g3f4 g5f4
info depth 7 seldepth 7 multipv 1 score cp 442 nodes 3479 nps 869750 tbhits 0 time 4 pv f5e6 d4d3 e6d7 g5f4 c2d3 e5d4 g3f4
info depth 8 seldepth 8 multipv 1 score cp 562 nodes 7896 nps 987000 tbhits 0 time 8 pv f5e6 d4e3 e6d7 e3e2 f1e2 a8b7 a6b7 e5d4
info depth 9 seldepth 9 multipv 1 score cp 677 nodes 10136 nps 1126222 tbhits 0 time 9 pv f5e6 d4e3 e6d7 e3e2 f1e2 g5h4 g3h4 a8b7 a6b7
info depth 10 seldepth 11 multipv 1 score cp 781 nodes 12361 nps 1236100 tbhits 0 time 10 pv f5e6 d4d3 e6d7 d3e2 f1e2 g5h4 g3h4 a8b7 a6b7 b6b5 c4b5
info depth 11 seldepth 12 multipv 1 score mate 5 nodes 14642 nps 1331090 tbhits 0 time 11 pv f5e6 a8b7 e6d7 d4c3 a6b7 c3b2 c1b2 e5d4 d7c8
info depth 12 seldepth 10 multipv 1 score mate 3 nodes 16792 nps 1399333 tbhits 0 time 12 pv f5e6 g5h4 e6d7 e5e4 d7c8
info depth 13 seldepth 6 multipv 1 score mate 3 nodes 17516 nps 1347384 tbhits 0 time 13 pv f5e6 g5h4 e6d7 e5e4 d7c8
info depth 14 seldepth 6 multipv 1 score mate 3 nodes 18210 nps 1400769 tbhits 0 time 13 pv f5e6 g5h4 e6d7 e5e4 d7c8
info depth 15 seldepth 6 multipv 1 score mate 3 nodes 19017 nps 1462846 tbhits 0 time 13 pv f5e6 g5h4 e6d7 e5e4 d7c8
bestmove f5e6 ponder g5h4
```

**Comment by mtaktikos** [comment]
Had tried it only with "go depth 10", and OK, now with "go depth 15" I have the same output as you.
But this doesn't solve the problem:
Usually I play with the GUI winboard. In winboard, lets' paste the whole game with edit/"Paste game from clipboard", go to the above position, and then "Analysis Mode".
Here, the move 28.fxe6 is not found. Can you confirm this issue? (then it must be an issue with winboard.
And if it is one: until now, I found no way to play just with the engine from the command line, without winboard at all)

**Comment by ianfab** [comment]
I tried to reproduce it with XBoard (since I can not test it on Windows/with WinBoard at the moment), but there it works fine, I get the same results as on the command line. There is no need to use the command line in general, I only prefer it for debugging, since it is easier to reproduce the conditions and compare results. For playing, I usually use XBoard, Cutechess, or PyChess, depending on the variant.

I do not expect it to be any bug with WinBoard itself, but maybe the engine is not configured correctly, e.g., pointing to the wrong executable, or maybe it needs to be reloaded in case you did not close WinBoard when changing the SF version. If you get different results in the GUI and on the command line, there definitely is something fishy with the configuration in the GUI.

**Comment by ianfab** [comment]
@mtaktikos Do you still encounter issues or does it work fine?

**Comment by mtaktikos** [comment]
Breakthrough works now fine. The default for hash memory in winboard (version 4.9.170105) was only 16 MB, have increased it to 1024 MB, and the problem is solved .
However, there are massive issues with Sittuyin and connect4: in winboard, the pieces outside the board are invisible and I found no way no make a move. Even when SF plays connect4 with white, winboard gives the error "Illegal move 1.P@d1" (although legality testing is turned off)
Tried it with the old winboard-alien, but here occur the same problems, the  connect4 game is unplayable.
Obviously, there are massive differences between xboard and winboard

**Comment by ianfab** [comment]
Thanks for the feedback. Are you using the most recent version of the [uci2wb adapter](https://github.com/ianfab/uci2wb)? The support for customizing the board size and pocket was only added recently. In XBoard, connect4 worked for me if I remember correctly, but for sittuyin I think there were some issues with dropping the king. I will check it later today.

By the way, do you have some experience with breakthrough and can estimate SF's playing strength or recommend engines to compare against? So far I only know that it is able to defeat someone who has not played breakthrough before (i.e., me).

**Comment by mtaktikos** [comment]
Hi Fabian, if you look for software opponents in the game Breakthrough:
it is easy to implement Brakthrough it in Sjaak II RC5, simply edit in 
it's file variants.txt the following definition:

############################################################################################
Variant: Breakthrough (8x8)
Board: 8x8
FEN: "ssssssss/ssssssss/8/8/8/8/SSSSSSSS/SSSSSSSS w - -"
XBoard pieces: ".......W...S.................w...s............"
BlackFlag: a8,b8,c8,d8,e8,f8,g8,h8
WhiteFlag: a1,b1,c1,d1,e1,f1,g1,h1

Piece: Sheep
Move: step N, NE, NW
Capture: step NE, NW
Symbol: "S", "S,s"
value 1350

Rule: captureanyflag = win
Rule: stalemate = win

############################################################################################

Against SF, Sjaak plays very weak.
In "Zillions of games", there exist a script Breakthrough.zrf - but also 
very weak against SF
Even Winand's strong engine GameMaster 2 that participated in Computer 
Olympiads  (downloadable in 
https://dke.maastrichtuniversity.nl/m.winands/loa/download.html)
loses against SF
There are some untested engines - first of all Fabien Letouzey's 
Breakthrough engine, a fork of the source code of his draughts program 
"Scan 3.0"
And last not least, there exist "ggp-zero-brakthrough", a neural net 
similar to the code of LeelaZero
But if I had to bet, I would bet on SF

**Comment by ianfab** [comment]
@mtaktikos Thanks a lot, that is very helpful, and it is nice to hear that it already performs well without many game-specific search or evaluation adjustments. If you have run some matches between the engines, feel free to add Elo estimates to the [wiki](https://github.com/ianfab/Fairy-Stockfish/wiki/Playing-strength) (even if the estimates are only derived from a handful of games).
