### ISSUE TITLE
JANGGI End Calculation

### ISSUE THREAD

**Issue by kimqwer2** [ianfab/Fairy-Stockfish#124]
9/c1P6/3k5/7c1/9/9/9/9/4K4/4C1B2 w - - 0 1
https://www.pychess.org/nPnwThfN
We can't finish the game, but the engine is finished.
＃7 -> ＃6 -> ＃4 -> ＃3 ->＃3 ...ㅁ
＃3 = I know it will be over after 3 moves.
They say it's over after three moves, but it's not over.
Is this calculation due to the score system?
(# + number) ->   Due to this, 7, 6, 4, and 3 issues were mentioned. Sorry.

**Comment by ianfab** [comment]
This is due to the way repetitions are currently handled. Since red keeps "repeating" by passing, it considers blue to be winning by red's violation of the repetition rule. This of course does not make much sense here, but current repetition handling is a known limitation, so I am closing this.
