### ISSUE TITLE
Shogi notation

### ISSUE THREAD

**Issue by CouchTomato87** [ianfab/Fairy-Stockfish#125]
I know there was talk about allowing different notations, but if that's not in the pipeline anytime soon, can we actually switch to Hosking notation (number number)? After being involved in Shogi communities for a while, really no one at all uses the Hodges notation (number letter). I also struggle with it because I can't count letters easily.

**Comment by CouchTomato87** [comment]
Oops, I meant to put this in Pychess. But before I do, lemme know if there's a more appropriate place to put the request

**Comment by ianfab** [comment]
Since both notations are supported in Fairy-Stockfish, no work is required here, so I'd suggest to discuss it in the pychess repo.
