### ISSUE TITLE
Custom variants/piece-types

### ISSUE THREAD

**Issue by grandmastermac** [ianfab/Fairy-Stockfish#126]
Hi there,

I want to do some testing on a variant I am creating. 

I had a look at the piece types available in variants.ini and I can't seem to find a definition for a Knight+Camel compound or the Knight+Wazir compound.

If there aren't definitions for a piece in variants.ini how do I go about creating them?

My objective is to do some white/black balance testing to determine my variant doesn't give white too much of an edge.

**Comment by ianfab** [comment]
Creating new piece types via configuration unfortunately is not possible yet, see #58. If you want to add a new piece type to the code, you can check a previous addition of a new piece type to see which places need to be changed, e.g., https://github.com/ianfab/Fairy-Stockfish/commit/5f428f62dae586f7308365a7b7ff6b4e069dcb1f. From there it should be straightforward to add the two compound leapers you mentioned.

**Comment by ianfab** [comment]
For reference, configurable piece types are supported since version 13.1, see https://github.com/ianfab/Fairy-Stockfish/releases.
