### ISSUE TITLE
How to add chinese chess (xiangqi) variant?

### ISSUE THREAD

**Issue by huynq55** [ianfab/Fairy-Stockfish#127]
How to add chinese chess (xiangqi) variant? Do I need to delete other variants and just keep one variant or I can keep all variants? If I can keep all variants, how to let the engine use the variant that I want?
One more question. I want to chat with you ianfab. Can you please give me your email or facebook?

**Comment by huynq55** [comment]
I ask this question because I thought that you have pre-defined xiangqi variant

**Comment by gaintpd** [comment]
if you want to use fairy-stockfish as an Xiangqi engine, you can use the ucci protocol in the xiangqi GUI such as sharkchess, and Binghe WuSi, of course, I have implement the support for xiangqi and minixiangqi and manchu in cutechess, It works very well on ubuntu18.04 but the minixiangqi always cause the crash in windows. I have the plan to fire a pull-request to the official cutechess repo this year.

**Comment by huynq55** [comment]
But do I need to change variants.ini?

**Comment by gaintpd** [comment]
No, you don't need to, If you want to use fairy-stockfish as an xiangqi engine.

**Comment by ianfab** [comment]
Which GUI are you using and which version of Fairy-Stockfish did you download? Xiangqi should work fine in any UCCI compatible Xiangqi GUI and also in XBoard/Winboard. If the GUI complains that Xiangqi is not supported, please make sure to download the "largeboard" version of the release which includes variants with boards larger than 8x8.

**Comment by huynq55** [comment]
Ok I have successfully installed the engine with my GUI

**Comment by ianfab** [comment]
Sounds good, so I guess we can close this issue. If you have further questions, feel free to re-open it.
