### ISSUE TITLE
I'm really impressive with your project

### ISSUE THREAD

**Issue by huynq55** [ianfab/Fairy-Stockfish#129]
I'm really impressive with your project. I want to code a chess engine like what you do, but it's hard for me. Are you professional programmer? How can you understand stockfish enough to start making changes? Please help me, I really want to understand your source code, but I don't know where to start. It's really good if you can make a tutorial, I think it will help a lot of people.

**Comment by huynq55** [comment]
How can I become a professional programmer like you?

**Comment by ianfab** [comment]
Thanks, I am glad that you like this project. I am a software developer by profession, but in a very different domain, Fairy-Stockfish is just a hobby project for me. I have been contributing to Stockfish forks as well as official Stockfish over the last 4 years, that is where my experience with the code base is coming from. I wrote an introduction to the Fairy-Stockfish codebase in the wiki at https://github.com/ianfab/Fairy-Stockfish/wiki/Understanding-the-code, so you can start from there, although it more or less assumes some basic familiarity with the official Stockfish code base.
