### ISSUE TITLE
Janggi repetition adjudication

### ISSUE THREAD

**Issue by kimqwer2** [ianfab/Fairy-Stockfish#131]
![bbbb](https://user-images.githubusercontent.com/63884391/82469096-8e6b7880-9afe-11ea-9ef5-e19f61d01428.png)
I often use JanggiCasual rule.
Red, however, can definitely win, but if Blue uses a "pass", he makes repeated moves.
The picture above is such a situation.
Even using 5 "passes" is far from a clear win.
The last picture is the ideal direction of victory I think.
Janggicasual rule knows that there is no object score counting according to "pass".

Is this because of the way it handles iterations?

5k3/3aa4/9/6p1p/9/3n5/4p4/5KC2/6p2/9 w--0 1

**Comment by ianfab** [comment]
This is one of the side effects of the current repetition handling. When blue is forced to keep passing, then red can arrange in a way that the repetition kicks in exactly at a point where it is considered a loss (illegal) for blue, therefore Fairy-SF thinks red can win in this way. I am planning to change this already, see https://github.com/ianfab/Fairy-Stockfish/tree/janggi_adjudication (and the corresponding question I asked on discord), to adjudicate repetitions as draws or via material counting (depending on the variant).

**Comment by kimqwer2** [comment]
casual rule, traditional rule -> Doesn't it take into account how to continue playing the game even if it is "pass" without being treated as a draw or object counting?
I think it is far from repetitive to keep using "pass".
I think that draw or object counting or defeat for repetition such as ABAB should exist   => Casual rule, traditional rule included
(position A -> position B -> position A -> position B).
However, even if you use the pass in "Casual Rules, Traditional Rules", it is recommended that the game continue.
(Without draw or object counting)
