### ISSUE TITLE
version Fairy-Stockfish 11.1 not work

### ISSUE THREAD

**Issue by dapao9999** [ianfab/Fairy-Stockfish#133]
not work when use Fairy-Stockfish 11.1 as an xiangqi engine with GUI,but Fairy-Stockfish 11 works well.
error:

"<fairy-stockfish-largeboard_x86-64-modern(3): Unknown command: newgame
<fairy-stockfish-largeboard_x86-64-modern(3): Unknown command: fen rnbakabnr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RNBAKABNR w - - 0 1“

**Comment by ianfab** [comment]
Can you please give more details, e.g., protocol the GUI uses (I assume UCCI) and logs? The errors above look valid, as "newgame" and "fen" are not valid commans in any of the protocols. They perhaps are supposed to be "uccinewgame" and "position fen ...".

**Comment by dapao9999** [comment]
Hi,i am using ucci protocol,i have tried several GUI,this is the log:
 <fairy-stockfish-largeboard_x86-64-modern(0): Fairy-Stockfish 11.1 LB 64 POPCNT by Fabian Fichter
<fairy-stockfish-largeboard_x86-64-modern(0): id name Fairy-Stockfish 11.1 LB 64 POPCNT
<fairy-stockfish-largeboard_x86-64-modern(0): id author Fabian Fichter
<fairy-stockfish-largeboard_x86-64-modern(0): option Protocol type combo default ucci var uci var usi var ucci var xboard
<fairy-stockfish-largeboard_x86-64-modern(0): option Debug_Log_File type string default 
<fairy-stockfish-largeboard_x86-64-modern(0): option Contempt type spin default 24 min -100 max 100
<fairy-stockfish-largeboard_x86-64-modern(0): option Analysis_Contempt type combo default Both var Both var Off var White var Black
<fairy-stockfish-largeboard_x86-64-modern(0): option Threads type spin default 1 min 1 max 512
<fairy-stockfish-largeboard_x86-64-modern(0): option Hash type spin default 16 min 1 max 131072
<fairy-stockfish-largeboard_x86-64-modern(0): option Clear_Hash type button
<fairy-stockfish-largeboard_x86-64-modern(0): option Ponder type check default false
<fairy-stockfish-largeboard_x86-64-modern(0): option MultiPV type spin default 1 min 1 max 500
<fairy-stockfish-largeboard_x86-64-modern(0): option Skill_Level type spin default 20 min -20 max 20
<fairy-stockfish-largeboard_x86-64-modern(0): option Move_Overhead type spin default 30 min 0 max 5000
<fairy-stockfish-largeboard_x86-64-modern(0): option Minimum_Thinking_Time type spin default 20 min 0 max 5000
<fairy-stockfish-largeboard_x86-64-modern(0): option Slow_Mover type spin default 84 min 10 max 1000
<fairy-stockfish-largeboard_x86-64-modern(0): option nodestime type spin default 0 min 0 max 10000
<fairy-stockfish-largeboard_x86-64-modern(0): option UCI_Chess960 type check default false
<fairy-stockfish-largeboard_x86-64-modern(0): option UCI_Variant type combo default xiangqi var 3check var 5check var ai-wok var almost var amazon var antichess var asean var breakthrough var bughouse var cambodian var capablanca var capahouse var caparandom var centaur var chancellor var chess var chessgi var chigorin var clobber var clobber10 var codrus var courier var crazyhouse var dobutsu var embassy var euroshogi var extinction var fairy var fischerandom var gardner var giveaway var gorogoro var gothic var grand var hoppelpoppel var horde var janggi var janggicasual var janggimodern var janggitraditional var janus var jesonmor var judkins var karouk var kinglet var kingofthehill var knightmate var koedem var kyotoshogi var loop var losalamos var losers var makpong var makruk var manchu var micro var mini var minishogi var minixiangqi var modern var newzealand var nocastle var normal var placement var pocketknight var racingkings var seirawan var shako var shatar var shatranj var shogi var shouse var sittuyin var suicide var supply var threekings var xiangqi
<fairy-stockfish-largeboard_x86-64-modern(0): option UCI_AnalyseMode type check default false
<fairy-stockfish-largeboard_x86-64-modern(0): option UCI_LimitStrength type check default false
<fairy-stockfish-largeboard_x86-64-modern(0): option UCI_Elo type spin default 1350 min 1350 max 2850
<fairy-stockfish-largeboard_x86-64-modern(0): option SyzygyPath type string default <empty>
<fairy-stockfish-largeboard_x86-64-modern(0): option SyzygyProbeDepth type spin default 1 min 1 max 100
<fairy-stockfish-largeboard_x86-64-modern(0): option Syzygy50MoveRule type check default true
<fairy-stockfish-largeboard_x86-64-modern(0): option SyzygyProbeLimit type spin default 7 min 0 max 7
<fairy-stockfish-largeboard_x86-64-modern(0): option TsumeMode type check default false
<fairy-stockfish-largeboard_x86-64-modern(0): option VariantPath type string default <empty>
<fairy-stockfish-largeboard_x86-64-modern(0): ucciok
>fairy-stockfish-largeboard_x86-64-modern(0): setoption Analysis_Contempt Both
>fairy-stockfish-largeboard_x86-64-modern(0): setoption Contempt 24
>fairy-stockfish-largeboard_x86-64-modern(0): setoption Debug_Log_File
>fairy-stockfish-largeboard_x86-64-modern(0): setoption Hash 16
>fairy-stockfish-largeboard_x86-64-modern(0): setoption Minimum_Thinking_Time 20
>fairy-stockfish-largeboard_x86-64-modern(0): setoption Move_Overhead 30
>fairy-stockfish-largeboard_x86-64-modern(0): setoption MultiPV 1
>fairy-stockfish-largeboard_x86-64-modern(0): setoption Protocol ucci
>fairy-stockfish-largeboard_x86-64-modern(0): setoption Skill_Level 20
>fairy-stockfish-largeboard_x86-64-modern(0): setoption Slow_Mover 84
>fairy-stockfish-largeboard_x86-64-modern(0): setoption Syzygy50MoveRule true
>fairy-stockfish-largeboard_x86-64-modern(0): setoption SyzygyPath <empty>
>fairy-stockfish-largeboard_x86-64-modern(0): setoption SyzygyProbeDepth 1
>fairy-stockfish-largeboard_x86-64-modern(0): setoption SyzygyProbeLimit 7
>fairy-stockfish-largeboard_x86-64-modern(0): setoption Threads 1
>fairy-stockfish-largeboard_x86-64-modern(0): setoption TsumeMode false
>fairy-stockfish-largeboard_x86-64-modern(0): setoption UCI_AnalyseMode false
>fairy-stockfish-largeboard_x86-64-modern(0): setoption UCI_Chess960 false
>fairy-stockfish-largeboard_x86-64-modern(0): setoption UCI_Elo 1350
>fairy-stockfish-largeboard_x86-64-modern(0): setoption UCI_LimitStrength false
>fairy-stockfish-largeboard_x86-64-modern(0): setoption UCI_Variant xiangqi
>fairy-stockfish-largeboard_x86-64-modern(0): setoption VariantPath <empty>
>fairy-stockfish-largeboard_x86-64-modern(0): setoption nodestime 0
>fairy-stockfish-largeboard_x86-64-modern(0): isready
<fairy-stockfish-largeboard_x86-64-modern(0): readyok
>fairy-stockfish-largeboard_x86-64-modern(0): newgame
>fairy-stockfish-largeboard_x86-64-modern(0): setoption ponder false
>fairy-stockfish-largeboard_x86-64-modern(0): position fen rnbakabnr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RNBAKABNR w - - 0 1
>fairy-stockfish-largeboard_x86-64-modern(0): fen rnbakabnr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RNBAKABNR w - - 0 1
<fairy-stockfish-largeboard_x86-64-modern(0): Unknown command: newgame
<fairy-stockfish-largeboard_x86-64-modern(0): Unknown command: fen rnbakabnr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RNBAKABNR w - - 0 1

**Comment by ianfab** [comment]
I am not sure how this is supposed to work, since the GUI is apparently not protocol-compliant. The engine behaves as expected and according to the UCCI protocol. Fairy-Stockfish 11 should behave in the same way and also report the "Unknown command" errors.

**Comment by gbtami** [comment]
UCCI needs `uccinewgame` instead of `newgame` (similar to USI `usinewgame`)

**Comment by dapao9999** [comment]
sorry,it is my fault
