### ISSUE TITLE
Consider material counting result in evaluation

### ISSUE THREAD

**Issue by kimqwer2** [ianfab/Fairy-Stockfish#136]
This is the score of the objects in janggi.
1pawn =2 points, 1Wazir = 3 points, 1Rook = 13 points, Elephant = 3 points
1horse = 5 points, 1cannon = 7 points
SF sees the horse as 800, so as the game progresses, it becomes 0 cannon and 2 horse.
If the game is judged by a score rather than a complete win, a person with 2 cannons will be better than a person with 2 horses, but 2 cannon is weaker than 2 horses in the game.
So I think "1horse, 1cannon" also has a good shape
If one cannon dies, I think it would be better to increase the value of the other one.
or, what about the new final valuation besides mg and eg?
This is only an idea, so it may actually be weaker.

**Comment by ianfab** [comment]
This should be solved by https://github.com/ianfab/Fairy-Stockfish/commit/c97fd9d74f32d850893eeec5bf3c3955adbe4df3.
