### ISSUE TITLE
white makes an illegal move in janggi

### ISSUE THREAD

**Issue by gaintpd** [ianfab/Fairy-Stockfish#137]
Hi ianfab, I have implemented the janggi support for cutechess, basically, I only implement the rules shown in the wiki page in pychess-variant website. When I test my implementation using the Fairy-Stockfish as an Janggi Engine. both White and Black( Blue or Green regarded as the White side, and the Red  as the Black side). the move window in cutechess  print  that  White makes an illegal move:d1d2, here is the complete pgn contents:

[Event "?"]
[Site "?"]
[Date "2020.05.31"]
[Round "?"]
[White "fairy-sf-lb11_1"]
[Black "fairy-sf-lb11_1"]
[Result "0-1"]
[GameDuration "00:01:45"]
[GameEndTime "2020-05-31T20:31:29.281 CST"]
[GameStartTime "2020-05-31T20:29:43.628 CST"]
[PlyCount "10"]
[Termination "illegal move"]
[TimeControl "40/300"]
[Variant "janggi"]

1. b4 {+0.36/24 31s} h7 {+0.26/21 28s} 2. Ng3 {+0.35/23 0.051s}
Nc8 {+0.25/18 6.8s} 3. Ke1 {+0.34/20 1.5s} Ng8 {+0.32/18 7.8s}
4. Nc3 {+0.34/18 16s} Ke10 {+0.17/18 0.023s} 5. Afe2 {+0.32/15 6.5s}
Ade9 {+0.35/16 3.3s, White makes an illegal move: d1d2} 0-1

and the contents printed in Application Output Tab in Qt is as below:

20:29:34: Starting /media/dyn/Data/cutechess/cutechess/projects/gui/cutechess
Illegal PV move e9e9 from fairy-sf-lb11_1 (0)
PV: Nc3 e9e9
Illegal PV move d1d2 from fairy-sf-lb11_1 (0)
PV: Ng3 b7 h4 Ng8 Nc3 Ke10 Ke1 Nc8 Afe2 Afe9 g5 c6 Ch5 f7 d1d2
Illegal PV move d10d9 from fairy-sf-lb11_1 (0)
PV: b4 h7 Nc3 Ng8 Ng3 Nc8 g5 Ke10 Ke1 c6 Ade2 Afe9 Ra2 d10d9
Illegal PV move d10d9 from fairy-sf-lb11_1 (0)
PV: b4 h7 Ng3 Nc8 g5 Ng8 Nc3 Ke10 Ke1 Afe9 Ade2 c6 Ra2 d10d9
Illegal PV move d10d9 from fairy-sf-lb11_1 (0)
PV: Ng3 Nc8 Nc3 Ng8 Ke1 Ke10 Ade2 Afe9 g5 Cbe8 Chf3 d10d9
Illegal PV move d10d9 from fairy-sf-lb11_1 (0)
PV: Ng3 Nc8 Nc3 Ke10 Ke1 Ng8 Ade2 Afe9 g5 Cbe8 Chf3 d10d9
Illegal PV move f1f2 from fairy-sf-lb11_1 (0)
PV: Ng3 Nc8 Nc3 Ke10 Ke1 Ng8 Ade2 Afe9 g5 Cbe8 f1f2
Illegal PV move d10d9 from fairy-sf-lb11_1 (0)
PV: Ng3 Nc8 Nc3 Ng8 Ke1 Ke10 Ade2 Afe9 g5 Cbe8 Chf3 d10d9
Illegal PV move f1f2 from fairy-sf-lb11_1 (0)
PV: Ng3 Nc8 Ke1 Ke10 Nc3 Ng8 Ade2 Afe9 g5 Cbe8 f1f2
Illegal PV move d10d9 from fairy-sf-lb11_1 (0)
PV: Ng3 Nc8 Ke1 Ke10 Nc3 Ng8 Ade2 Afe9 Chf3 d10d9
Illegal PV move d10d9 from fairy-sf-lb11_1 (0)
PV: Ng3 Nc8 Ke1 Ke10 Nc3 Ng8 Ade2 Afe9 Chf3 d10d9
Illegal PV move d10d9 from fairy-sf-lb11_1 (0)
PV: Ng3 Nc8 Ke1 Ng8 Nc3 Ke10 Ade2 Afe9 Chf3 Cbe8 g5 d10d9
Illegal PV move d10d9 from fairy-sf-lb11_1 (0)
PV: Ng3 Nc8 Nc3 Ng8 Ke1 Ke10 Ade2 Afe9 g5 Cbe8 Chf3 d10d9
Illegal PV move f1f2 from fairy-sf-lb11_1 (0)
PV: Ng3 Nc8 Nc3 Ng8 Ke1 Ke10 Chf3 Afe9 Ade2 Cbe8 f1f2
Illegal PV move i9f9 from fairy-sf-lb11_1 (1)
PV: Nc8 Nc3 h7 Ng3 Ng8 Ke1 Ke10 g5 Ade9 Ra5 Ri9 Afe2 i9f9
Illegal PV move d10d9 from fairy-sf-lb11_1 (0)
PV: Ng3 Nc8 Nc3 Ng8 Ke1 Ke10 g5 Afe9 Ade2 Cbe8 Chf3 d10d9
Illegal PV move d10d9 from fairy-sf-lb11_1 (0)
PV: Ng3 Nc8 Nc3 Ng8 Ke1 Ke10 g5 Afe9 Ade2 Cbe8 Chf3 d10d9
Illegal PV move f1f2 from fairy-sf-lb11_1 (0)
PV: Ke1 Ng8 Ade2 Ke10 f1f2
Illegal PV move f1f2 from fairy-sf-lb11_1 (0)
PV: Ke1 Ng8 Nc3 Ke10 Ade2 Afe9 f1f2
Illegal PV move f1f2 from fairy-sf-lb11_1 (0)
PV: Ke1 Ng8 Ade2 Ke10 Nc3 Afe9 f1f2
Illegal PV move f1f2 from fairy-sf-lb11_1 (0)
PV: Ke1 Ng8 Ade2 Cbe8 Nc3 Ke10 g5 Afe9 f1f2
Illegal PV move f1f2 from fairy-sf-lb11_1 (0)
PV: Ke1 Ng8 Ade2 Cbe8 Nc3 Ke10 g5 Afe9 f1f2
Illegal PV move a2d2 from fairy-sf-lb11_1 (1)
PV: Nc8 Ke1 Ce8 Nc3 c6 Ra2 Ke10 a2d2
Illegal PV move f1f2 from fairy-sf-lb11_1 (0)
PV: Ke1 Ce8 Nc3 Ke10 Chf3 Ng8 g5 Afe9 f1f2
Illegal PV move d10d9 from fairy-sf-lb11_1 (0)
PV: g5 Ng8 Nc3 Ke10 Ke1 Cbe8 Ade2 Afe9 Chf3 d10d9
Illegal PV move d1d2 from fairy-sf-lb11_1 (1)
PV: Ng8 Ke1 Nc8 Nc3 Ke10 c5 Cbe8 Afe2 g6 Che3 Ch6 Cb5 b7 g5 f6 d1d2
Illegal PV move i9f9 from fairy-sf-lb11_1 (1)
PV: Ke10 Nc3 Ng8 c5 Ade9 g5 Cbe8 Cb5 d7 Cd3 Ri9 h5 Ca8 Rb1 i9f9
Illegal PV move a9d9 from fairy-sf-lb11_1 (1)
PV: Ke10 Nc3 Ng8 c5 Ade9 Che3 g6 Ade2 Cbe8 Cb5 f6 Ri2 Ra9 h4 Rxi2 Nxi2 a9d9
Illegal PV move f1f2 from fairy-sf-lb11_1 (0)
PV: Nc3 Ke10 Ade2 Ng8 f1f2
Illegal PV move f1f2 from fairy-sf-lb11_1 (0)
PV: Nc3 Ke10 Ade2 Ng8 f1f2
Illegal PV move d1d2 from fairy-sf-lb11_1 (1)
PV: Ng8 Nc3 Ke10 g5 Ade9 Afe2 d7 Cb5 Cbe8 Ri2 Ch6 d1d2
Illegal PV move f1f2 from fairy-sf-lb11_1 (0)
PV: Nc3 Ke10 Ade2 Ng8 f1f2
Illegal PV move d10d9 from fairy-sf-lb11_1 (0)
PV: Nc3 Ng8 Ade2 Ke10 Cbe3 d10d9
Illegal PV move d10d9 from fairy-sf-lb11_1 (0)
PV: Ade2 Cbe8 Ra5 d10d9
Illegal PV move d10d9 from fairy-sf-lb11_1 (0)
PV: Ade2 Cbe8 Ra5 d10d9
Illegal PV move a2d2 from fairy-sf-lb11_1 (0)
PV: Ade2 Cbe8 Nc3 Ke10 Che3 Ade9 g5 c6 Ra2 Ra9 Cb5 f7 a2d2
Illegal PV move a2d2 from fairy-sf-lb11_1 (0)
PV: Ade2 Cbe8 Nc3 Ke10 Che3 Ade9 g5 c6 Ra2 Ra9 Cb5 f7 a2d2
Illegal PV move i2f2 from fairy-sf-lb11_1 (1)
PV: c6 Ade2 Ke10 g5 Cbe8 Cb5 Ade9 Ri2 Ra9 Ci5 Ch6 i2f2
Illegal PV move i2f2 from fairy-sf-lb11_1 (1)
PV: c6 Ade2 Ke10 g5 Cbe8 Cb5 Ade9 Ri2 Ra9 Ci5 Ch6 i2f2
Illegal PV move i2f2 from fairy-sf-lb11_1 (0)
PV: Nc3 Cbe8 c5 Ke10 Cb5 g6 Ade2 Afe9 Ri2 Ch6 Ce3 c6 d5 Ra9 i2f2
Illegal PV move i2d2 from fairy-sf-lb11_1 (0)
PV: Nc3 Ke10 c5 Cbe8 Cb5 g6 Ri2 Ch6 h4 c6 cxc6 Cxc6 i2d2
Illegal PV move f1f2 from fairy-sf-lb11_1 (0)
PV: Nc3 Ke10 Ade2 Afe9 f1f2
Illegal PV move a9d9 from fairy-sf-lb11_1 (0)
PV: Nc3 Ke10 c5 Cbe8 Ade2 g6 Cb5 Ade9 Ri2 Ra9 Ce3 a9d9
Illegal PV move d1d2 from fairy-sf-lb11_1 (1)
PV: c6 g5 Ke10 Afe2 Ade9 Che3 Ra9 d1d2
Illegal PV move i2f2 from fairy-sf-lb11_1 (0)
PV: Nc3 Ke10 c5 Cbe8 Che3 Ade9 Cb5 g6 Ri2 Ch6 g5 c6 d5 f6 h5 Ch9 i2f2
Illegal PV move d10d9 from fairy-sf-lb11_1 (0)
PV: Che3 Afe9 Afe2 d10d9
Illegal PV move d1d2 from fairy-sf-lb11_1 (1)
PV: g6 Afe2 Ade9 Ri2 d7 d1d2
Illegal PV move d1d2 from fairy-sf-lb11_1 (1)
PV: g6 Afe2 Ade9 Ri2 d7 d1d2
Illegal PV move i2f2 from fairy-sf-lb11_1 (1)
PV: g6 Ade2 Afe9 Ri2 Cbe8 Cb5 b7 Ce3 b6 Ci5 Ch6 i2f2
Illegal PV move d1d2 from fairy-sf-lb11_1 (0)
PV: Afe2 Ade9 Che3 Cbe8 g5 c6 d1d2
Illegal PV move f1f2 from fairy-sf-lb11_1 (0)
PV:  f1f2
Illegal PV move i2f2 from fairy-sf-lb11_1 (1)
PV: Afe9 Afe2 g6 Che3 Ch6 Ri2 Ce8 i2f2
Illegal PV move f1f2 from fairy-sf-lb11_1 (0)
PV:  f1f2
Illegal PV move f1f2 from fairy-sf-lb11_1 (1)
PV: Ade9 Ade2 g6 f1f2
Illegal PV move f1f2 from fairy-sf-lb11_1 (0)
PV:  f1f2
Illegal PV move f1f2 from fairy-sf-lb11_1 (0)
PV:  f1f2
Illegal PV move f1f2 from fairy-sf-lb11_1 (1)
PV: Ade9 Ade2 g6 f1f2
Illegal PV move f1f2 from fairy-sf-lb11_1 (1)
PV: Ade9 Ade2 g6 f1f2
Illegal PV move f1f2 from fairy-sf-lb11_1 (0)
PV:  f1f2
Illegal PV move f1f2 from fairy-sf-lb11_1 (0)
PV:  f1f2
Illegal PV move d1d2 from fairy-sf-lb11_1 (0)
PV:  d1d2
Illegal PV move i2f2 from fairy-sf-lb11_1 (1)
PV: Ade9 c5 g6 Ri2 d7 Cb5 Cbe8 Ce3 Ch6 i2f2
Illegal PV move d1d2 from fairy-sf-lb11_1 (1)
PV: Ade9 c5 Cbe8 d1d2
Illegal PV move d1d2 from fairy-sf-lb11_1 (0)
PV:  d1d2
Illegal PV move d1d2 from fairy-sf-lb11_1 (0)
PV:  d1d2
Illegal PV move f10f9 from fairy-sf-lb11_1 (1)
PV: Ade9 g5 f10f9
Illegal PV move d1d2 from fairy-sf-lb11_1 (0)
PV: Chf3 g6 d1d2
Illegal PV move d1d2 from fairy-sf-lb11_1 (1)
PV: Ade9 Che3 g6 d1d2
Illegal PV move f10f9 from fairy-sf-lb11_1 (1)
PV: Ade9 g5 Cbe8 Cb5 Ch6 Ra2 c6 Ri2 f10f9
Illegal PV move a9d9 from fairy-sf-lb11_1 (1)
PV: Ade9 g5 Cbe8 Cb5 c6 d4 Ra9 Ce3 Ch6 Cb2 d6 Rb1 Cc6 b5 a9d9
Illegal PV move f10f9 from fairy-sf-lb11_1 (1)
PV: Cbe8 Ri2 f10f9
Illegal PV move f10f9 from fairy-sf-lb11_1 (1)
PV: Cbe8 Ri2 f10f9
Illegal PV move f10f9 from fairy-sf-lb11_1 (1)
PV: Cbe8 Ri2 f10f9
Illegal PV move d1d2 from fairy-sf-lb11_1 (1)
PV: c6 Che3 Ra9 d1d2
Illegal PV move f5f2 from fairy-sf-lb11_1 (1)
PV: c6 Che3 Ra9 Ra5 a6 Rf5 b6 Ci3 Rh10 f5f2
Illegal PV move d1d2 from fairy-sf-lb11_1 (1)
PV: Cbe8 Che3 c6 d1d2
Illegal PV move a9d9 from fairy-sf-lb11_1 (1)
PV: Cbe8 Cb5 c6 d4 Ra9 Ce3 Ch6 Ci5 d6 d5 a9d9
Illegal PV move d1d2 from fairy-sf-lb11_1 (0)
PV: Chf3 g6 d1d2
Illegal PV move d1d2 from fairy-sf-lb11_1 (0)
PV: Chf3 g6 d1d2
Illegal PV move d1d2 from fairy-sf-lb11_1 (1)
PV: Cbe8 Cb5 c6 Ce3 Ra9 Ci5 Ri6 d1d2
Illegal PV move d1d2 from fairy-sf-lb11_1 (0)
PV:  d1d2
Illegal PV move i2f2 from fairy-sf-lb11_1 (1)
PV: Cbe8 Cb5 c6 Ce3 d6 Ci5 Ch6 Ri2 Ri9 i2f2
Illegal PV move d1d2 from fairy-sf-lb11_1 (0)
PV:  d1d2
Illegal PV move a2d2 from fairy-sf-lb11_1 (1)
PV: Cbe8 Cb5 c6 Ce3 d6 Ra2 Ra9 c5 Ch6 i5 Ri9 Ri4 e6 a2d2
Illegal PV move d1d2 from fairy-sf-lb11_1 (0)
PV:  d1d2
Illegal PV move d1d2 from fairy-sf-lb11_1 (0)
PV:  d1d2

and the fen string is as follows:
r1b1kab1r/4a4/1cn3nc1/p1p1p1pp1/9/9/1PP1P1P1P/1CN3NC1/4A4/R1BAK1B1R w - - 10 6

It seems that the move generation for the advisor is the source of problem.  I don't know which rule I have missed in my current implementation. I need the help, and I will take a screenshot of the cutechess and the complete engine log as the attached files

[EngineDebuglog.log](https://github.com/ianfab/Fairy-Stockfish/files/4707673/EngineDebuglog.log)
![Screenshot from 2020-05-31 20-57-08](https://user-images.githubusercontent.com/17960782/83352982-faad6e00-a381-11ea-8311-afcc9f9bd82e.png)

**Comment by gaintpd** [comment]
![Screenshot from 2020-05-31 20-57-08](https://user-images.githubusercontent.com/17960782/83353003-203a7780-a382-11ea-9ddb-12c2aa3995bd.png)

**Comment by ianfab** [comment]
Thanks, that is great news that you are working on Janggi support for cutechess. The advisor in Janggi can not only move like the advisor in Xiangqi, but also orthogonally, i.e., along all lines (whether diagonal or orthogonal) in the palace, see https://www.pychess.org/variant/janggi#advisor. The same applies to the king/general.

Since I assume you are familiar with the Xiangqi rules, I can maybe briefly summarize the main move generation differences for clarity:
* The Elephant movement differs: https://www.pychess.org/variant/janggi#elephant
* Cannons move the same way they capture, i.e., they need to jump to be able to move.
* Cannons can neither capture other cannons nor jump over them
* Soldiers/pawns can also move sideways from the beginning
* Special moves inside the palace:
  * Generals and advisors can move along all orthogonal and diagonal lines of the palace
  * Pawns can also move one square along the diagonal lines
  * Rooks can move one or two squares along the diagonal lines
  * Cannons can move along the diagonal lines if they jump over a (non-cannon) piece

**Comment by gaintpd** [comment]
Hello ianfab, I can't thank you enough for your prompt and accurate info. Frankly speaking, I regard the advisor and King/general in Janggi follow the same rules in Xiangqi. and obviously, this is an neglected mistake that makes carelessly, I only noticed the difference of Bishop/Elephant, Cannon and Pawn and the special rules in the palace(fortress, castle) for Rook/Chariots, Cannon and Pawn.
obviously, the curent implementation for Rook in the palace is wrong based on your explanation, I need to rewrite the rook rule implementation in palace. 
      
Is the bikjang(facing kings)  similar to Xiangqi, I borrow the code I implemented in Xiangqi directly. I did not implement the material counting feature, this feature is relying on the engine implementation.

In general, there will not be huge addition needed for my current implementation. The urgent task is to modify the move generation for Advisor and General and rewrite the move generation for Rook in palace. There is no other problems found in Janggi.

At last, I think I need to Thank you again for your timely and accurate info, thank you very very much. This is a nice day.

**Comment by gaintpd** [comment]
It seems that I misunderstand the rule of bikjang, I need to make it clear and implement this rule additionally.

**Comment by ianfab** [comment]
You are welcome. If you want to get more familiar with the Janggi rules, feel free to to play against the random mover bot on https://www.pychess.org/ to see which moves are legal, especially in the palace. You can also use `perft` in Fairy-Stockfish and check against your results in cutechess, e.g., I also have some perft tests in https://github.com/ianfab/Fairy-Stockfish/blob/0abbb717d3a925f5f7e976d408b9496dfbf4d77f/tests/perft.sh#L79-L81.

**Comment by gaintpd** [comment]
Thank you very much, The move generation for Advisor and King is revised and it works good right now. Other issues need to be settled the other day. Thank you.

**Comment by ianfab** [comment]
If you have any more questions, feel free to ask and re-open this issue, for now I am closing it. I guess what still might be missing are:
* Passing (king in place move)
* Bikjang
* Material counting

**Comment by gaintpd** [comment]
Hello ianfab, There is one illegal move persist in the current implementation. Here is the screenshot. Is this the so called rule of "passing".

![Screenshot from 2020-06-04 20-55-17](https://user-images.githubusercontent.com/17960782/83759863-c64df080-a6a6-11ea-8df5-b63f8e6cd419.png)

**Comment by ianfab** [comment]
Yes, at any time instead of making move a player can pass (like in Go/Weiqi) by making a move with the king where origin and destination square are the same (as far as I know over the board players just flip the king).

There are a few special cases with passing:
* If both players pass subsequently, this ends the game by material counting (https://www.pychess.org/variant/janggi#rules-gameplay)
* When a player passes in a bikjang situation, this also ends the game by material counting.
* Normally passing is not allowed when a player is in check. However, there is a corner case that when a player is in check (even checkmate) **and** there is a bikjang situation, then he is still allowed to pass, which again leads to material counting to decide the game result.

**Comment by gaintpd** [comment]
Hello ianfab, thank you very much for your excellent explanation. I have very little knowledge on the complete rule of Janggi, and just now, I have the right understanding of the English word 'passing' in the Janggi rules. just as your previous summary. There are three issues need to be settled. But I am still not fully understanding the rule of bikjang. Regarding to the rule of piece counting itself, it is not difficult to understand and implementation.

Thank you again. It is more and more close to finish the implementation of all the needed rules in Janggi.
