### ISSUE TITLE
Seirawan gating bug

### ISSUE THREAD

**Issue by kezsulap** [ianfab/Fairy-Stockfish#141]
A move is considered illegal if after moving piece away from a square puts one's king in check even if placing Hawk/Elephant on departure square would block this check.
In particular:
https://www.pychess.org/6f66ytoY
On move 5 white could play e.g. Nf3/H, but this is considered illegal
Final position is not checkmate since white can defend by Kd1/H

Moreover I believe this might me even worse in case of user-defined variant with Seirawan gating and cannons, since this would allow to make a move putting one's king in check by placing a piece from hand between the king and the cannon

**Comment by ianfab** [comment]
This behavior is intentional, since the king can not be in check during the move, but I unfortunately can not find a clear reference for this rule right now. Do you have a reference for your interpretation of the rule?

**Comment by kezsulap** [comment]
I found an explanation of this case on official website of this variant: http://www.seirawanchess.com/feedback.html (message from April 25, 2008)
They say your interpretation is right
Sorry for that

**Comment by ianfab** [comment]
No problem, and thanks for the clarification. For later reference I put the quote from your link here.

> When a piece is mov= ed from its original square, the move must be legal according to the laws of chess;= the placement of an undeveloped Hawk or Elephant as part of the initial move to block a check or replace a pinned piece is not sufficient to render legal an otherwise illegal move.
> 
>  
> 
> Here are two examples:
> 
>  
> 
> Black's last move is 1...Rh1+.  White may not play 2.Kd1/Ee1.  White could play 2.Kd2/Ee1 but may not expose his King to the Rook check for "half= a move."
> 
> White's Bishop on f1 is pinned to his King on e1 by a Black Rook on h1.&nbs= p; White may not play 1.Bb5+/Ef1, anticipating the capture of the Black h1-Roo= k on the next move, as he would have left his King exposed to a check.  An absolute pin is an absolute pin.
