### ISSUE TITLE
hash table problem

### ISSUE THREAD

**Issue by killmkll** [ianfab/Fairy-Stockfish#143]
Thank you always. Developer, please update the latest source frequently.
Is it good to have a high hash size regardless of game time? Should I reduce the hash size if the core is low? Please let me know a reasonable hash size of 16 GB with 8 cores 8 threads.

**Comment by ianfab** [comment]
It depends on the time control (as mentioned in https://github.com/ianfab/Fairy-Stockfish/wiki/FAQ#what-are-the-correct-settings-for-best-performance-on-my-machine). For long analysis 16 GB sounds very reasonable, but for games with short time control it might be a bit much, but in any case the impact of a too big hash table is rather limited, it only slightly decreases performance. If the time control is just a few minutes, <=1 GB should be sufficient.
