### ISSUE TITLE
inquiry about settings

### ISSUE THREAD

**Issue by killmkll** [ianfab/Fairy-Stockfish#144]
Is this setting correct?
Please let me know if you have anything to correct.
![설정](https://user-images.githubusercontent.com/64208810/83957892-8d7c6a00-a8a6-11ea-81a2-cd1cc37dad13.PNG)
![옵션](https://user-images.githubusercontent.com/64208810/83957893-8ead9700-a8a6-11ea-8895-d90e9c83486a.PNG)

**Comment by ianfab** [comment]
Yes.
