### ISSUE TITLE
Windboard ??

### ISSUE THREAD

**Issue by killmkll** [ianfab/Fairy-Stockfish#145]
Developer, thank you always.
Please update the latest source frequently.

Is it possible to achieve the best performance by using windboard AA? If there is anything better than Windboard AA, please let me know.

**Comment by ianfab** [comment]
Thank you for your interest in this project. However, if it works fine for you, please do not open so many issues for unnecessary questions as they just consume my time. Issues are mainly for bug reports and feature requests, and most questions should be answered by the documentation in the [wiki](https://github.com/ianfab/Fairy-Stockfish/wiki).
