### ISSUE TITLE
Missing SAN disambiguation for palace moves

### ISSUE THREAD

**Issue by ianfab** [ianfab/Fairy-Stockfish#152]
Since the SAN disambiguation only considers standard attacks and not palace moves, diagonal moves in the palace are sometimes missing SAN disambiguation, e.g.:
1b1aa2b1/5k3/3ncn3/1pp1pp3/5r2p/9/P1PPB1PPB/2N1CCN1c/9/R2AKAR2 w - - 19 17
Ae2 (Ade2/Afe2)

**Comment by gaintpd** [comment]
This issue seems the SAN disambiguation in the cutechess originated designed for chess and other chess variant works. Whereas the pawn disambiguation doesn't work.

**Comment by ianfab** [comment]
This issue is about the SAN generation in Fairy-Stockfish/pychess, so the only relation it has to cutechess might be that the broken SAN/PGN can not be imported into cutechess, but it needs to be fixed in Fairy-Stockfish.
