### ISSUE TITLE
Is fairy Stockfish capable of playing this?

### ISSUE THREAD

**Issue by Chess13234** [ianfab/Fairy-Stockfish#153]
https://github.com/Chess13234/ChessV2.0
Its a chess variant that adds some new roles for all pieces for more dynamic/tactical game, but retains most features of chess(same board, pieces, checkmates).

**Comment by ianfab** [comment]
The general rule changes are supported (castling, en passant, and n-move rule are configurable), but most of the additional rules for the individual pieces are not supported, and some of them are also not feasible to implement here, so overall the answer is no.
