### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by killmkll** [ianfab/Fairy-Stockfish#154]
Hi, Developer. I am a Korean long-term sponsor.

If you use Cpu Max,

Eight-core 16 threads. 

Is it correct to enter 16?

**Comment by ianfab** [comment]
Using hyperthreading might or might not improve performance, this is usually hardware-dependent, so it is best to test it yourself on your own hardware whether using 8 or 16 threads gives better results, but most likely using 16 threads will be slightly better.

However, as mentioned before please do not create a new issue for every little question here. This place is mainly to discuss bugs and feature requests.

You mentioned that you will donate. I did not receive anything yet, so did you send something already? (I am asking to make sure that there is no technical issue with it)

**Comment by killmkll** [comment]
I will be grateful to you on the 25th.

**Comment by killmkll** [comment]
I'll sponsor you on the 25th. Thank you.
