### ISSUE TITLE
Support for new variant - question

### ISSUE THREAD

**Issue by protonspring** [ianfab/Fairy-Stockfish#159]
I have a new variant and would like to know if this project can do it, or do I have to modify the source myself?
1) 10x10 board
2) 2 new pieces that move like queen, but only two steps.
3) New pieces can pass through own pieces.
4) Alternative checkmate rules involving the new pieces.

Is this something that can be done with Fairy-Stockfish?

**Comment by ianfab** [comment]
10x10 board size can be configured already, but a piece type that moves as you suggested currently is not built in, and since configuration of new piece types is not supported yet, it would require code changes, but they should be rather easy.

What do you mean by 3. and 4. exactly? Does the new piece leap to the second diagonal square (like an alfil)? And in which way is checkmate altered?

**Comment by protonspring** [comment]
3) The new pieces (according to the client), can pass through (or leap over) it's own pieces.  So, if it's on A1, and a pawn is on A2, the new piece can slide through the pawn and move to A3.

4) There are a few crazy checking rules.  If a new piece is a prince, the prince becomes the new king if the king is taken (yes. .the current king can be taken).  If that happens, the prince becomes the new king and normal mating rules now apply (nor more any backup royalty). I suspect this would require substantial changes.  Just checking if that is the case.

**Comment by ianfab** [comment]
So they can leap over pieces of their own color, but not over the opponent's pieces? Such a rule would be problematic for Fairy-Stockfish.

I am a bit confused by "if a new piece is a prince". Is there some promotion involved? I do not fully understand the mechanism of this rule yet, but most likely it will be problematic for Fairy-Stockfish as there can only be one type of royal piece.

**Comment by protonspring** [comment]
Ok.  Thank you, that answers my questions.  I will close this.  Much appreciation.
