### ISSUE TITLE
Evaluation of dead gating pieces in S-Chess

### ISSUE THREAD

**Issue by gbtami** [ianfab/Fairy-Stockfish#160]
In game https://www.pychess.org/JtHBCNCQ after back move 21... Exd1+ it evaluates 22. Rxd1 more than +2 at high depths because it thinks an elephant in the pocket is something useful. But after Rxd1 white can't gate his elephant anymore! Maybe fixing this can gain some Elo in S-chess :)

**Comment by ianfab** [comment]
Thanks. Yes, this is a known issue and was also partially discussed in #135, but unfortunately I so far failed to find a patch that gains Elo by fixing this, e.g., http://www.variantfishtest.org:6543/tests/view/5ecd66b56e23db36d55f2c49, although it would seem like this should be a no-brainer.

**Comment by ianfab** [comment]
@alwey Congrats, http://www.variantfishtest.org:6543/tests/view/5f5368236e23db221d9e90df passed at STC, feel free to submit for LTC.

**Comment by alwey** [comment]
Thank you. I'll submit soon. Currently I am investigating the midgame weight (200 in the tested version, 700 may be reasonable, too).

**Comment by ianfab** [comment]
@alwey Your test by accident is for standard chess. Tip: To submit a passed STC test for LTC quickly and reliably, you use the "reschedule" button on the finished test, then click on the "LTC" button, and then "submit".

**Comment by alwey** [comment]
Ah thanks, I have not seen that!

**Comment by alwey** [comment]
LTC passed. The patch uses (200,900) as piece score. Perhaps it would be better to scale the actual values of the pieces (this is more general):
```
if (pos.seirawan_gating() && !pos.piece_drops() && pos.count_in_hand(Us, ALL_PIECES) > popcount(pos.gates(Us)))
    score -= make_score(PieceValue[MG][pt] / 10, PieceValue[EG][pt] * 2 / 5)
           / pos.count_in_hand(Us, ALL_PIECES) * (pos.count_in_hand(Us, ALL_PIECES) - popcount(pos.gates(Us)));
```

**Comment by ianfab** [comment]
Nice. Yes, I agree that it would be nice to use a more general formula that considers the piece value. However, securing the Elo gain from a passed patch by merging it should be the priority, after that it can still be simplified, generalized, or improved, then of course testing against the passed patch, having the Elo gain already in the pocket.

**Comment by alwey** [comment]
OK, I just created a PR.

**Comment by ianfab** [comment]
Resolved by https://github.com/ianfab/Fairy-Stockfish/commit/90cc30aef0a66652af0b0a6ec9bd0fd8f3ceef6f.
