### ISSUE TITLE
Fishtest reports an "Illegal Move" termination for an Extinction game

### ISSUE THREAD

**Issue by notruck** [ianfab/Fairy-Stockfish#163]
During an idle glance at the terminal running fishtest, I saw a few illegal moves reported in Round 38 of "extinction_razor vs master" and thought it might be of interest. 

`Step 4/4. Deleting profile data ...
make ARCH=x86-64-bmi2 COMP=gcc profileclean
make[1]: Entering directory '/tmp/tmpcwTjrX/ianfab-Fairy-Stockfish-d212581/src'
make[1]: Leaving directory '/tmp/tmpcwTjrX/ianfab-Fairy-Stockfish-d212581/src'
Downloading extinction.epd ...
Verifying signature of stockfish_b82721dc23619fa3ecd98ab9660799aac1f369e9 ...
Verifying signature of stockfish_d2125816d5c179eb1fa0429f6e2134fb6995fa3c ...
CPU factor : 2.627335 - tc adjusted to 26.27+0.26
Running extinction_razor vs master
['/home/mvfishtest/fishtest-master/worker/testing/cutechess-cli', '-repeat', '-rounds', '200', '-tournament', 'gauntlet', '-pgnout', 'results.pgn', '-srand', '4010758818', '-resign', 'movecount=8', 'score=800', '-draw', 'movenumber=34', 'movecount=8', 'score=20', '-concurrency', '1', '-openings', u'file=extinction.epd', u'format=epd', 'order=random', 'plies=16', '-variant', u'extinction', '-engine', 'name=stockfish', u'cmd=stockfish_b82721dc23619fa3ecd98ab9660799aac1f369e9', u'option.Hash=4', u'option.Move Overhead=100', '-engine', 'name=base', u'cmd=stockfish_d2125816d5c179eb1fa0429f6e2134fb6995fa3c', u'option.Hash=4', u'option.Move Overhead=100', '-each', 'proto=uci', 'tc=26.27+0.26', 'option.Threads=1']
('TC limit', 36782.696368693985, 'End time:', datetime.datetime(2020, 7, 8, 15, 8, 35, 770))
Warning: 2 opening repetitions vs 1 games per encounter
Indexing opening suite...
Started game 1 of 200 (stockfish vs base)
Finished game 1 (stockfish vs base): 0-1 {Missing bishop: black wins}`
....
....
`Started game 37 of 200 (stockfish vs base)
Finished game 37 (stockfish vs base): 1-0 {Missing queen: white wins}
Score of stockfish vs base: 16 - 18 - 3  [0.473] 37
Started game 38 of 200 (base vs stockfish)
Warning: Illegal PV move d2d1k from base (1)
Warning: PV: Qd1 Qd3 Qa1 d2d1k
Warning: Illegal PV move d2d1k from base (1)
Warning: PV: Qd1 Qd3 Qa1 d2d1k
Warning: Illegal PV move d2d1k from base (1)
Warning: PV: Qd1 Qd3 Qa1 d2d1k
Warning: Illegal PV move d2d1k from base (1)
Warning: PV: Qd1 Qd3 Qa1 d2d1k
Warning: Illegal PV move d2d1k from base (1)
Warning: PV: Qd1 Qd3 Qa1 d2d1k
Warning: Illegal PV move d2d1n from base (1)
Warning: PV: Qd1 Qd3 Nf2 Qd4 Nh3 Nc5 Kf1 f5 Qc2 d2d1n
Warning: Illegal PV move d2d1k from base (1)
Warning: PV: Qd1 Qd3 Qa1 d2d1k
Warning: Illegal PV move d2d1k from base (1)
Warning: PV: Qd1 Qd3 Qa1 d2d1k
Warning: Illegal PV move d2d1k from stockfish (0)
Warning: PV:  d2d1k
Warning: Illegal PV move d2d1k from stockfish (0)
Warning: PV:  d2d1k
Warning: Illegal PV move d2d1k from stockfish (0)
Warning: PV:  d2d1k
Warning: Illegal PV move d2d1k from stockfish (0)
Warning: PV:  d2d1k
Warning: Illegal PV move d2d1k from stockfish (0)
Warning: PV:  d2d1k
Warning: Illegal PV move d2d1k from stockfish (0)
Warning: PV:  d2d1k
Warning: Illegal PV move d2d1k from stockfish (0)
Warning: PV:  d2d1k
Warning: Illegal PV move d2d1k from stockfish (0)
Warning: PV:  d2d1k
Warning: Illegal PV move d2d1k from stockfish (0)
Warning: PV:  d2d1k
Warning: Illegal PV move d2d1k from stockfish (0)
Warning: PV:  d2d1k
Warning: Illegal PV move d2d1k from stockfish (0)
Warning: PV:  d2d1k
Warning: Illegal PV move d2d1k from stockfish (0)
Warning: PV:  d2d1k
Warning: Illegal PV move d2d1k from stockfish (0)
Warning: PV:  d2d1k
Warning: Illegal PV move d2d1k from stockfish (0)
Warning: PV:  d2d1k
Warning: Illegal PV move d2d1k from stockfish (0)
Warning: PV:  d2d1k
Warning: Illegal PV move d2d1k from stockfish (0)
Warning: PV:  d2d1k
Warning: Illegal PV move d2d1k from stockfish (0)
Warning: PV:  d2d1k
Warning: Illegal PV move d2d1k from stockfish (0)
Warning: PV:  d2d1k
Warning: Illegal PV move d2d1k from stockfish (0)
Warning: PV:  d2d1k
Warning: Illegal PV move d2d1k from stockfish (0)
Warning: PV:  d2d1k
Warning: Illegal PV move d2d1k from stockfish (0)
Warning: PV:  d2d1k
Warning: Illegal PV move d2d1k from stockfish (0)
Warning: PV:  d2d1k
Warning: Illegal PV move d2d1k from stockfish (0)
Warning: PV:  d2d1k
Finished game 38 (base vs stockfish): 1-0 {Black makes an illegal move: d2d1k}
Score of stockfish vs base: 16 - 19 - 3  [0.461] 38
Started game 39 of 200 (stockfish vs base)
Finished game 39 (stockfish vs base): 1-0 {White wins by adjudication}
Score of stockfish vs base: 17 - 19 - 3  [0.474] 39`

I was able to save the (partial) PGN and viewed the game in cutechess GUI:

`[Event "?"]
[Site "?"]
[Date "2020.07.08"]
[Round "38"]
[White "base"]
[Black "stockfish"]
[Result "1-0"]
[FEN "rnbqkbnr/p1pppppp/8/1p6/P7/N7/1PPPPPPP/R1BQKBNR b KQkq - 0 1"]
[GameDuration "00:01:19"]
[GameEndTime "2020-07-08T05:29:43.732 UTC"]
[GameStartTime "2020-07-08T05:28:24.087 UTC"]
[PlyCount "116"]
[SetUp "1"]
[Termination "illegal move"]
[TimeControl "26.27+0.26"]
[Variant "extinction"]

1... b4 {+1.00/13 0.76s} 2. Nb1 {-0.23/13 1.1s} c5 {+1.01/12 0.55s}
3. c3 {-0.12/11 0.33s} Nc6 {+0.78/15 3.9s} 4. d4 {-0.06/11 0.41s}
e6 {+1.11/12 0.72s} 5. e3 {-0.40/14 2.9s} Rb8 {+1.29/13 1.3s}
6. Nd2 {-0.57/14 2.5s} d5 {+1.20/13 0.41s} 7. dxc5 {-0.79/14 2.2s}
bxc3 {+1.30/12 0.36s} 8. bxc3 {-0.90/12 0.49s} Bxc5 {+1.60/14 0.55s}
9. Ba3 {-0.60/15 2.0s} Bxa3 {+1.65/14 1.4s} 10. Rxa3 {-0.68/13 0.39s}
Na5 {+1.91/14 0.81s} 11. Ra1 {-0.34/12 0.25s} Rb2 {+2.35/14 0.33s}
12. Qc1 {-1.99/16 1.8s} Qb6 {+2.31/15 0.34s} 13. Rb1 {-1.68/14 0.38s}
Rxb1 {+2.86/13 0.32s} 14. Nxb1 {-1.60/13 0.29s} Qb3 {+2.72/13 0.37s}
15. Nd2 {-1.35/15 2.4s} Qb6 {+1.83/16 2.2s} 16. g3 {-0.88/15 2.0s}
Bb7 {+1.84/13 0.40s} 17. Bg2 {-1.19/15 0.96s} Ba6 {+1.81/15 1.3s}
18. Ne2 {-1.07/14 1.3s} Kd7 {+1.46/15 2.3s} 19. Nf4 {-0.38/14 1.2s}
Nc4 {+1.96/14 0.65s} 20. Nxc4 {-1.25/16 2.3s} Bxc4 {+1.69/15 0.39s}
21. Nh3 {-0.85/15 0.26s} f6 {+1.68/14 0.45s} 22. Ng1 {-0.92/14 0.36s}
Qb3 {+2.09/15 0.78s} 23. e4 {-0.62/16 0.74s} d4 {+4.18/12 0.17s}
24. cxd4 {-0.38/14 0.19s} Ba6 {+0.88/16 0.71s} 25. Qa1 {-0.34/13 0.17s}
Ne7 {+0.73/15 0.24s} 26. h4 {-0.71/15 1.2s} Rd8 {+0.96/14 0.30s}
27. h5 {-0.83/15 1.4s} e5 {+2.16/17 1.5s} 28. Kd2 {-1.30/17 1.2s}
Kd6 {+1.98/15 0.82s} 29. Rh3 {-0.67/12 0.096s} Qb4 {+2.61/15 0.86s}
30. Kd1 {-0.91/12 0.17s} Bc8 {+3.63/15 1.0s} 31. Rh4 {-0.78/14 0.34s}
h6 {+3.76/14 0.24s} 32. g4 {-3.60/17 1.2s} exd4 {+3.63/17 0.56s}
33. Qa2 {-2.52/14 0.15s} Rf8 {+4.22/15 0.26s} 34. Nh3 {-3.48/17 0.63s}
Qc3 {+3.98/18 0.93s} 35. Ng1 {-3.16/15 0.14s} Ba6 {+2.88/19 1.6s}
36. a5 {-1.96/19 0.63s} Bb5 {+3.42/15 0.20s} 37. Rh1 {-2.74/19 0.63s}
Bd7 {+3.71/18 0.50s} 38. Rh4 {-2.45/16 0.057s} Bb5 {+3.18/20 1.1s}
39. a6 {-3.00/19 0.54s} Ke5 {+3.58/16 0.28s} 40. Rh1 {-2.97/18 0.072s}
Kd6 {+3.55/21 0.73s} 41. Rh4 {-2.29/17 0.10s} Bc6 {+4.47/19 0.54s}
42. Bf1 {-1.47/19 0.21s} Nc8 {+6.77/19 0.66s} 43. Bg2 {-4.51/18 0.61s}
Nb6 {+6.98/16 0.16s} 44. Rh1 {-3.15/17 0.14s} Nd7 {+7.54/17 0.24s}
45. Rh2 {-3.11/17 0.13s} Nc5 {+8.70/18 0.31s} 46. Rh4 {-2.95/16 0.10s}
Bb5 {+9.19/21 0.50s} 47. Rh2 {-2.82/15 0.11s} Ke5 {+7.96/19 0.49s}
48. Rh4 {-2.60/17 0.18s} Rd8 {+8.23/18 0.25s} 49. Bh1 {-6.34/20 0.77s}
Rd7 {+6.69/21 1.0s} 50. Qb1 {-5.97/19 0.44s} Ba4 {+6.91/19 0.35s}
51. Ke2 {-4.56/15 0.15s} Rd8 {+8.07/17 0.14s} 52. Kf1 {-5.91/18 0.43s}
Bc6 {+7.80/17 0.40s} 53. Kg2 {-6.23/14 0.32s} d3 {+9.45/16 0.24s}
54. Qd1 {-5.84/16 0.27s} Bxe4 {+10.92/19 0.29s} 55. f3 {-5.10/15 0.12s}
Bc6 {+13.92/16 0.14s} 56. Nh3 {-7.66/17 0.29s} d2 {+16.56/16 0.19s}
57. Qg1 {-20.03/16 0.29s} Ne6 {+21.37/20 0.17s} 58. Qd1 {-M20/25 0.23s}
Qd4 {+M19/28 0.17s} 59. Qe2 {-M14/29 0.083s, Black makes an illegal move: d2d1k}
1-0` 

![2020-07-08-010146_479x662_scrot](https://user-images.githubusercontent.com/56622488/86893549-a3a06480-c0b6-11ea-947e-27a6b0943f87.png)

Thanks!

**Comment by ianfab** [comment]
Thanks for reporting. I already reported this issue (for kinglet, but should be the same for extinction) in the cutechess repository, see https://github.com/cutechess/cutechess/issues/563, therefore I am closing this one.
