### ISSUE TITLE
Undo move after setboard crashing in Janggi

### ISSUE THREAD

**Issue by sprinter89** [ianfab/Fairy-Stockfish#165]
The version I use is largeboard-86x64-modern

The sequence of commands makes stockfish crash.

xboard
variant janggi
setboard rnba1ab1r/4k4/1c4nc1/p1p1p1p1p/9/9/P1P1P1P1P/1C4NC1/4K4/RNBA1AB1R w - - 2 2
undo
d

The variant is important, I found normal chess variant does not crash.
But the fen string is not matter.

**Comment by ianfab** [comment]
Thanks for reporting. I think this is related to the handling of passing moves for CECP and a missing update of the move list there.
