### ISSUE TITLE
Can't move in UCI mode, How can I?

### ISSUE THREAD

**Issue by sprinter89** [ianfab/Fairy-Stockfish#166]
according to this website([http://wbec-ridderkerk.nl/html/UCIProtocol.html]), the command to move is something like "e2e4". it works in xboard, but it doesn't when in uci mode. how can I move pieces?

**Comment by gbtami** [comment]
Contrary to xboard protocol UCI is stateless. You always have to send starting position with all moves to the engine to tell what to think about. For example:
`position startpos`
`go depth 5`
info depth 1 seldepth 1 multipv 1 score cp 39 nodes 22 nps 11000 tbhits 0 time 2 pv e2e4
info depth 2 seldepth 2 multipv 1 score cp 39 nodes 46 nps 23000 tbhits 0 time 2 pv e2e4 d7d5
info depth 3 seldepth 3 multipv 1 score cp 39 nodes 72 nps 36000 tbhits 0 time 2 pv e2e4 d7d5 e4d5
info depth 4 seldepth 4 multipv 1 score cp 39 nodes 104 nps 52000 tbhits 0 time 2 pv e2e4 d7d5 e4d5 g8f6
info depth 5 seldepth 5 multipv 1 score cp 39 nodes 149 nps 74500 tbhits 0 time 2 pv e2e4 d7d5 e4d5 g8f6 b1c3
bestmove e2e4 ponder d7d5

`position startpos e2e4 e7e6`
`go depth 5`
info depth 1 seldepth 1 multipv 1 score cp 39 nodes 22 nps 11000 tbhits 0 time 2 pv e2e4
info depth 2 seldepth 2 multipv 1 score cp 39 nodes 46 nps 23000 tbhits 0 time 2 pv e2e4 d7d5
info depth 3 seldepth 3 multipv 1 score cp 39 nodes 72 nps 36000 tbhits 0 time 2 pv e2e4 d7d5 e4d5
info depth 4 seldepth 4 multipv 1 score cp 39 nodes 104 nps 52000 tbhits 0 time 2 pv e2e4 d7d5 e4d5 g8f6
info depth 5 seldepth 5 multipv 1 score cp 39 nodes 147 nps 73500 tbhits 0 time 2 pv e2e4 d7d5 e4d5 g8f6 b1c3
bestmove e2e4 ponder d7d5

**Comment by sprinter89** [comment]
thank you, gbtami!
