### ISSUE TITLE
 janggi finish error

### ISSUE THREAD

**Issue by kimqwer2** [ianfab/Fairy-Stockfish#170]
Stockfish can't see finish after update.

3ak4/4a4/4n4/1p2C4/4pp3/3P5/2b5R/3C5/2r6/1RBKA2rc w - - 0 1
![캡처](https://user-images.githubusercontent.com/63884391/89963815-9b25e580-dc83-11ea-8480-d5bcf335b73d.PNG)
![캡처1](https://user-images.githubusercontent.com/63884391/89963819-9d883f80-dc83-11ea-88c4-a797aaa568e4.PNG)
![캡처2](https://user-images.githubusercontent.com/63884391/89963822-9eb96c80-dc83-11ea-8f73-0e5f908ac904.PNG)

Stockfish can't see similar shapes.
5k3/9/9/C3C4/4p4/9/2b5R/9/2r6/1RBKA2rc w - - 0 1
![1](https://user-images.githubusercontent.com/63884391/89963963-fce64f80-dc83-11ea-8144-60bb19108b8a.PNG)
![2](https://user-images.githubusercontent.com/63884391/89963966-feb01300-dc83-11ea-8e0a-ae545b48dc44.PNG)

This happens in all modes of janggi. (janggi, janggimodern ....)

I don't know which update is the problem.
Commits on August 10, 2020 ~ Commits on August 11, 2020
I guess it's an update between these periods.
The update before this period seems to be well aware.

**Comment by ianfab** [comment]
Thanks for reporting, bug is confirmed.

```
setoption name UCI_Variant value janggi
position fen 3ak4/4a4/4n4/1p2C4/4pp3/3P5/2b5R/3C5/2r6/1RBKA2rc b - - 0 1
go depth 5
```
```
info depth 1 seldepth 2 multipv 1 score mate 2 nodes 110 nps 55000 tbhits 0 time 2 pv h1h2 i4i1
info depth 2 seldepth 4 multipv 1 score mate 1 nodes 181 nps 90500 tbhits 0 time 2 pv i1g1
info depth 3 seldepth 2 multipv 1 score mate 1 nodes 228 nps 76000 tbhits 0 time 3 pv i1g1
info depth 4 seldepth 2 multipv 1 score mate 1 nodes 275 nps 91666 tbhits 0 time 3 pv i1g1
info depth 5 seldepth 2 multipv 1 score mate 1 nodes 322 nps 107333 tbhits 0 time 3 pv i1g1
```

**Comment by ianfab** [comment]
I identified the change that caused this regression, see https://github.com/ianfab/Fairy-Stockfish/commit/44ee2f08a064b5d633c5c471c99eff8fb53f8642 for the revert. However, I do not understand yet why this fixes the problem, and I suspect this is indicating another issue.
