### ISSUE TITLE
Gemini 

### ISSUE THREAD

**Issue by gaintpd** [ianfab/Fairy-Stockfish#173]
Hello ianfab, could you add gemini variant support in fairy-stockfish. I dont  know whether it is feasible, if not, please ignore the little noise.
The rule is as follows:
https://musketeerchess.net/games/gemini/rules/rules.php

**Comment by gbtami** [comment]
You can play it as Capablanca using different starting FEN position `rnbaqkabnr/pppppppppp/10/10/10/10/PPPPPPPPPP/RNBAQKABNR w KQkq - 0 1`

**Comment by alwey** [comment]
@gbtami : This was my first reaction, too.  The only difference is that pawn promotion to Chancellor is illegal and thus suppressed by `GeminiBoard`, but it is legal in Capablanca Chess.

**Comment by gbtami** [comment]
@alwey good point.

**Comment by ianfab** [comment]
If I understand correctly Gemini is a subvariant of Janus, not of Capablanca, which is relevant for both promotion and castling. However, since Janus is also already supported, it is easy to add Gemini via the config file, e.g. the below should work.
```
[gemini:janus]
startFen = rnbjqkjbnr/pppppppppp/10/10/10/10/PPPPPPPPPP/RNBJQKJBNR w KQkq - 0 1
```

**Comment by alwey** [comment]
Indeed, the only difference would then be that symbol J were used instead of A.

**Comment by ianfab** [comment]
Using incompatible FENs for variants with identical rules only differing in the starting position does not sound like a good idea to me.

**Comment by alwey** [comment]
In cutechess I implemented `JanusBoard` with symbol J for Janus to be compatible with existing notation for that game.

**Comment by alwey** [comment]
I am considering an option for alternative symbols in variant play so that engines with different notations can play against each other ... kind of alias symbols.

**Comment by ianfab** [comment]
I was referring to Janus vs. Gemini. For me either letter is fine for the archbishop, but since it was already decided for Janus, Gemini as a subvariant of it should follow that convention. Aliases might help for some variants, but I think they should only be introduced very carefully for variants where inconsistent standards already exist, but not allowing too much flexibility for new variants where a consistent standard could still be achieved. Fairy-Stockfish by the way also has aliases, introduced for Xiangqi due to the different piece letters in CECP, UCI, and UCCI, but apart from Xiangqi they are not used so far.

**Comment by alwey** [comment]
> Aliases might help for some variants, but I think they should only be introduced very carefully for variants where inconsistent standards already exist, but not allowing too much flexibility for new variants where a consistent standard could still be achieved.

Yes!

**Comment by musketeerchess** [comment]
Hi
I think Fabian is right.

No need to make much work just to change the name of an existing piece. The most important is to play the variant online. So yes, can you add the few lines for Gemini Chess?

I also like the idea developed within cutechess allowing the possibility to mix notation so that different engines will be able to play each others.

It’s for sure a nice feature.

Thanks.

Zied 

Welcome to Musketeer Chess, the next Chess Evolution

**Comment by gaintpd** [comment]
> You can play it as Capablanca using different starting FEN position `rnbaqkabnr/pppppppppp/10/10/10/10/PPPPPPPPPP/RNBAQKABNR w KQkq - 0 1`

@gbtami Thank you very much for your reply.

**Comment by gaintpd** [comment]
> Indeed, the only difference would then be that symbol J were used instead of A.

@alwey Is there any other difference between the two variants besides the symbol?

**Comment by gaintpd** [comment]
> If I understand correctly Gemini is a subvariant of Janus, not of Capablanca, which is relevant for both promotion and castling. However, since Janus is also already supported, it is easy to add Gemini via the config file, e.g. the below should work.
> 
> ```
> [gemini:janus]
> startFen = rnbjqkjbnr/pppppppppp/10/10/10/10/PPPPPPPPPP/RNBJQKJBNR w KQkq - 0 1
> ```

I want to test my gemini implementation using the fairy-stockfish to guarantee the correctness. I dont know how to make it work with cutechess to take advantage of the variant.ini file. So that I can play gemini in cutechess against fairy-stockfish or let the fairy-stockfish play against fairy-stockfish.

**Comment by ianfab** [comment]
@gaintpd You can load a variants.ini file either via the UCI option `VariantPath` or by including `load variants.ini` in the command, see https://github.com/ianfab/Fairy-Stockfish/wiki/Variant-configuration#loading-variant-configuration. The latter is especially suited for GUIs, because they might detect the supported variants at startup of the engine, so if the variants are only loaded after startup via the `VariantPath` option, they might not correctly detect the support of the loaded variants, whereas when using `load` as part of the command the variants will already be available the first time the GUI detects the supported variants using the `uci` command.

**Comment by gaintpd** [comment]
Thank you ianfab, I have solve the problem, I should add load `variants.ini` the command lineedit as the follow screenshot.

![Screenshot from 2020-08-19 21-21-46](https://user-images.githubusercontent.com/17960782/90640130-30b40d00-e262-11ea-81ea-c864f2498d0e.png)

Thank you very much @ianfab

**Comment by gaintpd** [comment]
[Event "?"]
[Site "?"]
[Date "2020.08.19"]
[Round "?"]
[White "fairy-sf-lb11_1"]
[Black "fairy-sf-lb11_1"]
[Result "0-1"]
[GameDuration "00:04:08"]
[GameEndTime "2020-08-19T21:24:26.073 CST"]
[GameStartTime "2020-08-19T21:20:17.962 CST"]
[PlyCount "34"]
[Termination "illegal move"]
[TimeControl "40/300"]
[Variant "gemini"]

1. e4 {+0.67/23 8.2s} e5 {+0.34/20 8.8s} 2. d3 {+0.70/20 2.8s} d6 {+0.21/23 18s}
3. g4 {+0.84/20 2.7s} g5 {+0.10/22 4.7s} 4. Ng2 {+0.73/24 7.8s}
Ng7 {+0.07/20 3.0s} 5. Nc3 {+0.91/20 2.5s} Ne6 {+0.28/19 2.5s}
6. Ne3 {+0.66/22 8.4s} Nc6 {+0.37/20 3.8s} 7. Nf5 {+0.66/19 4.2s}
Ncd4 {+0.23/23 18s} 8. Ne2 {+0.72/21 12s} Nxf5 {+0.27/18 2.7s}
9. gxf5 {+0.53/20 4.0s} Nf4 {+0.05/21 8.5s} 10. Nxf4 {+0.69/20 4.5s}
gxf4 {+0.27/18 2.8s} 11. Ah3 {+0.58/20 4.5s} Ah6 {+0.26/18 2.8s}
12. Af3 {+0.46/22 26s} j5 {+0.23/19 3.9s} 13. j4 {+0.57/21 7.3s}
Af6 {+0.26/19 4.1s} 14. i3 {+0.49/19 2.5s} i6 {+0.21/20 15s}
15. Bi2 {+0.71/17 2.8s} Bd7 {+0.25/19 4.3s} 16. Bd2 {+0.52/22 20s}
Qe7 {+0.15/20 3.0s} 17. Qe2 {+0.44/19 2.3s}
Bi7 {+0.30/21 9.5s, **White makes an illegal move: f1b1**} 0-1

Now there is an problem arises like shako varaint, which files the king and rook occupy after castling. The test ended with an `illegal move: f1b1`.

**Comment by musketeerchess** [comment]
Hi
Castling should be the king moving 3 squares and the rook placed on the square next to the king.

So for short castle: king on i1 rook on h1 and long castle king on c1 and rook on d1

**Comment by alwey** [comment]
@gaintpd : My bad, Janus castling has King placed on b- or i-file, so this is different.
Capablanca has King on c- or i-file which is the same for Gemini, as @musketeerchess just stated.

**Comment by alwey** [comment]
```
[gemini:capablanca]
startFen = rnbaqkabnr/pppppppppp/10/10/10/10/PPPPPPPPPP/RNBAQKABNR w KQkq - 0 1
promotionPieceTypes = nbrqa
```

**Comment by ianfab** [comment]
Yes, if the castling rules are supposed as Zied described then that config should work. Since capablanca has a chancellor while geminni does not, removing it from the set of piece types with `chancellor = -` might give a small performance improvement.

**Comment by alwey** [comment]
@ianfab: if `chancellor = -` is used, should the assignment `promotionPieceTypes = nbrqa` be dropped or will this line still be necessary?

**Comment by ianfab** [comment]
Yes, it is strictly required. The promotion piece types are a separate set from the piece types (there is no implicit intersection), so if a piece type would be removed but still in the promotion piece types, that might cause undefined behavior. Generally I would recommend to inherit from a variant that has a subset of rules, not a superset, since it is easier to miss the removal of a rule than the addition of it. E.g., one could also use janus as the base and then modify the castling rights (and the piece char), which IMO is a bit cleaner.

**Comment by alwey** [comment]
```
[gemini:janus]
startFen = rnbaqkabnr/pppppppppp/10/10/10/10/PPPPPPPPPP/RNBAQKABNR w KQkq - 0 1
archbishop = a
castlingKingsideFile = i
castlingQueensideFile = c
```
This works AFAICS.

**Comment by gaintpd** [comment]
@gbtami @alwey @musketeerchess @ianfab Thank you all, I have test my gemini implementation in cutechess using the following user-defined variant in variant.ini
```
[gemini:capablanca]
startFen = rnbaqkabnr/pppppppppp/10/10/10/10/PPPPPPPPPP/RNBAQKABNR w KQkq - 0 1
promotionPieceTypes = nbrqa 
chancellor = -
```

Everything is OK.

**Comment by gaintpd** [comment]
A new illegal move encountered.
the fenstring is `6B3/2P1k2P2/3R6/pN2P5/10/10/8KP/1r8 w - - 3 63`

![Screenshot from 2020-08-20 21-37-02](https://user-images.githubusercontent.com/17960782/90776928-50643780-e32d-11ea-8900-6a62780a9731.png)

{-M8/41 0.32s, White makes an illegal move: c7c8-} 0-1

How to fix?

**Comment by gbtami** [comment]
Remove `chancellor = -` ?

**Comment by alwey** [comment]
Version 11.1 does not have this problem, 10.4 has. Tested with Capablanca-based definition.
However, both work with the Janus-based setup.

**Comment by gaintpd** [comment]
> Version 11.1 does not have this problem, 10.4 has. Tested with Capablanca-based definition.
> However, both work with the Janus-based setup.

The safe way to this solution is the Janus-based setup.

**Comment by alwey** [comment]
Perhaps `promotionPieceTypes` configuration has been added after version 10.4.

**Comment by ianfab** [comment]
Yes, variant.ini files are not always backwards compatible, so what I am saying always implicitly refers to the latest version. I try to avoid unnecessary incompatibilities, but sometimes it is hard to avoid when trying to improve it. When writing new variant configs and not being sure about it, please also use the config checker as mentioned in https://github.com/ianfab/Fairy-Stockfish/wiki/Variant-configuration#loading-variant-configuration to check whether there is any obvious issue that can be auto-detected.

**Comment by alwey** [comment]
I saved three or four generations of variant,ini files to roughly match the progress of fairy-stockfish versions, Old versions of stockfish should load the older files.

**Comment by ianfab** [comment]
You can also always download the default variants.ini of the respective release, which contains the documentation of the available configuration parameters of that release.

**Comment by alwey** [comment]
After checking, the janus-based setup still needs some work on the pieceToChar transformation.

```
Parsing variant: gemini
pieceToCharTable - Invalid piece type: J
pieceToCharTable - Invalid piece type: J
pieceToCharTable - Missing piece type: a
pieceToCharTable - Missing piece type: A
```

**Comment by ianfab** [comment]
You can basically ignore that. The `pieceToCharTable` is only required for Winboard/XBoard, since it needs to be told the rules, but cutechess should not use that.

**Comment by alwey** [comment]
Found a glitch in variant.cpp, line 701: Replace second upper-case` J` by lower-case` j`
`        v->pieceToCharTable = "PNBRQ............J...Kpnbrq............J...k";`

**Comment by alwey** [comment]
```
[gemini:janus]
startFen = rnbaqkabnr/pppppppppp/10/10/10/10/PPPPPPPPPP/RNBAQKABNR w KQkq - 0 1
archbishop = a
pieceToCharTable = PNBRQ............A...Kpnbrq............a...k
castlingKingsideFile = i  
castlingQueensideFile = c
```

**Comment by ianfab** [comment]
Oops, I missed that, thanks. Will you create a PR or shall I commit it myself?

**Comment by alwey** [comment]
Please commit yourself, I have not patched the code and have noz set up a Github repository for fairy-stockfish yet.

**Comment by alwey** [comment]
Added a section for Gemini to the [wiki](https://github.com/ianfab/Fairy-Stockfish/wiki/Variant-configuration#gemini).

**Comment by ianfab** [comment]
I added the config from the wiki to the default variants.ini in https://github.com/ianfab/Fairy-Stockfish/commit/ab4d4219aae9886c9615266e0561a4fd9491fc45, so I am closing this. If the variant will be merged in cutechess, we can still think about adding it to the built-in variants in Fairy-Stockfish as well.
