### ISSUE TITLE
Xiangqi drawn position evaluation: chariot vs complete defence

### ISSUE THREAD

**Issue by yawnoc** [ianfab/Fairy-Stockfish#178]
In <https://www.pychess.org/JIp0N8Ej?ply=95>, the game is surely drawn at move 48 (assuming perfect play).

Black has only a single chariot, which cannot win against red's well-positioned complete defence (2 advisors and 2 elephants) assuming perfect play by Red. However Fairy-Stockfish evaluates the position at −3.2, which is the best evaluation for Black throughout the entire game.

Generally speaking a lone chariot will draw against a complete defence (士象全) unless the defending side's 2 advisors and 2 elephants are poorly positioned (some examples of this are given in <http://www.xqinenglish.com/index.php/en/endgame/220/400>). However if any one of the four defending pieces are missing, then the chariot side can win.

**Comment by yawnoc** [comment]
I did some further experiments and it appears that Fairy-Stockfish's evaluation of Chariot vs Complete defence is affected by the presence of defensive material (advisors and elephants) on the Chariot's side, even though those pieces cannot be used in an attack (since there are no cannons).

The following games of the form
````
BLACK: Chariot + {irrelevant defensive material}
         VS
  RED: Complete defence
````
should *all* evaluate to zero (a draw), but in 7 out of 9 cases Fairy-Stockfish evaluates an advantage for Black which is roughly an increasing function of {irrelevant defensive material}.

| {Irrelevant defensive material} | Evaluation | Link | FEN |
| --- | --- | --- | --- |
| Nothing | 0.0 | [odOJDbQo](https://www.pychess.org/odOJDbQo?ply=0)\* | `4k4/9/9/9/9/9/8r/4B4/4A4/2B1KA3 w - - 0 1` |
| 1 advisor | 0.0 | [JHamY1Y6](https://www.pychess.org/JHamY1Y6?ply=0) | `3ak4/9/9/9/9/9/8r/4B4/4A4/2B1KA3 w - - 0 1` |
| 1 elephant | −0.3 | [sZAhhAPR](https://www.pychess.org/sZAhhAPR?ply=0) | `4k1b2/9/9/9/9/9/8r/4B4/4A4/2B1KA3 w - - 0 1` |
| 2 elephants | −0.7 | [NrmGxFe1](https://www.pychess.org/NrmGxFe1?ply=0)\* | `4k1b2/9/4b4/9/9/9/8r/4B4/4A4/2B1KA3 w - - 0 1` |
| 2 advisors | −1.0 | [TzaSkuyS](https://www.pychess.org/TzaSkuyS?ply=0)\* | `3ak4/4a4/9/9/9/9/8r/4B4/4A4/2B1KA3 w - - 0 1` |
| 1 advisor + 1 elephant | −1.3 | [UCqp9Z9v](https://www.pychess.org/UCqp9Z9v?ply=0) | `3ak1b2/9/9/9/9/9/8r/4B4/4A4/2B1KA3 w - - 0 1` |
| 1 advisor + 2 elephants | −2.5 | [fEurBbgJ](https://www.pychess.org/fEurBbgJ?ply=0)\* | `4k1b2/4a4/4b4/9/9/9/8r/4B4/4A4/2B1KA3 w - - 0 1`|
| 2 advisors + 1 elephant | −2.6 | [lns8YZQ0](https://www.pychess.org/lns8YZQ0?ply=0) | `3ak1b2/4a4/9/9/9/9/8r/4B4/4A4/2B1KA3 w - - 0 1` |
| Complete defence | −4.3 | [3gY90PcJ](https://www.pychess.org/3gY90PcJ?ply=0)\* | `3ak1b2/4a4/4b4/9/9/9/8r/4B4/4A4/2B1KA3 w - - 0 1`|

\* In the marked games Fairy-Stockfish (level 8) blunders the Chariot in desperation on the 50th move after the draw offer. Is this expected behaviour?

**Comment by ianfab** [comment]
Thanks for the detailed analysis.

Yes, the evaluation does not consider yet that there are purely defensive pieces in Xiangqi that can not participate in the attack, mainly because that is very specific knowledge for a quite generic engine as Fairy-Stockfish. So from my perspective the best attempt would be to try to decrease the (endgame) evaluation in cases where the side with the advantage has pieces that can never reach the mobility region (palace) of the opposing king/general, since this would be a generic rule but still should apply well to Xiangqi.

**Comment by gaintpd** [comment]
This is a problem resulted from the complexity of the endgame in xiangqi. As far as now, the possible solution for this problem is to add the endgame shape by shape that help the engine to do the right evaluation, just as ianfab said, this need the very specific knowledge, this is the approach for the xiangqi dedicated engines, eg, NewGG, you can find the repo in github. Another possible way may be the use of NNUE network, which needs a lot of training and may break the generality of Fairy-stockfish.

**Comment by HGMuller** [comment]
Evaluating defensive material in Xiangqi is a hard problem. You can bypass this to a large extent, however, by reconizing drawish positions, and strongly scaling their evaluation towards a draw score (like you would in Chess for KRNKR[P]). But one thing should be obvious: if the opponent has no attacking material at all, and you have no Cannons, your defensive material is completely useless, if not detrimental. This can be combined with the drawishness handling: if one side has defenders only, you should ignore the defenders of the other side, and check if the remaining (attacking) material is enough to overcome the defenders. If not, you scale towards draw, if it is, you subtract the value of the defenders. (But: having no defenders at all makes a single Cannon useless as well, and having only Elephants makes it semi-useless!)

Rook versus full defense is especially tricky; I suppose it is comparable to KBBKN in chess. It is usually draw, but a significant fraction of the positions can be won, usually with quite large DTC. If you don't want to rely on EGT the best approach would probably be to scale with one Elephant on the back rank and the other in the Eye by a large factor, and others only by a small factor; when the others are actually draws, it should be possible to reach a 'healthy' defensive position from them in just a few moves. The important thing here is to avoid persistent misevaluations.

**Comment by ianfab** [comment]
Already with the [current best NNUE network](https://fairy-stockfish.github.io/nnue/#current-best-nnue-networks) xiangqi-6f64c55fcb28.nnue this seems to be solved, as the evaluations of all the test positions are significantly lower than when you just remove one of the defenders. Therefore I am closing this.

| Irrelevant defensive material | Evaluation | FEN |
| --- | --- | --- |
| Nothing | -0.17 | `4k4/9/9/9/9/9/8r/4B4/4A4/2B1KA3 w - - 0 1` |
| 1 advisor | -0.42 | `3ak4/9/9/9/9/9/8r/4B4/4A4/2B1KA3 w - - 0 1` |
| 1 elephant | -0.36 | `4k1b2/9/9/9/9/9/8r/4B4/4A4/2B1KA3 w - - 0 1` |
| 2 elephants | -0.20  | `4k1b2/9/4b4/9/9/9/8r/4B4/4A4/2B1KA3 w - - 0 1` |
| 2 advisors | -0.34 | `3ak4/4a4/9/9/9/9/8r/4B4/4A4/2B1KA3 w - - 0 1` |
| 1 advisor + 1 elephant | -0.21| `3ak1b2/9/9/9/9/9/8r/4B4/4A4/2B1KA3 w - - 0 1` |
| 1 advisor + 2 elephants | -0.31 | `4k1b2/4a4/4b4/9/9/9/8r/4B4/4A4/2B1KA3 w - - 0 1`|
| 2 advisors + 1 elephant | -0.33 | `3ak1b2/4a4/9/9/9/9/8r/4B4/4A4/2B1KA3 w - - 0 1` |
| Complete defence | -0.51 | `3ak1b2/4a4/4b4/9/9/9/8r/4B4/4A4/2B1KA3 w - - 0 1`|
| Nothing, but incomplete opponent defense | -1.78 | `4k4/9/9/9/9/9/8r/9/4A4/2B1KA3 w - - 0 1` |
