### ISSUE TITLE
Xiangqi perpetual chase of unprotected piece

### ISSUE THREAD

**Issue by yawnoc** [ianfab/Fairy-Stockfish#179]
In <https://www.pychess.org/JJIkf7Hd>, Fairy-Stockfish perpetually chases the unprotected cannon, which is illegal (instead of a draw).

This could be difficult to implement as the rules are quite complicated. (For example, perpetually chasing a *protected* piece is perfectly fine.) From <http://wxf.ca/wxf/doc/book/WXF_rules_Eng.pdf>:

> ## 1 Common terms
>
> **Perpetual chase:** Player A makes a succession of chasing moves, while player B answers each move by moving away the piece under attack, or resolving the chase with another piece. If A continues to attack the piece move after move, he is making a "perpetual chase".
>
> **Real root:** When a protected piece is captured, and the protector can in turn capture the captor, the protector is a "real root".
>
> **Fake root:** When a protected piece is captured, the protector is immobilized and cannot take the captor immediately.
>
> ## 3 General Rules
>
> 3\) Perpetual chase of one piece on another piece (other than a pawn that has yet to cross the river) will be ruled as a loss. It is also illegal for two or more pieces to make perpetual on one piece, except when one of the chasing pieces is a pawn or a king.
>
> 6\) Perpetual chase on a piece with real root will be declared a draw. It is a draw if the protector is a fake root. However, perpetual chase on a chariot by a horse or a cannon is prohibited.

Related: #142

**Comment by ianfab** [comment]
Thanks. We already have an issue at https://github.com/ianfab/Fairy-Stockfish/issues/55 for this, therefore I am closing this. Please feel free to leave a comment there if you have any additional information.
