### ISSUE TITLE
Missed sacrifices in Janggi

### ISSUE THREAD

**Issue by kimqwer2** [ianfab/Fairy-Stockfish#184]
SF is not very good at judging the risks of Soldier. The score changes dramatically.
It seems like SF is searching randomly.
Therefore, there are some cases where errors are not made, and others are.
![ggggg](https://user-images.githubusercontent.com/63884391/93714502-13929700-fb9e-11ea-8b9b-9c2da4c3519a.png)
In the first scene,
(-0.32) --->   (-1.66)
3a1a3/4k4/2n1cn3/1pppb2pp/r8/8P/P2PB1rNP/4CC3/3AK4/R4AB1R w -- 0 1

In the second scene,
(+0.53) ---> (-1.23)  , (-1.99)
3a1a3/4k4/2n1cn3/1pp1bp1pp/r8/8P/P2PB1rNP/4CC3/3AK4/R4AB1R w -- 0 1

Appears many times in a similar structure.

![aaaaa](https://user-images.githubusercontent.com/63884391/93714521-302ecf00-fb9e-11ea-8a9b-c0ec29bbede8.png)
In this scene,
(+0.39) ---> (-4.60)
rnbak1b1r/4a4/6n1c/pp2p3p/1c3p3/6R2/1PPPB1PP1/R1N1C1NC1/4K4/2BA1A3 b - 19 10

**Comment by ianfab** [comment]
Thanks, the FENs are very helpful. I quickly checked, and to my understanding the justifications for the sacrifices in the two positions are:
1. Deflecting the pawn to play Eh4 attacking the central cannon.
2. Deflecting the rook with Ri7 to force checkmate (or regaining the rook with a winning position).

Fairy-SF perhaps does too much pruning for Xiangqi and Janggi and therefore misses some sacrifices, as can also be seen in https://github.com/ianfab/Fairy-Stockfish/issues/107. I already ran some tests on this in the past, but they were not conclusive, so this will need more testing and ideas how to improve it in the future.

**Comment by ianfab** [comment]
Since it is closely related to #107 I quoted the comments there and am closing this one here.
