### ISSUE TITLE
Missing ffishjs features (part 2)

### ISSUE THREAD

**Issue by gbtami** [ianfab/Fairy-Stockfish#185]
- [x] Make moveStack of the Board available (to show user entered moves in local/in-browser analysis)
- [x] Load variant configurations as string (instead of a file path) as @ianfab suggested in https://github.com/ianfab/Fairy-Stockfish/pull/182#issuecomment-689722355
- [x] Add a new function to iterate over SAN move list using pushSan() (Give move list as space delimited string as parameter)

**Comment by QueensGambit** [comment]
+ [x] Make moveStack of the Board available (to show user entered moves in local/in-browser analysis)
-> see https://github.com/ianfab/Fairy-Stockfish/pull/187

+ [x] Add a new function to iterate over SAN move list using pushSan() (Give move list as space delimited string as parameter)
What do you mean by this exactly? Can you elaborate?

**Comment by gbtami** [comment]
@QueensGambit I like to implement a basic .pgn import for pychess. I can achieve this calling pushSan() for all moves now, but it would be more convenient to do it with one function call only.
