### ISSUE TITLE
Kakao janggi has 2 types of repetition rules.

### ISSUE THREAD

**Issue by cjssh1002** [ianfab/Fairy-Stockfish#198]
Kakao janggi has 2 types of repetition rules.
I explain to you the repetition rule.
I hope you apply this rule to the FS-engine(modern).

  *A: counter position of Repeat
1. First repetition rule: B-A 1 time, C-A 2 times
2. 3rd repetition rule: B-A 3 times 
* Can be : B-A 2 times, C-A 1 time

No.2 has already been applied. 
However, No.1 has not yet been applied.

**Comment by ianfab** [comment]
Thanks. If I understand correctly, A/B/C refer to positions, not moves, so does this mean the repetition detection in Kakao Janggi is based purely on positions, and not on moves? If this is the case, that would simplify matters for me.

Currently, repetition detection in Fairy-Stockfish is purely based on the reoccurrence of a single position, so it does not matter how many other positions occur in between or in which order. Therefore it does not depend on being a straightforward back-and-forth movement pattern with positions repeating like A-B-C-D-A-B-C-D-A or the like.

If this does not cover the scenario you are referring to, can you please explain it in more detail? I am not sure yet whether A/B/C in your patterns above refer to moves, positions, or positions with the same side to move.

**Comment by cjssh1002** [comment]
Exactly, it is based on the order of positions.

**Comment by ianfab** [comment]
Summary from a discussion on discord on the criteria for prohibiting a repetition in Kakao Janggi:
* The repetition detection is solely based on the moves of one side
* A repetition is prohibited in the case a piece moves between two squares A and B two times in a row (ignoring opponent's moves): A->B B->A A->B **B->A**. The last move in this sequence is illegal. Or described more technically: If a move is described as the operation M, the sequence M -M M **-M** is prohibited.

**Comment by ianfab** [comment]
@cjssh1002 I tried to implement the above rules in https://github.com/ianfab/Fairy-Stockfish/commit/cabb1f562092235e53c3f755a503c903816144c0 and it seems to work, but I did not have much time to test it yet. If you like to test it already, feel free to do so. Feedback would be very welcome.

**Comment by cjssh1002** [comment]
I forgot about the only 1 rules.
* Repetition does not apply to "Wazir" moves.

**Comment by bas-del** [comment]
It doesn't know the exact algorithm yet (there are no programming files from Kakao Janggi). What I am most concerned about is that the application of this is likely to make the analysis more confusing (concerns that cause radical pruning). This is a human-adjustable sector, so it is not a big problem for engine activity.

**Comment by ianfab** [comment]
Update:
* The repetition detection is solely based on the moves of one side
* Repetition does not apply to king and guard moves
* Repeated passing does not count as a repetition. Passing moves are skipped when checking for a sequence of repeated moves, so they do not reset the repetition count. (Is this correct?)
* A repetition is prohibited in the case a piece moves between two squares A and B two times in a row (ignoring opponent's moves) if the previous move ended on square A (i.e., a move by the same piece): any->A A->B B->A A->B **B->A**. The last move in this sequence is illegal.

**Comment by cjssh1002** [comment]
Yes it is correct.

**Comment by ianfab** [comment]
I tried to fix the reported issues, please have another look: https://github.com/ianfab/Fairy-Stockfish/commit/bee163eabaeec25ef84c25e0fbc492632e762cc7

**Comment by cjssh1002** [comment]
You must be tired. Thank you for your effort. ^_^
Now me and my janggi cafe members will fully test for the official master merge.

**Comment by cjssh1002** [comment]
There is rule that needs to be modified.  This is a kakao janggi rule that i was very hard to find.

- Movements that can capture pieces are not included in the repeat counter.
- After capturing the piece, the piece is reset repeat counter.
