### ISSUE TITLE
Travis CI and Appveyor

### ISSUE THREAD

**Issue by ddugovic** [ianfab/Fairy-Stockfish#2]
Perhaps it would be useful to deploy Fairy-Stockfish on Travis CI and on Appveyor.

**Comment by ianfab** [comment]
Yes, makes sense. I think it should only require minor adaptions of the CI scripts, at least for testing compilation and standard chess searches only.

**Comment by ianfab** [comment]
Apart from a strange issue in the bench verification of 64bit Mac builds on Travis, the CI builds seem to work fine.
