### ISSUE TITLE
CECP error messages

### ISSUE THREAD

**Issue by HGMuller** [ianfab/Fairy-Stockfish#203]
The CECP driver of Fairy-Stockfish now handles unknown commands and illegal moves the same way, though an 'Unknow command' response. For moves CECP specifies an 'Illegal move' response, though. This is not just a moot point: CECP GUIs are supposed to take back the move played by the (usually human) opponent on 'Illegal move', to keep the GUI in sync with the internal state of the engine. Especially in variants, where the engine might want to enforce rules that are a bit more strict than can be specified with 'piece' commands (e.g. rules on what can capture what, or what you can promote to where), 'Illegal move' commands should be considered a normal part of the engine-GUI communication.

So rather than treating any unrecognized token as a move with an optional "usermove" prefix, the code now handling moves should be within the 'else if(token == "usermove")' clause, and the emitted error message when the move doesn't parse should become "Illegal move". The printing of the current message can then be moved to a final "else" for the remaining cases. Since the usermove=1 feature guarantees all moves will have that prefix, there is no need to test unrecognized commands for being a move.

This also prevents unimplemented commands to be mistaken for ponder misses...

**Comment by ianfab** [comment]
Thanks, I was not aware that this simplification actually affects functionality. The CECP implementation in Fairy-SF overall is quite simplistic and hacky, but this particular issue can be solved easily, so I will fix it asap.
