### ISSUE TITLE
LARGEBOARDS compiled with msvc running error

### ISSUE THREAD

**Issue by htomtom** [ianfab/Fairy-Stockfish#21]
When compiled with msvc using LARGEBOARDS, it seems running unlimitted time.  When run into the  Bitbases::init() or Threads.set(Options["Threads"]) in main(), the error occurs, throws "access conflict at 0x000000000085C070", stop at the line:
   repeat |= (db[idx] == UNKNOWN && db[idx].classify(db) != UNKNOWN);
when comment line Bitbases::init() , the error throws within set_state( ) module，throws "access conflict at 0x000000009F71798C" stop at the line
   si->key ^= Zobrist::psq[pc][s];

**Comment by ianfab** [comment]
Thanks for reporting it. I unfortunately do not have a setup for testing the compilation with MSVC at the moment, but there are a few issues I found in the code that are related to the issues you are seeing:
- Bitbases do not work and are not used for large boards at the moment, so the initialization should consequently also be skipped. This should fix the first issue, as you already mentioned.
- The bitboard operations popcount, lsb and msb are not implemented properly for MSVC in the large-board version, so it can not work at the moment. https://github.com/ianfab/Fairy-Stockfish/blob/0811ca24daad29b003c00b00a2bfc520229f4ac9/src/bitboard.h#L373-L377
https://github.com/ianfab/Fairy-Stockfish/blob/0811ca24daad29b003c00b00a2bfc520229f4ac9/src/bitboard.h#L415-L457
I am not entirely sure whether fixing these three functions would already completely solve the issues, but this should be the first step.

I hope I will find the time to address this soon. If you are interested, you can also try it yourself. The implementation of the bitboard operations can be analogous to how I generalized it from 64bit to 128bit for GCC:
https://github.com/ianfab/Fairy-Stockfish/blob/0811ca24daad29b003c00b00a2bfc520229f4ac9/src/bitboard.h#L379-L383
https://github.com/ianfab/Fairy-Stockfish/blob/0811ca24daad29b003c00b00a2bfc520229f4ac9/src/bitboard.h#L391-L411

**Comment by htomtom** [comment]
Thanks a lot for your detailed reply. I will try the above methods you mentioned and test them. If I have time, I'll simulate the popcount, lsb and msb operations for msvc, although I do not have much experience with bitboard operation.

**Comment by ianfab** [comment]
I started to work on it, you can check out the [msvc](https://github.com/ianfab/Fairy-Stockfish/tree/msvc) branch. However, I do not even know whether it compiles with MSVC (and I skipped the implementation for 32bit hardware for now). Would be nice if you find the time to test and possibly fix it.

**Comment by ianfab** [comment]
@htomtom The [msvc branch](https://github.com/ianfab/Fairy-Stockfish/commits/msvc) works fine with MSVC on appveyor now. Could you please check whether it also works for you locally?

**Comment by htomtom** [comment]
I start a rough test, and it works well. Nice!
