### ISSUE TITLE
Missed mate in 1 in S-Chess

### ISSUE THREAD

**Issue by Curious2021** [ianfab/Fairy-Stockfish#210]
![CDDA09DF-7A65-4328-8775-54F6A0371FCB](https://user-images.githubusercontent.com/73664660/99815387-372f7a80-2b18-11eb-803c-8b42737dd16b.png)

I was playing S-Chess(Seirawan Chess) on Pychess and discovered this setup of chess pieces causes Fairy Stockfish to fail to see the mating threat. It repeatedly failed to see the threat and was checkmated everytime. I played this using level 6. You can use the same setup as this image shows and Stockfish Fairy will not see the mate.

**Comment by ianfab** [comment]
Levels below 8 are artificially weakened, so it is no surprise that they make blunders. So as long as this can not be reproduced on level 8, I would not consider it a bug.

**Comment by Curious2021** [comment]
![9A785283-7236-4D26-8312-C15367DCCD0F](https://user-images.githubusercontent.com/73664660/99847030-68726f80-2b45-11eb-8f52-78eeb60ffae8.png)

Really? Think again. This one was in Level 8.

**Comment by ianfab** [comment]
Thanks for testing it. Since you are able to reproduce it with level 8, that makes it a bug. I suspect this might have to do with SEE pruning and gating not being considered in there.

**Comment by Curious2021** [comment]
https://www.pychess.org/wbnPamiu

This is a serious flaw. I tested this yet again and even after detecting the mate in one Stockfish fails to defend correctly and gets mated quickly.
