### ISSUE TITLE
Xiangqi ucci

### ISSUE THREAD

**Issue by wawahuy** [ianfab/Fairy-Stockfish#219]
I see fen
`4k4/9/9/9/9/9/8r/4B4/4A4/2B1KA3 w - - 0 1`
What does `w -- 0 1` mean?
Can help me with perfect example?
Example A walk, B walk step,....

**Comment by ianfab** [comment]
The UCCI FEN format is explained in Chinese in https://www.xqbase.com/protocol/cchess_fen.htm. It is based on the FEN standard for chess https://en.wikipedia.org/wiki/Forsyth%E2%80%93Edwards_Notation.
