### ISSUE TITLE
Gothic Chess

### ISSUE THREAD

**Issue by gbtami** [ianfab/Fairy-Stockfish#22]
Seems it's not patented from years https://www.chessvariants.com/large.dir/gothicchess.html so why not?
Ed Trice is playing right now at https://greenchess.net/game.php?id=10652

**Comment by ianfab** [comment]
If the patent is really expired, configuring the rules of gothic chess should be as simple as:
```
    Variant* gothic_variant() {
        Variant* v = capablanca_variant();
        v->startFen = "rnbqckabnr/pppppppppp/10/10/10/10/PPPPPPPPPP/RNBQCKABNR w KQkq - 0 1";
        return v;
    }
```

**Comment by gbtami** [comment]
I went and checked USPTO links given on chessvariants page I linked, and seen the same what it wrote .
http://i.imgur.com/oDf055V.png
