### ISSUE TITLE
Book in xiangqi chess

### ISSUE THREAD

**Issue by wawahuy** [ianfab/Fairy-Stockfish#223]
![image](https://user-images.githubusercontent.com/16779694/103078354-41a3cf00-4604-11eb-82ee-5bb4e3f135a4.png)

I shouldn't ask questions here.
I see nbook.bin, rbook.bin,... Is there any way to use it with engine or nodejs

**Comment by ianfab** [comment]
Fairy-Stockfish does not support opening books, see #112, but if the GUI you are using supports those books, it should work independently of the engine. I do not know which format the books are using, but if they are polyglot books, then Winboard/XBoard could be used. For such kind of questions the Fairy-SF discord is a good place to ask, see the link in the readme.
