### ISSUE TITLE
Only dowload NNUE net if required

### ISSUE THREAD

**Issue by ianfab** [ianfab/Fairy-Stockfish#257]
Currently the standard chess NNUE net from official Stockfish is always downloaded even when not including the net in the binary (`nnue=no`).
* Update makefile to skip download when not required (but always download it on `make net`)
* Adjust CI if required to consider this change

**Comment by CPagador** [comment]
Hi, I got a binary donwloading the artifact zip from build #75. I'd like to use it mostly for Gothic and Crazyhouse. Where can I download the NNUE file for those variants?

**Comment by ianfab** [comment]
Hi, there are no NNUE nets for Crazyhouse and Gothic chess yet, only for a few selected variants, also see https://www.patreon.com/ianfab or the [variant NNUE overview](https://docs.google.com/spreadsheets/d/1fgGvBKleUOI1wZZbiNhpT98qhQ7mYuQ5kar1lTQ9g3w/edit?usp=sharing). The NNUE training and playing code still needs more work to support a wider range of variants, also see https://github.com/ianfab/Fairy-Stockfish/issues/199, so you can currently only use classical evaluation for these variants.

**Comment by CPagador** [comment]
I see, thanks for the reply. 

Is there any project to implement spartan chess?

**Comment by ianfab** [comment]
Currently not, but if you are interested in the variant, feel free to open an issue for it. I can not promise that I will work on it, but it is always good to at least have an overview which variants users would be interested in.
