### ISSUE TITLE
New release for ffish.js

### ISSUE THREAD

**Issue by gbtami** [ianfab/Fairy-Stockfish#265]
Atomic is supported now in Fairy, and I like to add it to pychess.org as well, but SAN conversation of PV lines is not working with current version.
@QueensGambit may I ask you to create a new release, please?

**Comment by QueensGambit** [comment]
Hello @gbtami ,
could you elaborate what is not working with the SAN conversion of PV lines by giving an example?
These are the current unit tests for `board.variationSan(uciMoves)` and they are still passing for [**ffish.js@0.6.0**](https://www.npmjs.com/package/ffish/v/0.6.0).
https://github.com/ianfab/Fairy-Stockfish/blob/487a52ef17e2e8c3a5cb7574078bc51bfc0c9189/tests/js/test.js#L227-L257

**Comment by gbtami** [comment]
You are right. I mixed something up. It works OK.
Sorry for the noise.
