### ISSUE TITLE
Janggi  compile ERROR in variant

### ISSUE THREAD

**Issue by d4soft2021** [ianfab/Fairy-Stockfish#275]
Recently I asked /varian=janggicasual
and I download variant.cpp as you guided.
Compile ERROR
  no member variable castlingKingPiece in variant struct
  Variant* knightmate_variant() {
		Variant* v = fairy_variant_base();
		v->add_piece(COMMONER, 'm');
		v->remove_piece(KNIGHT);
		v->startFen = "rmbqkbmr/pppppppp/8/8/8/8/PPPPPPPP/RMBQKBMR w KQkq - 0 1";
		v->kingType = KNIGHT;
		v->castlingKingPiece = KNIGHT;
		v->promotionPieceTypes = { COMMONER, QUEEN, ROOK, BISHOP };
		return v;
	}
    and variant.h has no such member variable.
    I download source and unzip them, I think variant.h there is old version.
   Where can I get newest one ?  about  variant.cpp,varint.h

   Thank you .

**Comment by ianfab** [comment]
May I please ask you to continue in the existing thread/issue #274 as long as it is closely related to that? It really is not that handy to maintain so many threads for just a single topic.

Please do not mix different code versions. I just referred to that code for explanation, you do not need to do any changes there.
