### ISSUE TITLE
Array based movegen integration question

### ISSUE THREAD

**Issue by maksimKorzh** [ianfab/Fairy-Stockfish#280]
Hi Fabien

First of all thank you so much for all the previous replies.

I have an array based movegen for xiangqi in js that I'm now porting to c++ and trying to integrate with sf.

I've realized that it's easier to write this custom movegen from scratch rather than having a pain of disabling all the bitboard related stuff.

My question is - is it possible to reuse search only (preferably without threads) from sf as a module?

I just don't need anything but search, uci and timing from sf.

Could you please kindly suggest the way to go?

Just a brief pointing of available directions/options would be more than enough. I just don't yet understand enough how much sf's search relies on a particular position object. It feels very monolithic and I want to make it as modular as possible.

Edit: what I currently do is writing function duplicates, for instance xq_set(fenStr) to init xiangqi board array from fen without touching bitboards. I can also make my own versions of generate<LEGAL>(), pos.do_move() etc. And eventually end up on perft testing. But when it comes to search I feel very confused because apart from zobrist hash keys search seems to be relying on some additional keys that I neither want to maintain nor to inctementally update.
Hence I'm not sure whether my current approach is fine or leads to nowhere.

**Comment by ianfab** [comment]
Since this now is very specific to https://github.com/maksimKorzh/xiangqi-stockfish and not directly related to this project, can we please move the discussion there? Feel free to ping me there if you create a new issue.

**Comment by maksimKorzh** [comment]
I'm so sorry for polluting your project's issues, I just didn't dare to ask you directly in the context of my project.
I've moved question here: https://github.com/maksimKorzh/xiangqi-stockfish/issues/1
Thanks in advance!
