### ISSUE TITLE
Diana chess kingside castling not working

### ISSUE THREAD

**Issue by Belzedar94** [ianfab/Fairy-Stockfish#295]
Good morning,

There is an issue on the kingside castling if the board is small enough to have 2 moves for the same notation (Either castle or move the king). This usually happens in 960 positions, but if 960 is not active and the requirements are met, castling will be faulty.

Attaching the specific variant definition and startpos:

[diana:losalamos]
promotionPieceTypes = rbn
castling = true
castlingKingsideFile = e
castlingQueensideFile = b
startFen = rbnkbr/pppppp/6/6/PPPPPP/RBNKBR w KQkq - 0 1

Thank you

**Comment by ianfab** [comment]
Thanks. https://github.com/ianfab/Fairy-Stockfish/commit/ba7163daac853ee34e7d1b3d34ae4c6ce3f40384 is a potential fix. Will need to be clarified if GUIs already have some logic to handle this.
