### ISSUE TITLE
Documentation of variant configuration options

### ISSUE THREAD

**Issue by ianfab** [ianfab/Fairy-Stockfish#30]
Documentation of the variant configuration options should be available in variants.ini and variant.h. Additional examples could be collected in wiki.

**Comment by gbtami** [comment]
Added Grand-house to wiki.

**Comment by ianfab** [comment]
Thx. Now there is quite some flexibility to share variants, I am just not sure where to draw the line, but a reasonable rule of thumb (there is of course is no need for a hard rule) where to put a variant could maybe be:
- **in variant.cpp**: popular variants and variants explicitly supported by GUIs, e.g., crazyhouse, since those variants should be "written in stone" (and covered by perft tests).
- **in default variants.ini:** well-known variants, but not very popular, e.g., indian great chess, since they might be considered useful by many
- **in wiki**: user-invented or relatively unknown variants

3check-crazyhouse and anti-losalamos to me rather belong to the third category, I just put them into the variants.ini because I was lacking instructive examples.

**Comment by ianfab** [comment]
I added the list of all available options to the INI in https://github.com/ianfab/Fairy-Stockfish/commit/ad9eec8dbcd28be36c2acfbbf4875cc4b87e00e8#diff-c2603b10ee775cac85b483d9317f4d76 and started to describe some of them. If anyone wants to help with extending the documentation on the options, that would be very welcome.

**Comment by ianfab** [comment]
Now that some basic documentation on all variant configuration options is available, I think it would be a good timing to do the first release that includes the variant configuration feature in the next days. If there is some feedback on the documentation (or otherwise) that should be addressed beforehand, please let me know.
