### ISSUE TITLE
Trouble definining royal piece

### ISSUE THREAD

**Issue by DanilaK01** [ianfab/Fairy-Stockfish#306]
I'm trying to implement a chess variant where the king cannot move but can still be put in check and get checkmated:
`[treechess:chess]
immobile = k
kingType = k
castling = false`
I've run into an issue that the 'immobile' doesn't get put in check.
My question is how do you properly define a royal piece?

**Comment by ianfab** [comment]
In principle this is correct, however since chess already has assigned k to the king piece, your definition is ambiguous. If you just pick any other free letter instead of k it should work.

**Comment by DanilaK01** [comment]
So I've picked the letter "t" for my piece and changed the starting FEN but it didn't solve the issue. This position is not considered checkmate and the king is not considered to be in check.

> rnbqtbnr/1ppp1Qpp/p7/4p3/4P3/8/PPPP1PPP/RNB1TBNR b - - 0 3

**Comment by ianfab** [comment]
Fairy-Stockfish only supports exactly one royal piece type, which is the king. Therefore, you do not assign royalty to piece types, but assign a piece type to the king/royal piece. So when you define `kingType = t`, this means that the king piece will move like the piece type that has the letter t. With the starting position unchanged, it should thus work, e.g.:
```
[treechess:chess]
immobile = t
kingType = t
castling = false
```

**Comment by DanilaK01** [comment]
Everything seems to be working now. Thanks a lot!
