### ISSUE TITLE
Xiangqi

### ISSUE THREAD

**Issue by ianfab** [ianfab/Fairy-Stockfish#31]
Open problems for a Xiangqi implementation:
- [x] Hopper/Cannon move generation
- [x] Lame leapers (elephant, horse)
  - [x] consider time-asymmetrical movement of horse in attackers calculation
  - [x] precalculated magics
- [x] Configurable area for piece movements (general, elephant, advisor)
  - [x] consider in move generation, and attack/attackers_to calculation
- [x] Alternative royal pieces (wazir-style movement of general)
- [x] Position-dependent move of soldier
- [x] Flying general rule (face-off)
- [x] basic chasing rules
  - [x] perpetual check illegal
  - [ ] 3fold illegal
- [x] make piece abbreviations consistent with UCCI convention (only use XBoard convention for XBoard protocol) 

Possible further improvement:
- [ ] complex chasing rules

Current state of incomplete xiangqi implementation is on [branch xiangqi](https://github.com/ianfab/Fairy-Stockfish/tree/xiangqi).

**Comment by CouchTomato87** [comment]
The general face-off is not a problem?

**Comment by ianfab** [comment]
That also still needs to be implemented, so I should actually add it to the list, but it is rather easy to implement, that is why I forgot to mention it.

**Comment by CouchTomato87** [comment]
Gotcha. Also are you accounting for the possibility of implementing Janggi as well? It's a little annoying because you can choose your horse/elephant position as well as pass turns...

**Comment by ianfab** [comment]
Yes, I already thought about it, and from my perspective the most difficult are the special moves of the pieces, namely the moving options in the castle and the fact that cannons can not jump over cannons. Those really break some core assumptions within in the code (e.g., that the position on the board and the type of blocking pieces do not have any impact on the moving possibilities of a piece).

So currently I see it as very difficult, not to speak of that it basically requires the Xiangqi implementation, which will already be challenging. As soon as the latter is done (I aim to get it done still this year), I will reconsider how feasible Janggi is.

**Comment by ianfab** [comment]
Does anyone know other variants where the rules restrict certain pieces to specific areas of the board?

The only ones that come to my mind are all closely related to Xiangqi (minixiangqi, Janggi, congo), so I am thinking about whether this rule really needs to be implemented in a generic way or can be made specific for Xiangqi-like variants.

**Comment by CouchTomato87** [comment]
Not to my knowledge, at least for well-known variants.

**Comment by ianfab** [comment]
Ok, thanks.

**Comment by CouchTomato87** [comment]
Slight amendment to that. Apparently Rococo has a restriction, but that game is based on Ultima, and I don't think Fairy Stockfish is equipped for that.

**Comment by ianfab** [comment]
Thanks for the update, but I now anyway already went for a generic implementation on the Xiangqi branch, see https://github.com/ianfab/Fairy-Stockfish/commit/a4e744c839bb57bcaac7f6674d9853a43d34e146, and it seems to be working.
