### ISSUE TITLE
Wider UCI_Elo range

### ISSUE THREAD

**Issue by niklasf** [ianfab/Fairy-Stockfish#316]
I am finally in the process of finishing niklasf/fishnet#174, which was pretty painless so far. All the variants are working nicely out of the box.

The only remaining todo appears to be that ddugovic/Stockfish had support for even weaker skill levels. Currently it feels like Fairy Stockfish might be too strong for beginners, even on the lowest available level.

For reference, this UCI_Elo range was used by fishnet:
https://github.com/niklasf/fishnet/blob/78782635b5b533ffda68b6bd1f739e896f21ae44/src/api.rs#L226-L233

And some related commits from ddugovic/Stockfish:
ddugovic/Stockfish@b8efae6ef396ad968c251b85145a6187f3a062fe, ddugovic/Stockfish@0d35a730007c5f1b2607a9333532f6e7a8bb505e

**Comment by ianfab** [comment]
Thanks, nice to hear that it is working well. Fairy-Stockfish already does support weaker/negative Skill Levels, which are used e.g. in fairyfishnet for pychess, but UCI_Elo still has the same narrower range as upstream. I will have a look at how to naturally extend the UCI_Elo formula.

**Comment by niklasf** [comment]
Ah, yes, I just realized that while making #317. I don't think precise Elo's are necessary for fishnet, so I guess I'll just use Skill Level in the meantime.

**Comment by vibranium21** [comment]
Sometimes humans beat my fairy-stockfish bot in variants I have opposite problem

**Comment by ianfab** [comment]
Closed in https://github.com/ianfab/Fairy-Stockfish/commit/f4513589b5082bfce813663e27c6db8616610b45
