### ISSUE TITLE
Illegal move after opponent castles in chess960

### ISSUE THREAD

**Issue by maxalexger** [ianfab/Fairy-Stockfish#318]
**Background:**
* Together with @QueensGambit I am training [CrazyAra](https://github.com/QueensGambit/CrazyAra) to support international chess variants
* I already searched for the error in this repository, as well as in the cutechess repo

**Description:**
* During chess960, after the opponent castles, fairy stockfish always makes an illegal move
* As far as I could tell, this happens every time the opponent castles
* I am using the latest version of `cutechess`, including https://github.com/alwey/cutechess/commit/ce2ffb786729acfe20ca013cc8e5974337e66c4b, which fixes `chess960` castling so far

**Printout:**
* I went to the `Cutechess GUI` and generetad an example
* More pgns can be found in [fischerandom-20210523-2006-Ara-FairySF-50x2-fast.zip](https://github.com/ianfab/Fairy-Stockfish/files/6528707/fischerandom-20210523-2006-Ara-FairySF-50x2-fast.zip)

```
<MultiAraTournament(2): bestmove g8h8
>fairy-stockfish(1): position fen rnqbbnkr/pppppppp/8/8/8/8/PPPPPPPP/RNQBBNKR w HAha - 0 1 moves d2d4 d7d5 c2c4 d5c4 c1c4 c7c5 b1d2 b8a6 a1c1 b7b5 c4c2 f8e6 d4c5 c8c5 c2b1 c5b6 d2f3 e8c6 f3e5 c6e8 e2e3 d8c7 d1f3 a8d8 e5c6 e6g5 c6d8 g5f3 g2f3 c7d8 h2h4 e8c6 e1a5 b6a5 c1c6 a6b4 c6c8 g8h8
>fairy-stockfish(1): isready
<MultiAraTournament(2): info string apply move to tree
<fairy-stockfish(1): readyok
>fairy-stockfish(1): go wtime 7737 btime 8686 winc 100 binc 100
<fairy-stockfish(1): info string classical evaluation enabled
<fairy-stockfish(1): info depth 1 seldepth 1 multipv 1 score cp -213 nodes 24 nps 24000 tbhits 0 time 1 pv g8g8
<fairy-stockfish(1): info depth 2 seldepth 2 multipv 1 score cp -213 nodes 49 nps 49000 tbhits 0 time 1 pv g8g8 a2a3
<fairy-stockfish(1): info depth 3 seldepth 3 multipv 1 score cp -213 nodes 76 nps 76000 tbhits 0 time 1 pv g8g8 a2a3 b4d5
<fairy-stockfish(1): info depth 4 seldepth 4 multipv 1 score cp -213 nodes 108 nps 108000 tbhits 0 time 1 pv g8g8 a2a3 b4d5 g1g2
<fairy-stockfish(1): info depth 5 seldepth 5 multipv 1 score cp -213 nodes 142 nps 142000 tbhits 0 time 1 pv g8g8 a2a3 b4d5 g1g2 d5b6
<fairy-stockfish(1): info depth 6 seldepth 6 multipv 1 score cp -213 nodes 180 nps 180000 tbhits 0 time 1 pv g8g8 a2a3 b4d5 g1g2 d5b6 c8c6
<fairy-stockfish(1): info depth 7 seldepth 7 multipv 1 score cp -213 nodes 224 nps 224000 tbhits 0 time 1 pv g8g8 a2a3 b4d5 g1g2 d5b6 c8c6 a5a6
<fairy-stockfish(1): info depth 8 seldepth 11 multipv 1 score cp -213 nodes 332 nps 332000 tbhits 0 time 1 pv g8g8 a2a3 b4d5 g1g2 d5b6 c8c6 a5a6 b1d3 e7e6 h4h5 d8f6
<fairy-stockfish(1): info depth 9 seldepth 14 multipv 1 score cp -209 nodes 1183 nps 591500 tbhits 0 time 2 pv g8g8 a2a3 b4d5 g1g2 a5b6 c8c1 e7e6 f1g3
<fairy-stockfish(1): info depth 10 seldepth 13 multipv 1 score cp -212 nodes 1837 nps 918500 tbhits 0 time 2 pv g8g8 a2a3 b4d5 g1g2 a5b6 f1g3 b6b7 c8c1 e7e6 g3e4
<fairy-stockfish(1): info depth 11 seldepth 14 multipv 1 score cp -205 nodes 2911 nps 970333 tbhits 0 time 3 pv g8g8 a2a3 b4d5 g1g2 d5b6 c8c6 a5a6 f1g3 a6b7 c6c1 b6c4 b1c2 f7f5 c1d1 e7e6
<fairy-stockfish(1): info depth 12 seldepth 18 multipv 1 score cp -207 nodes 6249 nps 892714 tbhits 0 time 7 pv g8g8 a2a3 b4d5 g1g2 d5b6 c8c6 e7e6 f1g3 b5b4 g3e4 h7h6 b1d3 d8e7 a3b4 a5b4 c6c7
<fairy-stockfish(1): info depth 13 seldepth 20 multipv 1 score cp -196 nodes 25385 nps 746617 tbhits 0 time 34 pv g8g8 a2a3 b4d5 b1d3 e7e6 f1g3 a5b6 h4h5 h7h6 g1g2 d5e7 c8c1 e7d5
<fairy-stockfish(1): info depth 14 seldepth 20 multipv 1 score cp -197 nodes 64049 nps 800612 tbhits 0 time 80 pv g8g8 a2a3 b4d5 f1g3 d5b6 c8c6 e7e6 g1g2 h7h6 c6c1 d8e7 b1c2 b6c4
<fairy-stockfish(1): info depth 15 seldepth 18 multipv 1 score cp -163 nodes 94439 nps 786991 tbhits 0 time 120 pv g8g8 a2a3 b4d5 f1g3 d5b6 c8c6 e7e6 g3e4 d8e7 g1g2 h7h6 e4d6 b5b4 a3b4 a5b4
<fairy-stockfish(1): info depth 16 seldepth 22 multipv 1 score cp -167 nodes 266474 nps 752751 tbhits 0 time 354 pv g8g8 f1g3 a5a6 c8c5 a6b6 c5c1 e7e6 g1g2 a7a5 h4h5 h7h6 a2a3 b4d5 h1d1
<fairy-stockfish(1): info depth 17 seldepth 22 multipv 1 score cp -158 nodes 305226 nps 759268 tbhits 0 time 402 pv g8g8 a2a3 b4d5 f1g3 d5b6 c8c6 e7e6 g3e4 d8e7 e4g5 g7g6 g5e4 b6c4 f3f4 h7h5 g1g2 f8d8
<fairy-stockfish(1): info depth 18 seldepth 28 multipv 1 score cp -173 nodes 537710 nps 786125 tbhits 0 time 684 pv g8g8 a2a3 b4d5 h4h5 h7h6 b1d3 e7e6 f1g3 a5a6 c8b8 a6d6 b8b5 d8b6 b5b3 f8d8 d3e2 d8c8 g1g1 d6e7 f1d1 b6c7
<fairy-stockfish(1): bestmove g8g8 ponder a2a3
>fairy-stockfish(1): isready
>MultiAraTournament(2): isready
<fairy-stockfish(1): readyok
<MultiAraTournament(2): readyok
```

**Comment by ianfab** [comment]
I suspect that something is going wrong here with setting the UCI_Chess960 option. When I run
```
setoption name UCI_Chess960 value true
position fen rnqbbnkr/pppppppp/8/8/8/8/PPPPPPPP/RNQBBNKR w HAha - 0 1 moves d2d4 d7d5 c2c4 d5c4 c1c4 c7c5 b1d2 b8a6 a1c1 b7b5 c4c2 f8e6 d4c5 c8c5 c2b1 c5b6 d2f3 e8c6 f3e5 c6e8 e2e3 d8c7 d1f3 a8d8 e5c6 e6g5 c6d8 g5f3 g2f3 c7d8 h2h4 e8c6 e1a5 b6a5 c1c6 a6b4 c6c8 g8h8
```
it works fine for me. However, without UCI_Chess960 being set the engine expects castling moves to be using standard chess notation (i.e., from->to, not from->rook). Therefore it rejects the castling move in 960 notation (g8h8) and returns the castling move in standard notation itself (g8g8). My assumption would be that official Stockfish behaves the same under these conditions. Do you have an excerpt from the engine debug log where it can be seen how cutechess sets the UCI_Variant and UCI_Chess960 options?

**Comment by ianfab** [comment]
> \>Fairy-Stockfish 130521(0): setoption name UCI_Variant value chess960

That's weird. Fairy-Stockfish's list of supported variants does not contain `chess960`, so I am confused why cutechess sends this. If it used UCI_Variant fischerandom and/or UCI_Chess960 true, it should work. @alwey Any idea? Looks like a bug in cutechess to me.

**Comment by maxalexger** [comment]
Thank you for the fast reply. I think this is pretty inconsistent from cutechess. I am neither able to select `Chess 960` from the dropdown in the cutechess GUI, nor set it via the cutechess-cli as `-variant chess960` (results in an error). However, if I select/send `fischerandom`, cutechess answers with `setoption name UCI_Variant value chess960`.

I tried to setting `UCI_Chess960` flag to true, while using the cutechess-cli, with: 
```
-engine name=FairyStockfish dir=/.../Engines/fairy-stockfish/ cmd=fairy-stockfish option.UCI_Chess960=true
```
but it does not work. Cutechess does not send the command (I checked with the `-debug` option). It seems to me that anyone who wants to use fairy with cutechess needs to rebuild the binary at the moment. Or do you have any other ideas?

**Comment by ianfab** [comment]
There is a workaround since Fairy-Stockfish allows to add variants at runtime, so you could add an alias for fischerandom named chess960. For that you can just create a variants.ini file containing `[chess960:fischerandom]` and then load this at startup by adding `arg="load /path/to/your/variants.ini"` to the cutechess args for the engine. This seems to work fine for me, but it of course is an ugly workaround, and should IMO be fixed in cutechess. Overriding the engine options UCI_Variant and UCI_Chess960 directly perhaps is not possible, since these are protected options that cutechess controls itself.

**Comment by maxalexger** [comment]
I agree, somehow the option `UCI_Chess960` seems to be protected. When using `option.UCI_Chess960=true`, cutechess actually tries to set the option (I must have overlooked it earlier), but cannot find it:
```
Warning: FairyStockfish doesn't have option UCI_Chess960
```
Additionally, the option is not visible in the cutechess GUI. That seems to be standard behavior, as I cannot see it for other engines (including our own) as well.

---

However, I just ran a short 10 game tournament with your workaround suggestions and it worked fine! Thank you! 
From my point of view, we can close this issue. Though I think others might run into the same problem.

**Comment by ianfab** [comment]
Thanks, I agree that in principle the behavior from Fairy-SF side seems ok, so we can close it. Whether fischerandom or chess960 should be used as a variant name maybe is debatable, but setting a variant name that the engine does not list as a valid option value after receiving `uci` seems like a clear violation of the protocol by cutechess to me. Feel free to raise the bug in the cutechess repo.
