### ISSUE TITLE
use of large board engines in Winboard 

### ISSUE THREAD

**Issue by musketeerchess** [ianfab/Fairy-Stockfish#320]
Hi
I use the following version of Winboard 4.9.2021.3721

I noticed that the Large Board engines of Fairy Stockfish that came after version 11.1 are not supported.
When checking for the variants in winboard menu when the large board engines are loaded, none is supported.

Is this a known issue?
I'm running an experiment and i need these large board engines for part of this experiment.

are you confortable with cutechess GUI? which chess variants this GUI supports?

**Comment by ianfab** [comment]
I have not seen this before, and I think it likely is a configuration issue. What exactly do you mean by "none is supported"? Are all variants greyed out, only the large-board ones, or are only the custom variants missing? Please also make sure that you
* Download the large-board version (containing "largeboard")
* Use the CECP/XBoard protocol, not UCI (no UCI2WB)
* Check if your issue corresponds to the second point in https://github.com/ianfab/Fairy-Stockfish/wiki/Graphical-user-interfaces#troubleshooting

For compatible GUIs see https://github.com/ianfab/Fairy-Stockfish/wiki/Graphical-user-interfaces. The list of variants supported by cutechess can be found in their documentation, e.g.,  https://github.com/cutechess/cutechess/blob/5e8558f4ea6a2a5270462d2f77a2a3942671a11f/projects/cli/res/doc/help.txt#L13-L82.

**Comment by ianfab** [comment]
Is it now solved? If so, please close the issue.
