### ISSUE TITLE
performance improvement for Evaluation<T>::value()

### ISSUE THREAD

**Issue by zzzhc** [ianfab/Fairy-Stockfish#321]
in Evaluation<T>::value(), `Options["UCI_Variant"] == "chess"` used too much time, about 46% of parent in my profile.
My suggestion is to change it to a bool and then move code to `ucioption.cpp` or make it a member of `class Evaluation`.

![image](https://user-images.githubusercontent.com/159371/121891881-9839cc80-cd4e-11eb-9833-65cd7bbbb9fb.png)

<img width="1434" alt="WX20210614-201104@2x" src="https://user-images.githubusercontent.com/159371/121891887-9bcd5380-cd4e-11eb-8cb3-e4cc3bb3edfa.png">

**Comment by ianfab** [comment]
Thanks for your suggestion. I also thought that accessing the option map might be slow and therefore tried to precalculate this information, but my attempt in http://www.variantfishtest.org:6543/tests/view/5fd3ca596e23db221d9e94fa did not yield an improvement. If you find a measurable speed improvement by such a change, please let me know.

It could also be that compiler optimizations might make a big difference here, so results might vary depending on which optimization level you use during profiling, but optimizations of course can make it harder to read profiling results.

**Comment by ianfab** [comment]
For now I am closing this since I currently don't have clear evidence that this can be sped up significantly, and the general topic is covered by #253. If you have more input on this, feel free to reopen this issue or comment on #253.
