### ISSUE TITLE
Playing strength against human opponents

### ISSUE THREAD

**Issue by ianfab** [ianfab/Fairy-Stockfish#34]
Playing strength against engine opponents is quite well known already, but the comparison against human opponents is more difficult. I started to collect estimates in https://github.com/ianfab/Fairy-Stockfish/wiki/Playing-strength#compared-to-human-opponents.

If you have an estimate for playing strength in a variant, feel free to add it in the wiki or leave a comment here. In order to have a standardized classification, I would suggest to use the following categories:
expert: 2000+
master: 2200+
elite: 2500+
superhuman: 2800+

**Comment by alwey** [comment]
I would like to suggest one category more:

expert: 2000+
master: 2200+
grandmaster: 2500+
elite: 2700+
superhuman: 3000+

**Comment by ianfab** [comment]
Whatever is intuitive for people is fine with me. For chess variants there just normally are not many top players, so the distinction between grandmaster and elite level might be difficult. Perhaps it was anyway not a good idea idea to add Elo numbers, since they are more difficult to translate to variants than a term or description of the level.
