### ISSUE TITLE
Crash while implementing antichess + ZH

### ISSUE THREAD

**Issue by Belzedar94** [ianfab/Fairy-Stockfish#340]
Console shuts down after "go infinite" for the next custom variant:

# Hybrid variant of antichess and crazyhouse
[antichesshouse:antichess]
startFen = rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR[] w KQkq - 0 1
pieceDrops = true
capturesToHand = true

It searches until depth 7 and then shuts down.

**Comment by ianfab** [comment]
Thanks, should be fixed now. By the way, castling rights in the FEN do not make sense for antichess (as opposed to giveaway), but this does not cause any issues, it just ignores them.
