### ISSUE TITLE
Crashes and illegal moves while implementing kinglet + ZH

### ISSUE THREAD

**Issue by Belzedar94** [ianfab/Fairy-Stockfish#341]
[Test1_10.txt](https://github.com/ianfab/Fairy-Stockfish/files/6939572/Test1_10.txt)

Attaching log of the game . Also, variant definition:

# Hybrid variant of Kinglet and crazyhouse
[kinglethouse:kinglet]
startFen = rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR[] w KQkq - 0 1
pieceDrops = true
capturesToHand = true

**Comment by ianfab** [comment]
Likely that are just issues with Winboard, since it might treat the commoners as royal if you use the "king" image for them. Can you reproduce any such issue on the command line?

**Comment by Belzedar94** [comment]
You are totally right. Thank you for pointing that out! I'll close the issue for now :)
