### ISSUE TITLE
Header Section has no max-width for bigger screens 

### ISSUE THREAD

**Issue by visualdenniss** [ianfab/Fairy-Stockfish#344]
Header does not have max-width
A simple comparison with lichess: 

<img width="2560" alt="Screen Shot 2021-08-23 at 16 41 31" src="https://user-images.githubusercontent.com/80699817/130467487-b39d3e29-b547-4b6e-996e-87093a31a4fc.png">

<img width="2560" alt="Screen Shot 2021-08-23 at 16 41 38" src="https://user-images.githubusercontent.com/80699817/130467426-3f4c08b2-5789-408f-b604-701f375cb67e.png">

**Comment by visualdenniss** [comment]
An easy possible fix is  just adding to the header element: 

max-width: 1800px; 
margin: 0 auto; 

1800px is what lichess uses, but 1600px etc works fine as well.

**Comment by ianfab** [comment]
Looks like your issue ended up in the wrong repo. Please use https://github.com/gbtami/pychess-variants/issues.
