### ISSUE TITLE
Hostage Chess

### ISSUE THREAD

**Issue by Finlip** [ianfab/Fairy-Stockfish#36]
This is a variant that I'm most interested in. https://www.hostagechess.com/ This website has a beautiful book about this variant also available. I wonder if Fairy-Stockfish could also support this variant.

**Comment by ianfab** [comment]
Thanks for your suggestion. Since we already have an open issue where we discuss this topic, I will close this one, but feel free to comment on https://github.com/ianfab/Fairy-Stockfish/issues/19.
