### ISSUE TITLE
Crashing Shogi FEN

### ISSUE THREAD

**Issue by gbtami** [ianfab/Fairy-Stockfish#370]
Yesterday someone created a Shogi game with this custom position and it crashed fishnet workers.
ln2k2nl/9/p+p+p+p+p+p+p+p+p+/9/9/9/PPPPPPPPP/1B+5R+1/LNSGKGSNL[-] w 0 1

![https://i.imgur.com/ofLiruT.png](https://i.imgur.com/ofLiruT.png)

**Comment by mtaktikos** [comment]
Obviously with p+, B+, R+ he meant promoted pieces. 
Not tested fishnet yet, but in GUI LiGround, the accepted notation for the promoted pieces is +p, +B, +R. 
Probably the author meant the FEN

ln2k2nl/9/+p+p+p+p+p+p+p+p+p/9/9/9/PPPPPPPPP/1+B5+R1/LNSGKGSNL[-] w - - 0 1
(see attached image)
![grafik](https://user-images.githubusercontent.com/36267869/134813924-accd5688-f5a8-458e-aac6-103b649365ff.png)

**Comment by ianfab** [comment]
Yes, he/she obviously confused the order of the notation. However, Fairy-SF currently neither robustly handles it on parsing, nor rejects it in the validation, so that is a bug. At least one of the two needs to be addressed.

**Comment by mtaktikos** [comment]
Obviously with p+, B+, R+ he meant promoted pieces. 
Not tested fishnet yet, but in GUI LiGround, the accepted notation for the promoted pieces is +p, +B, +R. 
Probably the author meant the FEN

ln2k2nl/9/+p+p+p+p+p+p+p+p+p/9/9/9/PPPPPPPPP/1+B5+R1/LNSGKGSNL[-] w - - 0 1
![grafik](https://user-images.githubusercontent.com/36267869/134813924-accd5688-f5a8-458e-aac6-103b649365ff.png)

So, valid Shogi-FENs cam be checked as follows: After the promotion-sign ("+"), it can never follow an end of range ("/") or a number of empty squares, but always the symbol of a piece.

**Comment by mtaktikos** [comment]
Yep. While checking for valid Shogi-FENs, it should be applied this rule:
After the promotion-sign ("+") it can never follow an end of range ("/") or a number of empty squares, but always the symbol of a piece

**Comment by gbtami** [comment]
Thx!
