### ISSUE TITLE
stockfish support of new pieces

### ISSUE THREAD

**Issue by elephanthawk** [ianfab/Fairy-Stockfish#380]
hello
new here, i wonder if the stockfish can use some fairy pieces like grasshopper, zigzag. i like SChess and i'd like to play it using these pieces.
![piece zigzag](https://user-images.githubusercontent.com/91793646/135725358-d3907256-c152-43b7-8c3d-8bbf773bfb5d.png)

**Comment by ianfab** [comment]
Hi, the grasshopper is already supported, so configuring an S-Chess like variant with that piece is possible. E.g., the configuration might look like below, also see https://github.com/ianfab/Fairy-Stockfish/wiki/Variant-configuration for more info.
```
[sgrasshopper:grasshopper]
variantTemplate = seirawan
customPiece1 = g:gQ
startFen = rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR[GGgg] w KQBCDFGkqbcdfg - 0 1
gating = true
seirawanGating = true
promotionPieceTypes = nbrqg
```
The zigzag bishop (aka "crooked bishop") currently is not supported and would be quite some effort to add. Considering that this is a very rare piece type in variants, it currently is unlikely that it will be added.

**Comment by elephanthawk** [comment]
> Hi, the grasshopper is already supported, so configuring an S-Chess like variant with that piece is possible. E.g., the configuration might look like below, also see https://github.com/ianfab/Fairy-Stockfish/wiki/Variant-configuration for more info.
> 
> ```
> [sgrasshopper:grasshopper]
> variantTemplate = seirawan
> customPiece1 = g:gQ
> startFen = rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR[GGgg] w KQBCDFGkqbcdfg - 0 1
> gating = true
> seirawanGating = true
> promotionPieceTypes = nbrqg
> ```
> 
> The zigzag bishop (aka "crooked bishop") currently is not supported and would be quite some effort to add. Considering that this is a very rare piece type in variants, it currently is unlikely that it will be added.

Hello
thank you for this accurate answer. you gave me a nice and easy method to add other pieces to one of my favorite games. thank you very much

**Comment by ianfab** [comment]
Glad I could help. Do you consider this resolved now, or would you like to keep this open as a feature request for the crooked bishop?

**Comment by elephanthawk** [comment]
Hi Fabiano
Can you consider keeping this open. It will be very nice to have the crooked bishop join the league. It's a very interesting piece, easy to understand but difficult to master. It becomes stronger in the middle and endgame as there are less obstacles. It will be nice to see how this piece behaves in front of a Bishop of the same square color. Thank you. 
I would love to use it to play Seirawan Chess.

Regards, Samuel.
