### ISSUE TITLE
Ambiguity in Xiangqi WXF notation

### ISSUE THREAD

**Issue by cloudfish** [ianfab/Fairy-Stockfish#395]
In apiutil.h the WXF notation uses format "15+1" only when there are >=3 pawns on a file. This will generate ambiguous notation when there are exactly two tandem pawns on each of the two files, since both front pawns will be referred to as "P+".

According to [this video](https://www.xqinenglish.com/index.php/en/basics-of-xiangqi/168-basics-of-xiangqi-chinese-chess-04-the-xiangqi-notation), World Xiangqi Rule (2018) clarified how to notate under this situation. The condition to use format "15+1" should be like:

if (count(our pawns on this piece's file)>=3 || (count(our pawns)>=2 on >=2 files on board) && count(our pawns on this piece's file)>1)

**Comment by ianfab** [comment]
Thanks for reporting.
