### ISSUE TITLE
Function nMoveRule doesn't work

### ISSUE THREAD

**Issue by mtaktikos** [ianfab/Fairy-Stockfish#401]
Defined in variants.ini a variant just to test this function:

[drawishchess:chess]
startFen: 8/8/8/k1p1p1p1/1pPpPpPp/1P1P1PRP/1K5R/8 w - - 0 1
nMoveRule: 7

FairySf announces mate in 8, instead of finding the draw due to the 7-move-rule
Also if you change nMoveRule to 6 or 5, it has no effect at all

**Comment by ianfab** [comment]
`:` is not a valid syntax to assign values, you need to use `=` instead. In recent development versions you can also validate this using the `check` command. Also see https://github.com/ianfab/Fairy-Stockfish/issues/388.

**Comment by mtaktikos** [comment]
Sry, corrected to the right syntax:

[drawishchess:chess]
startFen: 8/8/8/k1p1p1p1/1pPpPpPp/1P1P1PRP/1K5R/8 w - - 0 1
nMoveRule = 7

Now FairySF announces mate in 10, instead of a draw

**Comment by ianfab** [comment]
This topic of mate distances beyond the 50 move rule has been discussed extensively for official Stockfish, and their workarounds are also present in the Fairy-SF code base, e.g.,
https://github.com/ianfab/Fairy-Stockfish/blob/b3a6aa1e8ecc1cfddf4230a0cc9cb5afe87ba192/src/search.cpp#L800-L803
and
https://github.com/ianfab/Fairy-Stockfish/blob/b3a6aa1e8ecc1cfddf4230a0cc9cb5afe87ba192/src/search.cpp#L1762-L1763

Although in principle the hard-coded move count numbers there could be adjusted based on the n move rule to cover such edge cases, the upstream code already is just a workaround, so I currently see more cons than pros to this. Therefore I won't fix this. Maybe at some point this will be solved more fundamentally upstream, and then it can be merged from there.
