### ISSUE TITLE
Selfmate/misere chess

### ISSUE THREAD

**Issue by VinDeCourtenay** [ianfab/Fairy-Stockfish#404]
'Selfmate' chess means having the win condition as selfmate (being checkmated) rather than checkmating your opponent. This can be called [Misère chess](https://en.wikipedia.org/wiki/Mis%C3%A8re) because the rules are basically to lose according to the rules of standard chess (not Losing chess / Antichess, where you are forced to capture if possible).

Selfmate puzzles are popular among problemists. There is no good engine currently for solving these puzzles - the best solvers are probably Popeye and Gustav, but these can take hours to find even selfmate in 10 ([ref](http://www.kotesovec.cz/gustav/gustav_alybadix.htm)) - nor for trying to win at this variant in general.

I was wondering if it is feasible to adapt Stockfish to spot selfmates and play towards selfmate as the win condition instead of checkmate?

I notice [the constraints in FAQ](https://github.com/ianfab/Fairy-Stockfish/wiki/FAQ#can-the-gamevariant-xyz-be-supported) are met: two-player, alternate turns, perfect-information etc. In fact the game seems pretty similar to standard chess, and really much of the evaluation function could be the same since I believe accumulating material advantage is often beneficial for selfmates in the same way as checkmates ([ref2](https://chess.stackexchange.com/a/34886/26072)).

**Comment by Belzedar94** [comment]
I will let Fabian confirm it, but I think this can already be supported through variants.ini (https://github.com/ianfab/Fairy-Stockfish/wiki/Variant-configuration)

I guess the following config should work:

[Misere:chess]
checkmateValue = win

**Comment by ianfab** [comment]
Thanks for your suggestion. Just to make sure, you are talking about non-cooperative selfmates, and not cooperative helpmates, right? If so, the configuration suggested by Belzedar should in principle already be sufficient. However, it will likely only play towards selfmate by tactical means, and not long term strategically, since the evaluation does not consider this rule much yet, apart from skipping the bonus for king safety.

**Comment by VinDeCourtenay** [comment]
Yes, I'm talking about non-cooperative selfmates. (Just the same as normal chess except the goal is to be checkmated rather than deliver checkmate.) Is it likely that this configuration alone would yield an agent capable of spotting forced selfmates to a good depth like how `checkmateValue = loss` Stockfish easily solves checkmate problems?

I guess that for playing towards selfmate by strategic means there are not many well-known concepts differing from standard chess which could be used in the evaluation [1]. We need a large material advantage, space, greater mobility etc. However, we do need to move our King into opponent territory to get selfmated. Also, if it reaches an endgame, we need to immobilize, rather than capturing, the last few pawns/pieces of the opponent.


[1]: As an example game by humans, Pritchard (2007, p86-87) gives the following correspondence game in which White gives queen odds and Black plays Misere chess:
```
1 d4 d5 2 Nc3 c6 3 Nf3 g6 4 e4 e6 5 e5 Bb4 6 Bd2 Bxc3 7 Bxc3 b5 8 h4 h5 9 O-O-O a6 10 Ng5 f5 11 g3 Nh6 12 Bd3 Nf7 13 Bxf5 gxf5 14 Nxf7 Kxf7 15 Bd2 Nd7 16 Rhe1 c5 17 dxc5 Nxc5 18 Bg5 Qg8 19 Re3 Bb7 20 Rc3 Rc8 21 Be3 Nd7 22 Bd4 Rxc3 23 bxc3 a5 24 Kd2 a4 25 Rb1 Ba6 26 Rg1 Qg4 27 Rb1 Rc8 28 Rb4 Rc4 29 Rxc4 dxc4 30 a3 f4 31 Kc1 fxg3 32 fxg3 Qxg3 33 Kb2 Qxh4 34 Kc1 Qe1+ 35 Kb2 Qd1 36 Ba7 Nxe5 37 Bc5 h4 38 Bd4 Nc6 39 Be3 e5 40 Bf2 h3 41 Bg3 e4 42 Bf4 Ke6 43 Bg3 e3 44 Bf4 e2 45 Bg3 Kd7 46 Bh2 e1(Q) 47 Bf4 Qee2 48 Bg3 Qdxc2+ 49 Ka1 Qf1+ 50 Be1 Qd2 51 Kb1 h2 52 Ka1 h1(Q) 53 Kb1 Qf8 54 Ka1 Qxa3+ 55 Kb1 Qad6 56 Ka1 Qf6 57 Kb1 Kc7 58 Ka1 b4 59 Kb1 b3 60 Ka1 Kb6 61 Kb1 Ka5 62 Ka1 Ne7 63 Kb1 Nc8 64 Ka1 Bb5 65 Kb1 Qa6 66 Ka1 Nb6 67 Kb1 Qh7+ 68 Ka1 Qxc3+ 69 Bxc3#
```

**Comment by ianfab** [comment]
> Is it likely that this configuration alone would yield an agent capable of spotting forced selfmates to a good depth like how `checkmateValue = loss` Stockfish easily solves checkmate problems?

I could only guess, so I would suggest to just give it a try and judge by yourself.

**Comment by ianfab** [comment]
Since the variant is already supported via configuration I am closing this. If you want to discuss strategies or playing strength improvements for such variants, feel free to write about it on discord or in the github discussions.
