### ISSUE TITLE
Wrong time unit in UCCI

### ISSUE THREAD

**Issue by cloudfish** [ianfab/Fairy-Stockfish#406]
Fairy-SF makes moves in very shory time when I tested it with Chinese Xiangqi GUIs. According to the [specs](https://www.xqbase.com/protocol/cchess_ucci.htm) the default time unit in UCCI is seconds. It is strongly recommend that engines support the `usemillisec(check)` option. The GUI will usually send `setoption usemillisec true` to the engine if the engine sends `option usemillisec type check default true/false` before `ucciok`.

**Comment by ianfab** [comment]
Thanks. Does this only apply to the `go time` input or also the `info time` output of the engine? The spec is not very explicit on that.

**Comment by cloudfish** [comment]
This should only apply to the `go time` input. The `info time` should use msec regardless of the value of  `usemillisec(check)`.

1. In the spec of `usemillisec(check)` (五、3.(1)), it reads "in millisecond mode the time unit of the `go` command is millisecond".
2. In the spec of `info time` (五、11.(1)) it reads "the time unit is usually millisecond". Considering the spec of `usemillisec(check)`, it sounds like "we don't want to specify the unit, but msec is the convention".
3. In the GUI I tested, the time shown in engine output is correct (need to multiply the time control by 1000 though). This implies the unit of `info time` is msec, if the time given by Fairy-SF is used directly.

**Comment by ianfab** [comment]
Thanks, that makes it easier. Could you please test if https://github.com/ianfab/Fairy-Stockfish/pull/407 fixes the problems in the GUI?

**Comment by cloudfish** [comment]
That fixes the issue, thanks.
There is still one typo: it's `oppincrement` rather than `oppinc`.
