### ISSUE TITLE
Missing disambiguation in KyotoShogi

### ISSUE THREAD

**Issue by kezsulap** [ianfab/Fairy-Stockfish#408]
https://www.pychess.org/HmwxPoxD
Moves 5 and 9 are both described as just N-44+ despite there being two knights able to move to 44
![board_913536558139838475](https://user-images.githubusercontent.com/16389252/143780317-0b721328-34a4-45ad-8662-10d6c70a50fc.png)
1kmf3/1ps4/7/7/7/4SP1/3FMK1[] w - - 1 1
Same thing happens in Chennis in this position where moving either bishop both to e3 is described as just Be3=s+ and to b4 as Bb4=s

**Comment by ianfab** [comment]
Thanks. Looks like https://github.com/ianfab/Fairy-Stockfish/blob/ee0ba01e4d3ca8af3ae46fe43f7267d944514f73/src/apiutil.h#L209 does not capture ambiguity of promotion moves.

**Comment by gbtami** [comment]
@QueensGambit may I ask you to create a new release for ffish.js please?

**Comment by QueensGambit** [comment]
Sure, I just published a new release for ffish.js.
Sorry for the delay.

**Comment by gbtami** [comment]
Thx a lot!
