### ISSUE TITLE
Custom Crazyhouse variant, illegal pawn drop

### ISSUE THREAD

**Issue by CastleII** [ianfab/Fairy-Stockfish#410]
I configured a variant of Crazyhouse where it is not allowed to make drops with check, for this in variants.ini I put the following:

```
[unchecking:crazyhouse]
dropChecks = false
```
	
Then in WinBoard I added the engine with these parameters:
`	"Fairy-SF" /variant=unchecking -fcp "fairy-stockfish-largeboard_x86-64-modern.exe load variants.ini" -fd "C:\engines"
`
	
And I created a match between engines, choosing the menu "File > New Variant" and selecting the "unchecking" variant.

During the game this custom rule runs smoothly, but often in games the engine loses by making an illegal pawn drop, not against the custom rule, but impossible because it has no pawns in hand, example positions:

	4r3/1p1bP1kp/p5pp/3p4/4p3/3PP2P/PP2N1P1/R4RK1[PNNBBRnbrqq] b - - 0 43
	Engine wants to make P@f3
	
	6k1/pp1p2P1/2nn1PpR/3pRp1b/1q1p4/1P5Q/PPP3P1/1K1R4[NNBRbbqq] b - - 1 61
	Engine wants to make P@h7
	
In analysis mode it also considers these drops as the best moves.

**Comment by ianfab** [comment]
To me the FENs look suspicious, because the material does not sum up to what is there in the starting position. I guess WinBoard does not convert back promoted pawns when they are captured, which leads to missing pawns and extra rooks/queens in the first/second position. Fairy-Stockfish on the other hand likely correctly tracked the hand pieces and knows it should have a pawn and not a rook/queen in hand. If you can confirm that this is what happens, I think this can be closed.

**Comment by CastleII** [comment]
> I guess WinBoard does not convert back promoted pawns

It seems that you are right, I mean WinBoard, in crazyhouse games, converts back promoted pawns when they are captured.

But by choosing to play a game in the custom variant, it does not convert these pawns back.




So I guess that any custom crazyhouse variant will cause this bug in WinBoard.

Let me know if you know any other GUI to play this.

**Comment by CastleII** [comment]
@ianfab A possible simple solution would be to allow overwriting the rules of the variant through the INI file, e.g.: 
```
[crazyhouse]
dropChecks = false
```
	
This way WinBoard is made to believe that it is normal crazyhouse, and everything would work fine.

This would also allow to play these custom variants in other GUIs.

**Comment by ianfab** [comment]
For this special case it might be a potential workaround, but it is a rather rare scenario that a variant is a perfect subset of another one, so I do not consider it a major use case. Overwriting buit-in variants in principle could be allowed, but in my opinion it would cause too much confusion, e.g., related to variant inheritance.

In the end it is a GUI bug, so it should be fixed there. Overwriting the rules in the code and recompiling the engine can be a workaround in the meantime.
