### ISSUE TITLE
Hello where to download Chinese chess Syzygy Tablebase files? Is there a tool to generate Syzygy Tablebase Files?

### ISSUE THREAD

**Issue by shuangqiao999** [ianfab/Fairy-Stockfish#417]

**Comment by ianfab** [comment]
The short answer is that there are none, at least to my knowledge. Very space efficient tablebases usually make a lot of use of the rules of the game in the encoding, so it is far from trivial to adjust them for other games. The original source for the syzygy generation code for standard chess can be found at https://github.com/syzygy1/tb.
