### ISSUE TITLE
make net failed in tag fairy_sf_14_0_1_xq

### ISSUE THREAD

**Issue by meet-ai** [ianfab/Fairy-Stockfish#421]
make net
Default net: xiangqi-83f16c17fe26.nnue
https://tests.stockfishchess.org/api/nn/xiangqi-83f16c17fe26.nnue
Already available.
Failed download or xiangqi-83f16c17fe26.nnue corrupted, please delete!
Makefile:822: recipe for target 'net' failed

**Comment by ianfab** [comment]
This is basically expected. `make net` is for downloading standard chess networks. For variant networks there is no such infrastructure. The NNUE networks are attached to the [release](https://github.com/ianfab/Fairy-Stockfish/releases/tag/fairy_sf_14_0_1_xq), so you can download them from there.

The changes done on the `xq` branch were anyway only temporary just for the purpose of this release to simplify usage. These changes will not go into master. If you still want to compile it for your own hardware you can add `make_net=` to the make command to skip downloading a network.
