### ISSUE TITLE
bug in uci protocol

### ISSUE THREAD

**Issue by boardgame1** [ianfab/Fairy-Stockfish#425]
In uci protocol, setting UCI_Variant does not change 'Position pos' variable, so line 352 of 'loop' function in uci.cpp should change something like as follow.

this:
      else if (token == "setoption") setoption(is);

to this:
      else if (token == "setoption") {
          setoption(is);
          string s = is.str();
          if(s.find("UCI_Variant") !=string::npos) 
              pos.set(variants.find(Options["UCI_Variant"])->second, variants.find(Options["UCI_Variant"])->second->startFen, false, &states->back(), Threads.main());
      }

**Comment by ianfab** [comment]
This is not a bug. The UCI protocol always expects a `position` command before searching on a position (i.e., after `UCI_Variant` is set), see http://wbec-ridderkerk.nl/html/UCIProtocol.html.
