### ISSUE TITLE
更新 / upstream merges

### ISSUE THREAD

**Issue by KevinZHZ** [ianfab/Fairy-Stockfish#430]
我看到仙女鱼已经快3个月没有更新了 鳕鱼官网更新到了14.1 请问下作者是在更新权重，还是要在鳕鱼下个大版本 才会更新呢？

**Comment by ianfab** [comment]
I do merge updates from official Stockfish into Fairy-Stockfish, but I usually lag behind some time, since mixing upstream changes with changes for variants makes it harder to debug regressions and bugs, so I try to do upstream merges in bigger blocks instead of frequent smaller merges.

**Comment by KevinZHZ** [comment]
谢谢您再百忙之中能回复我，广大中国的象棋爱好者都对您做的努力表示万分感谢，都在等待新版的发布，最新的14,01进步很大 说明nnue对象棋的帮助确实很大，中国象棋爱好者都在期待这个项目越来越好，不断超越自己，越来越完善。
