### ISSUE TITLE
Xiangqi perpetual chasing rules missing

### ISSUE THREAD

**Issue by msomatt** [ianfab/Fairy-Stockfish#438]
Xiangqi has some complex Perpetual chasing rules mentioned here:
http://www.clubxiangqi.com/rules/
with further complex cases listed here:
http://www.clubxiangqi.com/rules/asiarule.htm
Whilst wikipedia also briefly discusses Perpetual checks/chasing:
https://en.wikipedia.org/wiki/Xiangqi

It seems to me that Perpetual Check is covered by `isOptionalGameEnd` but I didnt find Perpetual Chasing covered by this (e.g. when a rook chases a knight)

**Comment by ianfab** [comment]
This is a known limitation. If you have additional input on the topic feel free to comment on https://github.com/ianfab/Fairy-Stockfish/issues/55.
