### ISSUE TITLE
Please improve Fairy-Stockfish code for the new Apple Mac Studio

### ISSUE THREAD

**Issue by lex312** [ianfab/Fairy-Stockfish#445]
It should run much faster on this device: 
https://www.apple.com/mac-studio/

**Comment by gbtami** [comment]
You should donate a new Apple Mac Studio to ianfab to help his work on this issue :)

**Comment by ianfab** [comment]
Regarding architecture support I entirely rely on what official Stockfish provides, I do not maintain anything on my own there.
