### ISSUE TITLE
Large boards version issues illegal moves in PV

### ISSUE THREAD

**Issue by alwey** [ianfab/Fairy-Stockfish#45]
Since `6aab09c` cutechess reports dozens of illegal moves in PVs at least for standard chess. Version `9e617f4` does not issue any (AFAICS) illegal moves.

The problematic moves have target squares outside the board.

<stockfish-large-6aab09c(37): info depth 10 seldepth 16 multipv 1 score cp -20 nodes 1888 nps 269714 tbhits 0 time 7 pv g8f6 e1g1 f8c5 b5c6 d7c6 d2d3 d8e7 c1d2 c8g4 h2h3 g4f3 d1f3 f6d7
<stockfish-large-6aab09c(37): info depth 11 seldepth 21 multipv 1 score cp -25 nodes 10921 nps 280025 tbhits 0 time 39 pv g8f6 e1g1 f8c5 c2c3 e8g8 d2d4 c5b6 c1g5 e5d4 e4e5 h7h6 g5f6 g7f6 f3d4 c6d4 d1g4 g8h8 c3d4 d7d5 **g4l4** h8g7

**Comment by alwey** [comment]
<stockfish-large-6aab09c(37): info depth 10 seldepth 16 multipv 1 score cp -20 nodes 1888 nps 269714 tbhits 0 time 7 pv g8f6 e1g1 f8c5 b5c6 d7c6 d2d3 d8e7 c1d2 c8g4 h2h3 g4f3 d1f3 f6d7
<stockfish-large-6aab09c(37): info depth 11 seldepth 21 multipv 1 score cp -25 nodes 10921 nps 280025 tbhits 0 time 39 pv g8f6 e1g1 f8c5 c2c3 e8g8 d2d4 c5b6 c1g5 e5d4 e4e5 h7h6 g5f6 g7f6 f3d4 c6d4 d1g4 g8h8 c3d4 d7d5 **g4l4** h8g7

**Comment by ianfab** [comment]
Note: This bug is also in the 10.3 release. However, since the bug is only triggered in quiescence search, SF will never play an illegal move because of this, it just might report illegal moves somewhere down the PV. It also does not seem to have a significant impact on playing strength.

**Comment by ianfab** [comment]
Thanks for reporting, bug is confirmed.
