### ISSUE TITLE
More convenient CLI usage

### ISSUE THREAD

**Issue by ianfab** [ianfab/Fairy-Stockfish#47]
Now that the xboard protocol is supported, it already is relatively simple to play variants that are not supported by any GUI on the command line. What is mainly missing is to print the current board position in order to not have to use a physical board. Communication could e.g. work similar to Sjaak, see below. Any opinions?
```
>xboard

>board on
 8r n b q k b n r 
 7p p p p p p p p 
 6                
 5                
 4                
 3                
 2P P P P P P P P 
 1R N B Q K B N R *
  a b c d e f g h 
>e2e4
{verbose search output}
move d7d5
 8r n b q k b n r 
 7p p p   p p p p 
 6                
 5      p         
 4        P       
 3                
 2P P P P   P P P 
 1R N B Q K B N R *
  a b c d e f g h 
```

**Comment by GregNeto** [comment]
Great news! A "perft" command or a "go" or "on" command  would be great

**Comment by gbtami** [comment]
There is "go perft" see https://github.com/ianfab/Fairy-Stockfish/blob/master/src/uci.cpp#L108

**Comment by ianfab** [comment]
@GregNeto Thanks for your feedback. Can you please explain a bit more what you mean?
* Perft is already supported in UCI/USI/UCCI mode, so would you like to also have it when using xboard protocol? Or is it just about getting the list of legal moves in the position, i.e., not for engine testing but as input help?
* `go` already is the (protocol-compliant) command to start searching for all supported protocols, so what is missing there from your point of view?
* What would `on` supposed to do?

**Comment by GregNeto** [comment]
Sorry for my amateurish stuff:

- "on" is the same as "go" ;-), already implemented, sorry
- as UCI is a pain for CLI, a xboard "perft x" would be nice
- also the ability of reading fen in xboard mode would be great, but you implemented setboard, so this is fine ?!

One thing I could wish for would be the ability to randomize the first x moves, something like:
randomize x moves xxx  (where xxx is centipawns-difference in eval measured from the best move), or some other method to make the engine play diverse.

Together with a "self x" command where x are the number of games the engine plays with itself one could produce any number of games (which should be saved to a file, preferebly a pgn file) which might be interesting for evaluating a newly created variation. Or do I misunderstand something? Does xboard mode mean that every new variation works in xboard? I don't think so.

**Comment by ianfab** [comment]
* I can add `perft` for xboard, no problem.
* Setboard should be fine, or does it miss anything?
* For randomization you can e.g. try the `Skill Level` or `UCI_Elo` option (both do the same, UCI_Elo is just a bit more fine-grained), which more or less do what you suggest, see the [readme](https://github.com/ianfab/Fairy-Stockfish#skill-level).
* Automatic generation of games is a very specific task that should not be part of the engine, but it should be relatively easy to write a small script for this in any scripting language, e.g., python.
* All of the supported protocols can be used for any variant. Whether a certain combination of variant and protocol is useful just depends on whether there is a GUI supporting it. Even newly configured variants might work in XBoard/WinBoard (e.g., I also tried "xiangqihouse" and it worked fine), it just breaks if a variant uses too fancy features (partly because I so far did not implement the `piece` command of xboard).

**Comment by ianfab** [comment]
[Perft is now supported in xboard protocol](https://github.com/ianfab/Fairy-Stockfish/commit/95e5d52c0c18a5668264a45d29313df605719693):
```
xboard
perft 5
a2a3: 181046
b2b3: 215255
c2c3: 222861
d2d3: 328511
e2e3: 402988
f2f3: 178889
g2g3: 217210
h2h3: 181044
a2a4: 217832
b2b4: 216145
c2c4: 240082
d2d4: 361790
e2e4: 405385
f2f4: 198473
g2g4: 214048
h2h4: 218829
b1a3: 198572
b1c3: 234656
g1f3: 233491
g1h3: 198502

Nodes searched: 4865609
```

**Comment by GregNeto** [comment]
Danke; eine Kleinigkeit : in variants.ini , der chancellor sollte rook and
knight sein

Fabian Fichter <notifications@github.com> schrieb am Di., 12. Nov. 2019,
21:07:

**Comment by ianfab** [comment]
Thanks, fixed.

**Comment by ianfab** [comment]
I now added the `d` and `eval` commands also to the xboard protocol, so one can print the board state and the static evaluation, see examples below. Is there anything missing?
```
xboard
d
```
```
 +---+---+---+---+---+---+---+---+
 | r | n | b | q | k | b | n | r |
 +---+---+---+---+---+---+---+---+
 | p | p | p | p | p | p | p | p |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 | P | P | P | P | P | P | P | P |
 +---+---+---+---+---+---+---+---+
 | R | N | B | Q | K | B | N | R |
 +---+---+---+---+---+---+---+---+

Fen: rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
Sfen: rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR b - 1
Key: 3E22BF56052D0BF3
Checkers: 
```
```
eval
```
```
     Term    |    White    |    Black    |    Total   
             |   MG    EG  |   MG    EG  |   MG    EG 
 ------------+-------------+-------------+------------
    Material |  ----  ---- |  ----  ---- |  0.00  0.00
   Imbalance |  ----  ---- |  ----  ---- |  0.00  0.00
       Pawns |  0.53 -0.11 |  0.53 -0.11 |  0.00  0.00
     Knights |  0.00 -0.16 |  0.00 -0.16 |  0.00  0.00
     Bishops | -0.04 -0.35 | -0.04 -0.35 |  0.00  0.00
       Rooks | -0.22 -0.02 | -0.22 -0.02 |  0.00  0.00
      Queens |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
    Mobility | -0.92 -1.08 | -0.92 -1.08 |  0.00  0.00
 King safety |  0.70 -0.05 |  0.70 -0.05 |  0.00  0.00
     Threats |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
      Passed |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
       Space |  0.53  0.00 |  0.53  0.00 |  0.00  0.00
  Initiative |  ----  ---- |  ----  ---- |  0.00  0.00
     Variant |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
 ------------+-------------+-------------+------------
       Total |  ----  ---- |  ----  ---- |  0.00  0.00

Total evaluation: 0.13 (white side)
```

**Comment by GregNeto** [comment]
Looks good!

Can you show an example with a board and hand like in kyotoshogi? Have you left out the letters and numbers of the files and ranks on purpose?

And are the strength reducing options like Skill Level or UCI_Elo also available in xboard/cli mode?

**Comment by ianfab** [comment]
These commands with above output are also used in official SF, so the only thing I did was to now also make it available when using the xboard protocol instead of UCI, therefore leaving out the files and ranks was not my decision. The code that prints the board representation is: https://github.com/ianfab/Fairy-Stockfish/blob/ae0a8f3a9760c0aa0bd099736bba1eb135a94310/src/position.cpp#L88-L130

Pieces in hand and promoted pieces are not displayed very nicely, currently you have to read the pieces in hand and the unpromoted status of a promoted piece from the FEN/SFEN:
```
 +---+---+---+---+---+
 |   |   | k |   |   |
 +---+---+---+---+---+
 |   | n |   | g |   |
 +---+---+---+---+---+
 | B |   | s |   |   |
 +---+---+---+---+---+
 |   |   | P |   |   |
 +---+---+---+---+---+
 | p | g | K |   |   |
 +---+---+---+---+---+

Fen: 2k2/1n1+l1/+S1s2/2P2/p+lK2[N] w - - 1 12
Sfen: 2k2/1n1+l1/+S1s2/2P2/p+lK2 b N 23
Key: 6E4E394009D44C91
Checkers: b1 
```

All UCI options are also available when using the xboard protocol, you just need to use the xboard syntax to define an option, i.e., `option name=value`, e.g., `option Skill Level=10`, see also https://www.gnu.org/software/xboard/engine-intf.html#8.

**Comment by ianfab** [comment]
I now added more information to the output of `d`, so that one can easily see the side to move (*), the pockets, and the promoted pieces on the board. Example for kyoto shogi:
```

 +---+---+---+---+---+
 | n |   | k |   |   |   [ls]
 +---+---+---+---+---+
 |   |   |   |   |   |
 +---+---+---+---+---+
 |   |   | p |+p |   |
 +---+---+---+---+---+
 |   |   |   |   |   |
 +---+---+---+---+---+
 |   | L | K |+N |   | * [S]
 +---+---+---+---+---+

Fen: n1k2/5/2p+p1/5/1LK+N1[Sls] w - - 0 11
Sfen: n1k2/5/2p+p1/5/1LK+N1 b Sls 21
Key: 8162BEB17F1217AE
Checkers: 
```
