### ISSUE TITLE
Request for CMakeList.txt file.

### ISSUE THREAD

**Issue by silicon-ninja** [ianfab/Fairy-Stockfish#472]

**Comment by silicon-ninja** [comment]
The Problem is that Rust doesn't allow makefile to compile directly. the library needs cmakelist.txt to work with while building.

**Comment by ianfab** [comment]
Hi. I won't maintain additional build configuration for the engine on top of what I pull from official SF, but for a C++ API I will/would if there is a PR for it. To my knowledge @lakinwecker is currently working on that (https://github.com/Mind-Sports-Games/Fairy-Stockfish-Lib), don't know if you are in contact with him. He also wrote a Rust binding, not sure if you are aware of that https://github.com/Mind-Sports-Games/Fairy-Stockfish-Rust. Might be easier to discuss this real time on discord though.

**Comment by silicon-ninja** [comment]
Hey Fabian, i went through @lakinwecker lib. i faced a segmentation fault understood where it actually was and decided to make few bindings on my own for my functionality to work with my project.

**Comment by lakinwecker** [comment]
Please report the segmentation fault

**Comment by ianfab** [comment]
Further discussion about potential issues with the existing libs/bindings can then continue in the respective repos, so closing this here.
