### ISSUE TITLE
Separate variant for opponent player

### ISSUE THREAD

**Issue by GediminasMasaitis** [ianfab/Fairy-Stockfish#481]
I'd like to experiment with some asymmetric chess ideas such as disabling double pawn move for one side, seeing how much this affects playing strength as a handicap, or for example only allowing knights to go forward as in shogi. Some of these ideas can be implemented currently by using custom pieces, but some cannot.

For example I can set up a variant:
``` ini
[nodoublepawnmoves]
customPiece1 = p:fmWfceF
knight = n
bishop = b
rook = r
queen = q
king = k
```

But then if I want this variant only to apply to black and I supply the engine with `position startpos moves e2e4`, the engine can't set up that position, because the move is not in the legal move list according to this variant:

https://github.com/ianfab/Fairy-Stockfish/blob/ffdc517b77fdaf400ad4314bbc2e13d1f8ed7660/src/uci.cpp#L566-L570

While it may be possible to hack around this, instead of generating all legal moves and picking the one that matches the UCI notation, just generate a move from the UCI notation string and move the piece where the notation says for it to go, I think this would be a very bad solution. The engine wouldn't be able to predict opponent moves which don't follow the current loaded variant, and the engine would often lose on the spot from an unknown move.

Currently the selected variant applies to both colors. I think the best solution would be to add a separate UCI option, maybe `UCI_OpponentVariant`, and then when setting up a position and when generating moves during search, use the variant which is loaded for the side whose moves are being generated.

Of course there would be variant options which would be incompatible, board size being an obvious one, so there would need to be checks in order to determine if the opponent's variant is compatible with your own variant.

By doing this, it would even enable some very wild ideas, such as one side playing by chess rules, while the other side plays shogi.

**Comment by ianfab** [comment]
The idea sounds fancy, but in the scope of this project this won't work. How to model the rules of the game is a core design decision that is hard to change later on. In principle though you can create asymmetric variants with different armies, there are just a few limitations that can be problematic, e.g., the missing support for custom pawns. The solution to your use case should be to address these limitations, while a major redesign of the rule representation likely won't happen, so I am closing this.
