### ISSUE TITLE
Janggi Variant Bikjang Rule Error

### ISSUE THREAD

**Issue by cjssh1002** [ianfab/Fairy-Stockfish#485]
variant = janggi

In the bikjang situation of the Janggi variant, win is sum of the pieces points.

rh1a1a1er/4k4/c4h3/epp2pC1p/1c7/9/1PP1P1PP1/1CH6/4K4/1REA1AHER w 0 1
1. ed3  2. fe6

![3333](https://user-images.githubusercontent.com/63978900/169676659-5e1281f6-410d-4ffd-bc82-48f3e5b0ec9e.PNG)

In this situation, if the engine captures C , it becomes Bikjang, and Black win.
However, the engine tries to avoid the bikjang by moving P from f6 to e6.

Conclusion: In this situation, P must capture C and win the game. (Score win)

**Comment by ianfab** [comment]
Not a bug
