### ISSUE TITLE
Support for best move generation in ffish

### ISSUE THREAD

**Issue by RastislavKish** [ianfab/Fairy-Stockfish#488]
The [ffish NPM package](https://www.npmjs.com/package/ffish) already contains logics for creating a board, playing moves, loading positions etc.
It would be great, if it also allowed generation of the best move for a position according to the fairy-stockfish engine.
I've read through ffishjs.cpp, but I don't see such a function. If it's there and I just missed it, it could get mentioned in the package description, as it's an essential functionality of a game engine.

**Comment by ianfab** [comment]
Ffishjs is a library for the game logic, not an engine. If you want to use the engine in JavaScript, see the WASM port at https://github.com/ianfab/fairy-stockfish.wasm

**Comment by RastislavKish** [comment]
@ianfab ah, from the description on NPM:

> The package ffish.js is a high performance WebAssembly chess variant library based on Fairy-Stockfish.

I thought ffish is is actually the JS interface of the web assembly.
In such case, it would make sense to have sort of a genmove function on the Board object, since the library already has a loaded instance of the engine and the Board object information about the current position, which is required for move generation in UCI.

Is the Fairy-stockfish web assembly a completely different project then?

**Comment by ianfab** [comment]
They share large parts of the code base, but one is a relatively lightweight and general chess variant library not necessarily specific to Fairy-Stockfish, while the other is just a one to one equivalent of the native engine, including all the search and evaluation related stuff like transposition table, NNUE, etc. So they are two different animals.
