### ISSUE TITLE
您好作者，我看到鳕鱼官网更新了15，请问您又打算讲仙女更新到15的计划吗？

### ISSUE THREAD

**Issue by KevinZHZ** [ianfab/Fairy-Stockfish#502]
您好作者，我看到鳕鱼官网更新了15，请问您又打算讲仙女更新到15的计划吗？

**Comment by KevinZHZ** [comment]
Hello, author. I saw that the Stockfish has been updated to 15. Are you going to talk about the plan to update the fairy to 15?

**Comment by ianfab** [comment]
In general I do merge upstream changes from official Stockfish, but in order to ensure stability and due to lack of time I often postpone merges.

**Comment by KevinZHZ** [comment]
好的，谢谢您回复我的问题，今年还有半年时间 还早，您可以看下15有没有性能提升，完后在作出移植决定。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Fabian ***@***.***&gt;; 
发送时间: 2022年6月28日(星期二) 下午3:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ianfab/Fairy-Stockfish] 您好作者，我看到鳕鱼官网更新了15，请问您又打算讲仙女更新到15的计划吗？ (Issue #502)






一般来说，我会合并官方 Stockfish 的上游变化，但为了确保稳定性和由于时间不够，我经常推迟合并。

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
您收到这个消息是因为您创建了这个线程。留言 ID ***@***.***与&gt;
