### ISSUE TITLE
Fischer castling in Chess960 variants on xboard

### ISSUE THREAD

**Issue by rkb97** [ianfab/Fairy-Stockfish#524]
I am playing Chess960 variants on xboard and noticed an issue with castling. In xboard, when you click "New Shuffle Game" it gives you options for just "shuffle" and "Fischer castling".

Shuffle mixes the pieces but keeps rooks and king in the default position and castling is default and works fine that way. But only works if I have the xboard "Test Legality" setting turned off. If I have "Test Legality" turned on, when trying to castle I get "Illegal move O-O (rejected by first chess program)" unless ironically I have UCI_Chess960 as false and the engine will still play from its random starting position.

With Fischer castling, the rooks can be anywhere as long as the king is between them. But when I try to castle in a game like this, the engine doesn't accept it and popup box says "Illegal move O-O (rejected by first chess program)" regardless of the "Test Legality" setting. If I have "Test Legality" turned off the engine just quits and stops playing with no popup box.

So there may be miscommunication between the xboard GUI and the engine regarding the Test Legality or Fischer castling options. The expected behavior would be with Fischer castling, no matter where the king and rook start, they will end up in the default castle position as long as no pieces between them, not passing through check, and the squares are unoccupied. It seems the "Test Legality" gets rules from the engine based on whether or not UCI_Chess960 is set, it's just not complete in fischer castling. It could also be the way the move is sent as "O-O" or "O-O-O" shown in the error message is not familiar to the engine and expects moves such as e2e4, but not sure how to represent castling 2 pieces like that or how it handles default castles without a problem.

I know the UCI_Chess960 flag is supposed to allow castling with shuffled starting positions. But it doesn't seem to work if I enable Fischer castling in xboard. I would think Fischer castling would be included in the UCI_Chess960 rules, but maybe xboard isn't handling it properly. There is a xboard command-line option called -firstNeedsNoncompliantFEN which according to the xboard man pages can directly replace the castle rights and e.p. field of the FEN sent to the engine, but that didn't seem to help either.

I'm going to look into the xboard source code as well but posting here too. Any insight or things to try to work around it would be greatly appreciated. I'm fairly new to working with chess engines and xboard so I may be overlooking something. Can anybody else confirm this issue? In the screenshots attached, you can see an example that allows the castle moves in a solo game with no engine. Xboard shows it as king landing on a rook, but lands in the default castle position. This move wouldn't be allowed playing against the engine, but works fine in solo games.

Command I use to start xboard: 
xboard -fcp "fairy-stockfish" -firstOptions "UCI_Chess960=1" -shuffleOpenings -fischerCastling

Thank you all for your work on this project, this is my favorite chess engine for all the variants :) This is the only problem I have with it and I hope to contribute to getting this resolved, seeing if anyone else knows about this. Sorry if it's a long post I just wanted to be descriptive as possible.

![fischercastle](https://user-images.githubusercontent.com/10799276/193704437-0884f6a5-b13a-4d00-84f2-6bcca482cc85.png)

**Comment by rkb97** [comment]
I also try to see this only using the engine command line without the xboard gui.

```
$ fairy-stockfish
uci
setoption name UCI_Chess960 value true
ucinewgame
position fen bnnrqbkr/pppppppp/8/8/8/8/PPPPPPPP/BNNRQBKR w KQkq - 0 0 moves e2e4 e7e5 e1e3 d7d5 f1e2 c7c5 c1b3 f7f5
```

I notice the engine output FEN string contains HDhd for castling rights instead of KQkq, based on the rook files - so it seems to know something. It doesn't accept O-O or O-O-O as a move, so how would you tell the engine to castle in this scenario?

Based on xboard documentation here, https://www.gnu.org/software/xboard/engine-intf.html#8 if you scroll down to the MOVE section, it shows syntax for move commands being sent from xboard to engine:

Normal moves: e2e4
Castling: e1g1, e1c1, e8g8, e8c8
FischerRandom castling: O-O, O-O-O (oh, not zero)

I've tried castling using the regular syntax, trying g1c1 but that doesn't work. Any ideas to try?

**Comment by rkb97** [comment]
I was playing a game and the engine actually made the fischer castle move itself, but whenever I do it there's an error and doesn't allow it. Could there possibly be a problem with O-O and O-O-O not specifying which side of the board is on and relying on who's turn it is to determine that? Using the command line and trying lowercase o-o and o-o-o or without dashes oo and ooo doesn't work either, for either side I try it on. 

```
position fen bnnrqbkr/pppppppp/8/8/8/8/PPPPPPPP/BNNRQBKR w KQkq - 0 0 moves e2e4 e7e5 e1e3 e8e6 f1e2 f8e7 c1b3 c8b6 

or..

position fen bn1r2kr/ppppbppp/1n2q3/4p3/4P3/1N2Q3/PPPPBPPP/BN1R2KR w HDhd - 6 5
```

o-o, O-O, o-o-o, O-O-O, oo, OOO, etc all don't work as next move for either side. Does anybody know how to castle in this example?

Searching through the source code I see position.cpp includes code about castling for Chess960 from lines 700-750, which includes black and white castling using OO and OOO in the code and disambiguation for king square in Chess960. So I know it's there and has done it before, but I can't figure it out on my side with either xboard or using engine directly in command line. Anybody else confirm this issue or am I the only one? Feel free to point out if I'm missing something obvious. I thought xboard may have something to do with it but seeing how I can't figure out how to castle myself in the engine directly leaves me stuck.

Also tried explicitly adding v->castling = true; to Variant* chess960_variant() in variant.cpp and recompiling but that didn't change anything, either default is true or handled by v->chess960 = true already;

```
    // Chess960 aka Fischer random chess
    // https://en.wikipedia.org/wiki/Fischer_random_chess
    Variant* chess960_variant() {
        Variant* v = chess_variant()->init();
        v->chess960 = true;
        v->nnueAlias = "nn-";
+       v->castling = true;
        return v;
    }
```

**Comment by ianfab** [comment]
Thanks for your feedback. I am a bit in a rush right now so I didn't read everything, but what I can say is that generally the UCI protocol and Fairy-SF use "king captures rook" notation for castling in chess960, e.g., `e1h1` for short castling in the standard starting position. Fairy-SF doesn't support the xboard `O-O` notation as far as I remember, so likely this is the reason for the compatibility problems.

**Comment by rkb97** [comment]
Yeah that's it.

`position fen bn1r2kr/ppppbppp/1n2q3/4p3/4P3/1N2Q3/PPPPBPPP/BN1R2KR w HDhd - 6 5 moves g1d1 g8d8 a2a4`

Works as expected, now just need to get xboard to understand that and send the appropriate commands. Thanks for your help, currently looking into a fix.

**Comment by rkb97** [comment]
My solution was looking into the xboard source code, in backend.c

```
cps->useFEN960 = FALSE;
cps->useOOCastle = TRUE;
```

Changing these values around results in not sending O-O notation to the engine, but will still be printed with the PGN move history. I don't think these options can be changed anywhere in the GUI so I just recompiled from source and it works now with legality testing as well. Not an issue with Fairy-SF after all and easy enough to change xboard to fix it.
