### ISSUE TITLE
Support for a duck piece "@"

### ISSUE THREAD

**Issue by lbordowitz** [ianfab/Fairy-Stockfish#528]
Relating to the request in [PyChess for the Duck Chess variant](https://github.com/gbtami/pychess-variants/issues/1014), I think it would be useful to start by adding the duck piece. This would build towards the implementation of a Duck Chess variant.

The duck piece can move to any open space on the board. It cannot capture any piece. No piece can capture it. It can be jumped over by a knight.

I took a gander (no pun intended) at `piece.cpp`. I don't think the existing paradigm of directions/hopping are conducive to this piece type, but I'm also brand new to this code and would be very happy to be shown my misunderstanding. Once the duck piece is implemented, a follow-up issue should be made to track creating the Duck Chess variant.

Thank you!

**Comment by ianfab** [comment]
Thanks for your suggestion. Yes, the duck doesn't fit very well into the current modeling of piece types. However, in principle it should be feasible to add at least its movement, and likely also that it is uncapturable. The bigger problem is that even after that it still wouldn't really get any closer to supporting duck chess, since the double move characteristics of making a normal move and a duck move isn't supported at the moment and that is the much more problematic part. And if that latter part won't get supported I assume there isn't much value in adding the duck as it is very specific to this one variant.

**Comment by ianfab** [comment]
An experimental implementation of duck chess is available at https://github.com/ianfab/Fairy-Stockfish/tree/duck. This is **not** mergeable to master for maintainability reasons though, so currently it is unlikely to be supported as an official feature, but at least there is something to work with.

**Comment by defrag1971** [comment]
in many positions it crashes, here's an example:

```
xboard
variant duck
setboard 8/2k5/8/3*4/3P4/8/3K4/8 w - - 1 1
go
info string classical evaluation enabled
1 75 0 480 1 80000 0     d2c3,c3a1
2 138 1 1394 2 139400 0  d2c3,c3a1 c7b6,b6b1 d4d5,d5a1
3 138 1 2241 3 160071 0  d2c3,c3a1 c7b6,b6b1 d4d5,d5a1
4 175 2 3348 4 145565 0  d2e3,e3d6 c7b6,b6b1 d4d5,d5a1
5 372 4 5600 5 121739 0  d2e3,e3d6 c7b6,b6b1 e3f3,f3d5
6 120 13 11597 6 85272 0         d2c3,c3f6 c7d6,d6a1 c3c4,c4d5 d6c6,c6a1 d4d5,d5d6 c6d7,d7e4
7 144 20 16583 7 82915 0         d2d3,d3e4 c7c6,c6d5 d3d2,d2c7 c6d7,d7e4 d2c3,c3d6
8 141 45 39001 9 85905 0         d2c3,c3g7 c7d6,d6a1 c3c4,c4d5 d6c6,c6a1 d4d5,d5d6 c6d7,d7e4
9 139 65 63106 10 96640 0        d2d3,d3e4 c7c6,c6d5 d3e4,e4d6 c6c7,c7d5 e4e5,e5d7 c7b8,b8d5 e5f5,f5d6
10 192 78 79392 13 101007 0      d2d3,d3e4 c7c6,c6d5 d3e4,e4d6 c6c7,c7d5 e4e5,e5d7 c7c6,c6d5 e5e6,e6d6
11 92 126 124450 13 98769 0      d2d3,d3e4 c7c6,c6d5 d3e4,e4d6 c6b6,b6d5 e4e5,e5d7 b6b5,b5d5 e5e6,e6d6 b5b4,b4d5 e6f6,f6d6 b4b5,b5d5 f6g6,g6d6 b5b4,b4d5 g6f6,f6c6
12 110 162 165900 17 102092 0    d2e3,e3d6 c7d8,d8d5 e3f4,f4d7 d8c8,c8d5 f4e4,e4c7 c8b8,b8d5 e4f5,f5d7 b8a7,a7d5 f5e6,e6b6 a7b8,b8d5 e6d7,d7b7
Assertion failed: pc != NO_PIECE, file \Documents\Visual Studio 2019\Projects\Duck Chess\src\types.h, line 703
```

**Comment by ianfab** [comment]
Thanks, should be fixed now.

**Comment by defrag1971** [comment]
you're welcome.
after adding this code in psqt.cpp, playing strength improved by 100 elo, due to knights being far better than in standard chess.
(two knights are superior than the queen)

```
      if (v->duck && isSlider)
      {
          score = score / 5;
          score = score * 3;
      }
```

**Comment by ianfab** [comment]
I tested similar patches as well, but results weren't conclusive. Was your test result statistically significant?

**Comment by defrag1971** [comment]
> I tested similar patches as well, but results weren't conclusive. Was your test result statistically significant?

200 blitz games tested at 1'+½", the trend was clearly biased against the sliding pieces:

```
Rank Name                        Elo    +    - games score oppo. draws
   1 Duckfish @sliders at 67%    108   72   72    77   68%   -27   16%
   2 Duckfish @sliders at 50%     61   70   70    80   59%   -15    9%
   3 Duckfish                     -6   70   70    78   49%    -1   12%
   4 Duckfish @sliders at 150%   -47   70   70    79   42%    11   13%
   5 Duckfish @sliders at 33%   -116   74   74    80   33%    29    5%
```

**Comment by mosquitobird11** [comment]
Really love the implementation here with wall square, opens up a lot of possibilities like [Tamerlane Chess](https://en.wikipedia.org/wiki/Tamerlane_chess), or maybe even ridiculous stuff like [this](https://www.reddit.com/r/AnarchyChess/comments/ynyxow/new_map_just_dropped_placing_a_lilypad_takes_one/) which I am going to try to build now haha

**Comment by tryingsomestuff** [comment]
@defrag1971 may I ask which GUI you are using for testing duckchess please ?
Is there something else outhere apart from the winboard patch of HGM ?

**Comment by defrag1971** [comment]
> 

Using compiled Winboard as well.
As far as I know there's no other implemented GUI.

**Comment by ianfab** [comment]
Implemented in https://github.com/ianfab/Fairy-Stockfish/commit/873e76a4983af174019413a3d940a0ecd0933587. Note: Duck chess (and game of the amazons) require the `all=yes` flag during compilation to be included.
