### ISSUE TITLE
Confusion regarding mustDropType

### ISSUE THREAD

**Issue by inversed-ru** [ianfab/Fairy-Stockfish#549]
After reading the variants.ini comments I was under the impression that mustDropType specifies the pieces for which drops are mandatory. That is: if a player has such pieces in hand, one of them must be dropped if this is at all possible. This is not actually the case. "Mandatory" drop pieces in hand merely block non-drop moves, but dropping other pieces is still legal. Is this the intended behaviour? If so, perhaps the variants.ini comments should be clarified.

I'm developing a variant that starts with an empty board and a full set of pieces in hand. I want to implement a rule that prevents a player from dropping a major piece until all minor pieces have been dropped by said player. If I could make the minor piece drops truly mandatory, that'd be a good approximation to what I am trying to achieve.

**Comment by ianfab** [comment]
I think this is a bug. Likely this option hasn't really been used so far so it went unnoticed.

**Comment by inversed-ru** [comment]
I did not realize that mustDropType only supports a single piece. I don't really need a pure setup phase (placement without movement). I just want to constrain the order of drops so that major pieces cannot be dropped before dropping all minors. As far as I understand, two modifications are necessary to achieve that:

1. Support for multiple mustDropType pieces;
2. mustDropType logic working in the opposite way compared to the current implementation: drops of other pieces should be blocked but non-drop moves should be unaffected. Perhaps two different piece sets blocking drops/non-drops could be introduced.

Implementing the first modification and fixing mustDropType logic is also an option. It would not achieve exactly what I want, but should be pretty close (setup phase for minor pieces only).

**Comment by ianfab** [comment]
The reason why we currently have the mustDropPiece is that it came with basically zero overhead. Supporting multiple such pieces however would come at a computational overhead, and for a rather niche feature I think it isn't worth the trade-off, so I likely won't add that. But the existing bug should of course be fixed.

**Comment by inversed-ru** [comment]
I now realize that what I really want is not a multipiece mustDropPiece support, but a separate priorityDrops option. I'll try implementing it myself.
