### ISSUE TITLE
Dobutsu repetition should be draw

### ISSUE THREAD

**Issue by gbtami** [ianfab/Fairy-Stockfish#552]
https://www.pychess.org/hba7FX5P

**Comment by ianfab** [comment]
Closing as (partial) duplicate of #191.

**Comment by gbtami** [comment]
Ahh, sorry. I forget about that.

**Comment by gbtami** [comment]
Is it OK to create a PR with for Dobutsu with this addition lines?
        v->nFoldValue = VALUE_DRAW;
        v->perpetualCheckIllegal = true;

**Comment by ianfab** [comment]
Yes, would be nice, thanks. I guess you meant perpetual check illegal false though.  Also in order to keep the frequency of rule changes low it would be good to include the mandatoryPiecePromotion change as well.
