### ISSUE TITLE
Duck Chess with checks variant

### ISSUE THREAD

**Issue by PeterNjeim** [ianfab/Fairy-Stockfish#556]
The official and initial version of Duck Chess from https://duckchess.com (what Chess.com uses) doesn't support checks, allows castling while in check and through checks, and also uses a custom stalemate definition. I initially thought that maybe it was impossible to enforce, but after some thought I realised that it can be done, and return to original chess rules for checks, castling, and stalemates.

Basically, make the Duck moves that cause or keep the King in check illegal. However, if this means there are 0 remaining legal Duck moves, then make the corresponding pre-Duck move illegal altogether. This should be calculated before the player makes their pre-Duck move.

Castling takes a similar approach. A castle in standard chess is only legal when you aren't check and don't move through check. So, when scanning a castle move, you scan for any Duck moves that block the initial check, and the through-checks. If no Duck move is capable of blocking these, then the castle move should be illegal. If there is such a Duck move, then castling is legal, but the Duck is then restricted to only the squares that will block the castle-prohibiting check. Yes, you need to block the check with the Duck after you castle, or else you wouldn't have been able to castle in the first place.

As for stalemates, well now it becomes simple. If you aren't in check, and there are no legal pre-Duck moves, that's a stalemate and therefore a draw. There are no legal pre-Duck moves if all moves have 0 Duck moves that would prevent a check. Yes, that means you could theoretically be in a position where your opponent has moved the Duck to a square that blocks a check, and then you no longer have any legal moves, causing your opponent to stalemate you with the Duck. That's a rare stalemate though. A more common stalemate would be like in regular chess, where the opponent is trying to checkmate you with some intermediate non-checking moves, and accidentally puts you in a position where you have no more legal moves. However, it would still be rarer than standard Chess as you can always use the Duck to block whatever check you're stepping into. So in reality, the stalemate can only occur if the King is surrounded by double checks (or checks via a Knight, or checks where you're adjacent to a piece, basically, any check where you can't, well, block with the Duck), while the King itself is not in check.

As for checkmates, they are also simple. If you are in check, and there are no legal pre-Duck moves, you are checkmated and lose. There are no legal pre-Duck moves if all moves have 0 Duck moves that would prevent a check. Just as with stalemates, checkmates are harder. You need all 9 squares the King can occupy to be checked in a way that no Duck move can block, so either double checks, Knight checks, adjacent checks, etc.

I think this version of Duck Chess is better than the original, as it actually delivers on the "real chess but with a duck" message. Players can't accidentally checkmate themselves this way, and that's how it should be.

Thanks for your time as always.

**Comment by ianfab** [comment]
While I get the point of such rule modifications, with a similar spirit how it e.g. works for atomic, I think it would also be somewhat inconsistent. For the check of pseudo-legality (e.g. slider blockers) you would consider the previous duck placement, but for check of legality you would consider the new duck. But that aside considering that supporting duck chess already is challenging, I won't make efforts to support a variant of it that nobody else does yet, so I will stick to what chess.com and the other engines do as that is the currently popular variant. While I am not decided on which ruleset I would prefer personally, as a feature request I won't consider this unless the situation changes.

**Comment by ianfab** [comment]
FYI, some sort of this idea was enabled by #624. The main point of that PR simply was to fix an existing bug that prevented that kind of variant from working at all, I did not really explicitly implement specific behavior with respect to checkmate, castling, etc., so it just follows how the code currently behaves out of the box. And that should be that it is checkmate when the king is under attack considering the current duck placement and there is no normal+duck move combo that is legal, and analogous for stalemate. You can e.g. check the test positions in the unit tests.
