### ISSUE TITLE
I need help defining custom variants

### ISSUE THREAD

**Issue by tatratram** [ianfab/Fairy-Stockfish#561]
Hello.
I'm trying to use the largeboard version of Fairy-Stockfish to set up custom games and observe Fairy-Stockfish playing against itself.

As a test/practice run, I've tried recreating the regular shogi rules. However, it doesn't seem to work properly. What happens is that when a promoted piece gets captured, it enters the "pocket" still promoted, and it can't be brought out anymore. And then, when the bot tries to bring out a piece it thinks it has, WinBoard calls illegal move.

What am I doing wrong?

This is what I've written:
```# 9×9 shogi
[shogic]
variantTemplate = shogi
maxRank = 9
maxFile = 9
shogiPawn = p
lance = l
shogiKnight = n
silver = s
gold = g
bishop = b
dragonHorse = h
rook = r
bers = d
king = k
startFen = lnsgkgsnl/1r5b1/ppppppppp/9/9/9/PPPPPPPPP/1B5R1/LNSGKGSNL[-] w 0 1
pieceDrops = true
capturesToHand = true
promotionRank = 7
doubleStep = false
castling = false
promotedPieceType = l:g n:g p:g s:g b:h r:d
dropNoDoubled = p
immobilityIllegal = true
shogiPawnDropMateIllegal = true
stalemateValue = loss
nFoldRule = 4
nMoveRule = 0
perpetualCheckIllegal = true
pocketSize = 7
nFoldValue = loss
nFoldValueAbsolute = true
pieceToCharTable = PNBR.S...G........L..Kpnbr.s...g........l..k

**Comment by ianfab** [comment]
Very likely the behavior you see is in issue with WinBoard and has nothing to do with Fairy-SF. The position and pockets that Winboard displays does not necessarily represent the state of the engine, so the engine might represent the position correctly, but the displayed position could still be wrong. Your config looks fine to me.
