### ISSUE TITLE
Support default variant option in variants.ini

### ISSUE THREAD

**Issue by danielweiv** [ianfab/Fairy-Stockfish#57]
There are some xiangqi Gui programs which don't support variant option, so Fairy-Stockfish can not be loaded correctly.

**Comment by ianfab** [comment]
Thanks for the feedback. For the UCCI protocol xiangqi is already set as the default in order to work around this issue, but if the GUI uses a different protocol (e.g., UCI or xboard), this solution might not be sufficient. Can you please name GUIs where this issue occurs (and if possible also the protocols it supports)?

**Comment by danielweiv** [comment]
Sorry for the false alarm, I loaded the wrong engine fairy-stockfish_x86-64.exe instead of fairy-stockfish-largeboard_x86-64-modern.exe, the latter can be loaded corretly by the GUI I use. This issue can be closed now.

**Comment by danielweiv** [comment]
There are two mostly used GUIs, one is named 兵河五四 in chinese， the other is named 鲨鱼象棋. Both those engines can load  fairy-stockfish-largeboard correctly.

**Comment by ianfab** [comment]
No problem, and thanks for testing. It is good to know that it is working fine on different UCCI compatible GUIs as I had only tested it on one (gmchess on linux).

Do you by chance have some knowledge about comparison of human and engine strength in Xiangqi? E.g., I know from testing that Fairy-Stockfish should be slightly above the level of Elephant Eye, but I do not know how this relates to human rating as I am only rated ~1600 in Xiangqi, so I can only tell that it is far above my level.

**Comment by danielweiv** [comment]
After a rough survey, I find that many people think that eleeye engine strength should be comparable to a  (weak) Xiangqi master. According to http://www.dpxq.com/hldcg/dengjifen_1.html, the ELO rating of the last one in the top 160 professional Xiangqi players in China is about 2300, and the ELO rating of the best Xiangqi Player is 2723.
By the way, the best free Xiangqi eninge one can find on the Internet is NewGG, which you can download from https://github.com/leedavid/leela-chess-to-Chinese-Chess/releases/tag/v0.72. Those files are shared by the author of NewGG Xiangqi engine. NewGG is much stronger than eleeye or fairy-stockfish.
