### ISSUE TITLE
Any plan for a Mac version?

### ISSUE THREAD

**Issue by DaniSpringer** [ianfab/Fairy-Stockfish#577]
Or should I be trying a different one here? https://fairy-stockfish.github.io/download/ Maybe Linux?
Thanks

**Comment by gbtami** [comment]
See https://github.com/ianfab/Fairy-Stockfish/issues/391#issuecomment-961318791

**Comment by ianfab** [comment]
As mentioned in the above linked issue one can in principle compile Fairy-SF for Mac, they just aren't part of releases so far. For the request to include Mac binaries into releases there already is issue #542, so any discussion or progress in that direction should be tracked there.
