### ISSUE TITLE
Configurable piece types

### ISSUE THREAD

**Issue by ianfab** [ianfab/Fairy-Stockfish#58]
Allow to configure a limited number of piece types per variant in variant configuration.
* [x] Parse movement possibilities (e.g. using Betza notation)
* [x] Reserve slots for configurable piece types
* [x] Re-initialize (at least the user-defined) pieces on variant change
* [x] How to handle special piece types like hoppers (non_sliding_riders)?
* [x] Parse or calculate piece value
* [x] Documentation of new options and Betza notation

**Comment by CouchTomato87** [comment]
Is this what we were discussing earlier regarding shogun chess so that only 1 super piece can be on your side at any given time?

**Comment by ianfab** [comment]
No, this is about defining new piece types (e.g., let's say you want the vertical slider for okisaki shogi) on-the-fly in the config to not require code changes.
