### ISSUE TITLE
[resolved] - Game of Amazons queen piece is not correct

### ISSUE THREAD

**Issue by JamesHeppell** [ianfab/Fairy-Stockfish#584]
We are trying to implement the game of amazons (https://en.wikipedia.org/wiki/Game_of_the_Amazons) "amazons" in Fairy, but getting some unusual moves back from legal moves. 

The initial Fen is correct = "3q2q3/10/10/q8q/10/10/Q8Q/10/10/3Q2Q3[PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpppppppppppppppppppppppppppppppppppppppppppppp] w - - 0 1"

We get 146 legal moves when there should be 2176

The amazon queen piece is behaving like  (a shogi lance + shogi knight), whereas it should be behaving like a queen that cant capture (quiet_queen?). 

For example "d1c3pb5" is a legal move from the starting position which I don't think is correct. 

Any help investigating this would be appreciated - hoping it might be a change of piece type?

**Comment by gbtami** [comment]
It is already supported in Fairy.
See https://github.com/ianfab/Fairy-Stockfish/blob/master/src/variant.cpp#L1424

**Comment by JamesHeppell** [comment]
Sorry maybe I wasn't clear, we are trying to use the fairy version, and integrate that into our site.
However the legal moves list doesn't give the full set of moves we think it should.

**Comment by gbtami** [comment]
I see. Sry for misunderstanding it.

**Comment by ianfab** [comment]
The automatic perft tests include game of the amazons and test for 2176, so it should work correctly. Which commands are you using?

**Comment by JamesHeppell** [comment]
sorry perhaps I prematurely raised this bug, we are not using the latest version of fairy, so will make sure I'm testing against the latest version first and then report back!

**Comment by JamesHeppell** [comment]
We have checked and the perft test is passing for amazons giving 2176 moves. Therefore we probably have an issue with our integration. Therefore please close the ticket, and will get back in touch if we find any errors/issues. 
Thanks for the speedy replies.
