### ISSUE TITLE
Makruk: Lone king counting shouldn't apply when there are unpromoted pawns on the board

### ISSUE THREAD

**Issue by Fulmene** [ianfab/Fairy-Stockfish#75]

**Comment by ianfab** [comment]
Looks like the following changes should be required:

https://github.com/ianfab/Fairy-Stockfish/blob/8822131c9a25130fee4a03e5b7f635c068bf2f03/src/position.cpp#L1358-L1359
```
      && !count<PAWN>()
      && (!st->countingLimit || (captured && count<ALL_PIECES>(sideToMove) == 1))))
```
https://github.com/ianfab/Fairy-Stockfish/blob/8822131c9a25130fee4a03e5b7f635c068bf2f03/src/position.cpp#L1949

`if (count<PAWN>()`

I need to check the counting rules of ASEAN and Sittuyin to make sure that they are consistent in that regard.

**Comment by Fulmene** [comment]
From what I gather, ASEAN and Sittuyin doesn't require there to be no pawns on board.
