### ISSUE TITLE
WASM port of Fairy-Stockfish

### ISSUE THREAD

**Issue by smartchessguiapp** [ianfab/Fairy-Stockfish#82]
Does Fairy-Stockfish have a WASM port similar to that of multi variant Stockfish ( https://github.com/niklasf/stockfish.js/releases  )? I implemented S-Chess in my gui, but I cannot analyze in the browser without a WASM executable.

**Comment by ianfab** [comment]
It is also a requirement for a future local analysis feature on pychess, but unfortunately we do not have a WASM port yet.

**Comment by smartchessguiapp** [comment]
Anyway, I allowed several server engines in my gui and added Fairy-Stockfish as a new server engine. Its binaries work both locally under Windows, and on the Heroku server's linux too. Thanks a lot for making available those binaries. Of course with many users having a single server instance causes conflicts, so the ultimate solution is still a WASM port.

**Comment by ianfab** [comment]
For reference, the WASM fork is being worked on at https://github.com/ianfab/stockfish.wasm
