### ISSUE TITLE
FEN validation for pyffish and ffishjs

### ISSUE THREAD

**Issue by ianfab** [ianfab/Fairy-Stockfish#87]

**Comment by ianfab** [comment]
Open:
* [ ] Expose FEN validation in pyffish
* [ ] Refactor FEN validation to better align with variant configuration properties

**Comment by gbtami** [comment]
Sry for the late join, but I have some more suggestion we implemented in pychess.

Decline FEN if the king is in check, but the moving side is the opponent (in variants where king can't be captured)

Similar to how FEN with missing parts handled, it would be useful to accept drop variant FEN with no empty bracket pairs at all.

It would also be nice to accept lichess style crazyhouse FEN as well.

**Comment by ianfab** [comment]
Lichess style crazyhouse FENs are already supported. For the other ones I opened a new issue. Feel free to comment there if you come up with more scenarios.
